### ISSUE TITLE
Add chest rewards on Achievements

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#223]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=1641%3A11935&mode=design&t=f0r5D1IAZtsokm2g-1

When the user has completed an achievement, they have the option to claim their reward, which is accessible through a "Claim your rewards" button.

**Comment by Ayoazeez26** [comment]
@Kevils I would love to work on this.

**Comment by ayushtom** [comment]
@Ayoazeez26 Issues labelled with open for contribution are available for you to pick up. Other issues are currently on hold so it might not be considered as your onlydust contribution

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
