### ISSUE TITLE
New Quest with Flex 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#231]
## Idea
1/ Quizz (we can switch marketplaces with this quest)
2/ Transaction on Flex 
3/ Twitter Follow

## Needs
NFT from @Kevils + Quizz from Gurk

Website: https://flexing.gg/

**Comment by 3ameth** [comment]
You guys make it with the new feature with Flex NFTs it was so great, IMO keep it up fam <3 can wait to see what next feature with stark.id

**Comment by okste1234** [comment]
Hi @fricoben I'll love to contribute to this, but the link provided isn't active again. So, i'll appreciate some explanation...

**Comment by martinvibes** [comment]
please let me work on this
