### ISSUE TITLE
Feedback for the leaderboard after to get Nft or achievement

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#282]
Loom : https://www.loom.com/share/fe25ff8282ff4876b8bbdbd26b65f372

Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=2096%3A7437&mode=design&t=QCz7kBJmNg2Ft3fN-1

When the user completes their quest and receives their NFT or achievement, feedback is available and clickable on the page.

**Comment by JeffreyJoel** [comment]
Hi @Kevils, I would like to work on this.

**Comment by ayushtom** [comment]
@JeffreyJoel Issues labelled with `open for contribution` are available for you to pick up. Other issues are currently on hold so it might not be considered as your onlydust contribution
