### ISSUE TITLE
Notifications for the leaderboard

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#283]
Loom : https://www.loom.com/share/239857553cb743e1993098228f16a9c0

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=2107%3A8236&mode=design&t=QCz7kBJmNg2Ft3fN-1

When the user completes their quest and receives their NFT or achievement, notification appears to inform them how many positions they have gained through this quest.

**Comment by fricoben** [comment]
No need for notifications
