### ISSUE TITLE
Add new animations in lands

### ISSUE THREAD

**Issue by irisdv** [starknet-id/starknet.quest#288]
## Description
Adds animations for trees, avnu building, mobile phone building (first level of upcoming starknet quest achievement)

## PROPOSED TODO

- [ ] tree animations
- [ ] AVNU building
- [ ] mobile phone building

**Comment by icortes99** [comment]
Hello! Can I take this?

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
lands to be deprecated soon too
