### ISSUE TITLE
get_quest_participants is called twice

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/starknet.quest#310]
it is called for zero before the correct value, that's useless

<img width="296" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/41830259/6b71e4a4-075b-434f-a0df-4f0dacbaa853">

**Comment by ayushtom** [comment]
I think adding checks on `quest.id` on the quest.id should help with avoiding duplicate calls. Also i think we should put `questId` as a `state` variable
