### ISSUE TITLE
Add stats dashboard for quests

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#313]
Technical & Designer Brief: https://www.notion.so/lfg-labs/Starknet-Quest-Stats-Brief-71cf64b78cc241db82873d4f8d3806cb?pvs=4

**Comment by Kevils** [comment]
Loom : https://www.loom.com/share/ebd7d6f6650f4244bbe550c6e3470a6a

Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=2437%3A6976&mode=design&t=0UM3T6672ZMPU4TX-1
