### ISSUE TITLE
Improve loading

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/starknet.quest#328]
The page takes a second to load images and content. When it is loaded it looks beautiful, but while loading it's not perfect. The fact the image is missing and there is no loading animation might be the issue.

<img width="1420" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/41830259/28acdd3a-60d8-4ea5-9585-a36addd140b8">

**Comment by Subbitoooo** [comment]
Hello man, I think there are different things That you should do to improve loading time for starknet pages. You can
optimize images and media through compression, resizing, and using suitable formats, inimize file sizes by minifying and combining CSS, JavaScript, and HTML files, thereby reducing the number of HTTP requests.In additional, you can utilize browser caching for static resources and leverage a Content Delivery Network for global distribution of assets.
Enhance CSS and JavaScript efficiency by asynchronously loading critical components and eliminating unnecessary code and
reduce the number of HTTP requests by consolidating resources, utilizing image sprites, and employing data URIs for small images. Hope that this Thoughts could be helpful for you ;)

**Comment by ayushtom** [comment]
@Marchand-Nicolas we can add a spinner here on the image. Adding event listeners to the image to check if the image has loaded or not should help with attaching spinners to this section. Let me know if you have any questions so we can discuss on it

**Comment by fricoben** [comment]
Need to use a simple skeleton here, open for contributions for my OnlyDust friends

**Comment by him2312** [comment]
@ayushtom can you assign this issue to me?
I'll check to add the skeleton loader and explore to compress the `webp` images. 

The current ones are too big, and might be impacting page load performance. Will give it a shot.

**Comment by ayushtom** [comment]
Assigned!

**Comment by fricoben** [comment]
> [@ayushtom](https://github.com/ayushtom) can you assign this issue to me? I'll check to add the skeleton loader and explore to compress the `webp` images.
> 
> The current ones are too big, and might be impacting page load performance. Will give it a shot.

How are we on this ?

**Comment by raizo07** [comment]
Hello, if this is still open, I'd love to be assigned to it.

**Comment by him2312** [comment]
Hey @fricoben @ayushtom 

I've made some progress on this by adding the skeleton and adding image load priorities at relevant touch-points. Raising a WIP PR for early feedback.

I'm still exploring the right trade-off for image quality <> image size for larger images (more than >50Kb). Will close this within the next 1-2 days and open it up for review.

<img width="1440" alt="Screenshot 2024-03-21 at 10 32 19 AM" src="https://github.com/starknet-id/starknet.quest/assets/11074657/c63276ce-83ee-41d9-9fa5-e7c82e0e1fb6">

**Comment by him2312** [comment]
Related to the above pointer, did a lighthouse audit and we can safely reduce a few KiBs from the larger ones.

<img width="569" alt="Screenshot 2024-03-21 at 10 36 50 AM" src="https://github.com/starknet-id/starknet.quest/assets/11074657/5ab4475e-0747-4251-8c15-60f924f9f4ed">

**Comment by ayushtom** [comment]
@him2312 i can ask the designer to help with the reduced sizes with helpful tradeoffs to make it faster. Can you mention the list of all images which you would require to work on this?

**Comment by him2312** [comment]
@ayushtom I’ll change the images to the relevant resolution and we can check with the designer to have a look and get feedback.

**Comment by him2312** [comment]
Added `Skeleton` to the Featured quests section.

https://github.com/starknet-id/starknet.quest/assets/11074657/013cd448-3290-4b57-943d-4f98ab010431

**Comment by him2312** [comment]
Did an image compression for active quest images (Hero card) - and the lighthouse audit shows almost 1000 KiBs has been reduced compared to the [previous one](https://github.com/starknet-id/starknet.quest/issues/328#issuecomment-2011229545).

<img width="648" alt="Screenshot 2024-03-26 at 7 34 14 AM" src="https://github.com/starknet-id/starknet.quest/assets/11074657/d3da0e7f-91a5-4341-b96e-1a3e7695826a">
