### ISSUE TITLE
Refresh data button is not UX friendly

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#336]
Refresh data button is not UX friendly because users don't feel like it does something (because once you click nothing happens o, the front)

<img width="212" alt="Capture d’écran 2023-11-16 à 08 27 47" src="https://github.com/starknet-id/starknet.quest/assets/78437165/df5dda86-75d9-4518-a182-93037fe1a6a2">

**Comment by fricoben** [comment]
Let's add skeletons how you prefer

**Comment by ayushtom** [comment]
Cool
