### ISSUE TITLE
Web wallet dashboard CTA

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#355]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=1423%3A3475&mode=design&t=qSUYK5mFCwzCXwMr-1

Add a button to open the web-wallet dashboard when a user is connected with the web-wallet.

@ayushtom will choose among interested contributors

**Comment by fricoben** [comment]
@ayushtom added this as open for contrib

**Comment by raizo07** [comment]
Hello, Can you assign this task to me?

**Comment by Ayoazeez26** [comment]
@ayushtom I'm interested in picking this up

**Comment by krshishir1** [comment]
@ayushtom @fricoben this issue looks already solved

**Comment by ayushtom** [comment]
@Ayoazeez26 i am assigning this to you!

**Comment by Ayoazeez26** [comment]
@ayushtom is there where I can send you a message to get a couple of clarifications on this issue because some components are not being displayed on the dashboard

**Comment by ayushtom** [comment]
@Ayoazeez26 sure 
my telegram is -> @ayushtom

**Comment by fricoben** [comment]
Already in production but you go on this one https://github.com/starknet-id/starknet.quest/issues/559

@Ayoazeez26, the wallet to use is Argent Web Wallet and it includes a mail (so no braavos or anything related)
