### ISSUE TITLE
Focus Tree Second Quest

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#357]
## Description
Here we'll have a second quest with focus-tree where we'll asking people who participated in the first quest to be converted into real focus tree users.
 
## TASKS OF THE QUEST

1- Download the Focus Tree app on ios or android and sign-up (they need one email account to do so) 
2- Send your StarkQuest NFT X Focus Tree from previous quest to your Focus Tree wallet address
3- RT, Like the Starnet Quest tweet

You Can Verify everything through this API endpoint https://api.focustree.app/starknet-quest/paul@focustree.app

Be careful with this quest you'll need to talk to @Th0rgal before because we won't have an NFT reward (so we'll need to make some special changes (here is the process to learn how to create a quest https://app.skiff.com/file/cdec17a0-d7b1-4705-818f-e1920d79b74b)

**Comment by ayushtom** [comment]
https://github.com/starknet-id/api.starknet.quest/pull/136
using this task for api endpoint tracking.
have created a seperate issue for FE here #359
