### ISSUE TITLE
Add a new effect card on hover

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#363]
I think we can take our gradient blue and green or just green color for background effect : https://codepen.io/aaroniker/full/yLEPJXj

So we can also replace our actual effect hover by this new effect : 
![image](https://github.com/starknet-id/starknet.quest/assets/144677881/89086654-140e-4b81-bcfb-dfb564212877)

**Comment by fricoben** [comment]
overkill imo
