### ISSUE TITLE
Remove automatically the quest exipred on the list of Trending quests

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#367]
<img width="1437" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/144677881/51420186-f8d7-4de8-af2d-544ae4566df3">

Remove automatically a quest when it is exipred on the list of Trending quests

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/starknet-id/api.starknet.quest/pull/150
