### ISSUE TITLE
Add gamification to the claming of ERC20 in quest boosts

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#412]
ATM we only have a button for claiming. 

I think we can create a modal or take back the opening of the chest to gamify the process a bit. 

I'll let you make a design for the next sprint @Kevils and @ayushtom will be able to prod also before next sprint

**Comment by Kevils** [comment]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=2843%3A6376&mode=design&t=xuEASoeOKViJq6nf-1

Loom : https://www.loom.com/share/8b13f1ebf3c54b98b480432aadd052c6

**Comment by Kevils** [comment]
Maybe linked with this issue : https://github.com/starknet-id/starknet.quest/issues/223
