### ISSUE TITLE
Leaderboard V2

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#416]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/Starknet-Quest?type=design&node-id=2849%3A13026&mode=design&t=WAc19fxsXMjrybnh-1

Loom : https://www.loom.com/share/cf101968b2584d65ae84555abd2fb967

Description - 
- The current leaderboard already has the components you require in this issue.
- The part where the uer is supposed to be placed in the top of the leaderboard is something which i will modify in the api so you can directly use the api and i will manage the response you get.
- The endpoint used currently for fetching ranking is - 
`/leaderboard/get_ranking?addr=${addr}&page_size=${page_size}&shift=${shift}&duration=${duration}`

here the variables are as follows
- addr = address of the user 
- page_size = number of entries you need per response (not really needed in this issue since you set the length to 10 at all times now)
- shift = handle pagination here ( a positive number means the response moves towards the end of the table and a negative number means the response moves towards the top of the table)
- duration = handling the 3 types of durations - `week` , `month` and `all`

You can use this endpoint to get the data you require on the leaderboard. You can handle continuous pagination by joining the older responses to the new response and rendering the final combined list on the page

**Comment by krshishir1** [comment]
@ayushtom I am interested in working on this feature.

**Comment by Dharmik79** [comment]
@ayushtom  I would like to work on this.

**Comment by ayushtom** [comment]
@krshishir1 @Dharmik79 this issue is not prioritized and will need some new api endpoints so i would suggest to pick from any other available issue and comment there so i can assign to you

**Comment by kateberryd** [comment]
Can I be assigned this @ayushtom

**Comment by BlackStarkGoku** [comment]
I would like this one !

**Comment by ayushtom** [comment]
@BlackStarkGoku assigning you!
