### ISSUE TITLE
New loading animation

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#417]
Figm file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=2877%3A7478&mode=design&t=pTx5mgxszjPqgOVT-1

Loom : https://www.loom.com/share/1247f5cca1e24811b0dfdc4435b4c84a

**Comment by 0xkar4n** [comment]
Can I work on it?
I tried to download the Animation from Lottie but cannot do that.

**Comment by Kevils** [comment]
Have you access with this link ? : https://app.lottiefiles.com/share/2b563b89-dbc3-4a73-8c8f-3e2c5302e2ae

**Comment by 0xkar4n** [comment]
Thanks for the link, Now i can access it 👍

**Comment by Kevils** [comment]
> Thanks for the link, Now i can access it 👍

Ok perfect thanks ! 🙂

**Comment by 0xkar4n** [comment]
Hello @fricoben , I have created a PR(#424 ) for this issue.
Please review it and let me know if any changes are required.😃
