### ISSUE TITLE
Front-end adjustments for quests

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#442]
- Being able to have long titles without taking all the page like this 
<img width="1402" alt="Capture d’écran 2024-01-05 à 11 24 48" src="https://github.com/starknet-id/starknet.quest/assets/78437165/272b0c08-f814-42b4-afab-3aa093b4ee47">

- BRaavos wants to be able to have more text here so solution is 1) Add more width and 2) Add a way to break text and jump a line
<img width="728" alt="Capture d’écran 2024-01-05 à 11 25 09" src="https://github.com/starknet-id/starknet.quest/assets/78437165/488d7d07-a8a3-4d35-91bb-37d868ab14b7">

- Add possibility to add second reward with USDC logo

**Comment by ayushtom** [comment]
@Kevils me and ben were discussing to add a support of tags in the rewards section. The way we do currently in the quest card.
LMK if this sounds good to you and if there's any layout changes you would like for this in the rewards section
