### ISSUE TITLE
Improve Loading Time For Starknet pages

### ISSUE THREAD

**Issue by Subbitoooo** [starknet-id/starknet.quest#448]
Hello!:) I think there are different things That we should do to improve loading time for starknet pages. We can
optimize images and media through compression, resizing, and using suitable formats, inimize file sizes by minifying and combining CSS, JavaScript, and HTML files, thereby reducing the number of HTTP requests.In additional, we can utilize browser caching for static resources and leverage a Content Delivery Network for global distribution of assets.
Enhance CSS and JavaScript efficiency by asynchronously loading critical components and eliminating unnecessary code and
reduce the number of HTTP requests by consolidating resources, utilizing image sprites, and employing data URIs for small images. Finally, We should enable compression, such as gzip or Brotli, to shrink the size of files transferred between the server and the client and
optimize fonts by using only the required weights and styles, and consider local hosting or web-safe fonts.
What are your thoughts about that ?

**Comment by fricoben** [comment]
Not interested atm
