### ISSUE TITLE
Main domain enforcement pop-up showing when it shouldn't 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#454]
- https://discord.com/channels/1025416762835095674/1194636250951458936
- https://discord.com/channels/1025416762835095674/1194864264838656080
- https://discord.com/channels/1025416762835095674/1188127485481721907

**Comment by ayushtom** [comment]
fixed this on db by adding a missing field `mandatory_domain` on quests which had this issue. Have asked all users facing this issue on discord to recheck again

**Comment by ayushtom** [comment]
Error still persistent. I will need an address which is facing this issue.Since on my address it doesn't reproduce so it's not possible to check what might be the reason. Can connect with one of the users on a meet link to triage this

**Comment by fricoben** [comment]
More info here https://github.com/starknet-id/app.starknet.id/issues/651

**Comment by fricoben** [comment]
Should be good atm
