### ISSUE TITLE
If a quest was done and is expired, show it as done

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#461]
Some users is afraid they didn't make quests, so if a quest is done and is expired. You can show it as done but unclickable. Or maybe show something that can show the two informations

<img width="783" alt="Capture d’écran 2024-01-14 à 16 14 54" src="https://github.com/starknet-id/starknet.quest/assets/78437165/df8db6db-c856-4f53-89e4-084b5f3750c3">

**Comment by fricoben** [comment]
It's actually already the case but the old quest (AVNU ZKLEND ...) appeared as expired only so we have to fix that

**Comment by ktarun1419** [comment]
Can i start working on this issue?
