### ISSUE TITLE
Briq building and Carbonable building are not updating in land 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#477]
**Details**

Users who has BRIQ / CARBONABLE nft , their land page doesn't show the building of them respectively
Even after trying " Refresh data " option in our achievement page 

**Info**

Address : 0x02Fa93277E68AbC9C913e8e4098979842Fe66C0760ad13702Ed7f51D61499E12

NFT Portfolio : https://starkscan.co/contract/0x02fa93277e68abc9c913e8e4098979842fe66c0760ad13702ed7f51d61499e12#portfolio-sub-nfts

wallet : browser extension Argent
browser : Brave v1.61.114 (Jan 4, 2024)
Mobile or pc : Mac
Os version : MacOS Ventura, Version 13.4.1 (c)

**Screenshots :**
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/e30660cf-48fe-4747-b607-d5f3c5ceb573)

**Similar Discord tickets :**
https://discord.com/channels/1154728104112177262/1198067096731537479
https://discord.com/channels/1154728104112177262/1199294281253400578
https://discord.com/channels/1154728104112177262/1197890532572143716
https://discord.com/channels/1154728104112177262/1197233898900439171

**Comment by fricoben** [comment]
Closed
