### ISSUE TITLE
Raffle winners are unable to claim reward 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#481]
**Details**

We got two reports regarding this issue , were users unable to claim the reward

_Address 1 : 0x05D823320Fe77A791FDcEE21dC3FDADA4c660F4582369640C45217A854e4605E
Raffle reward for : https://starknet.quest/quest/104_ 
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/8da3d0b0-26d2-4e7d-b0c4-1209d3a110eb)

**HERE CHANGE THE REWARD AMOUNT TO IT SAYS YOU HAVE WON 1000 USDC 
IT MUST BE YOU HAVE WON 100 USDC ......**

![image](https://github.com/starknet-id/starknet.quest/assets/55296770/92037073-8073-467a-88fd-4d13c8f9c1dd)
Ticket link : https://discord.com/channels/1154728104112177262/1199393156131725423

_Address 2 : 0x19d081186f939258032ab321be2cef29816374b0d782d4a782e2d834799abad
Raffle reward for : https://starknet.quest/quest-boost/1_
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/52befaed-301b-4370-8469-b66ea475c4b6)

**HERE ALSO SAME ERROR IN NOTIFICATION 
FOR UPCOMING RAFFLE PLEASE CONSIDER TO MENTION THE EXACT AMOUNT USER GETS**

![image](https://github.com/starknet-id/starknet.quest/assets/55296770/4c715f04-5551-4e22-a75a-54a1b3f24b47)

**This user says that now he can't find option to open the chest , since it shows already opened** 

![image](https://github.com/starknet-id/starknet.quest/assets/55296770/c74d9a3e-98ca-4714-b95a-2f9b8a9ffdcd)

Ticket link : https://discord.com/channels/1154728104112177262/1199699497920503940

**Comment by fricoben** [comment]
fiw not working
