### ISSUE TITLE
No quest appears on the first page

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#489]
<img width="1009" alt="Capture d’écran 2024-01-29 à 17 02 16" src="https://github.com/starknet-id/starknet.quest/assets/78437165/85132d5b-67ee-43f2-b1e8-aee687c3497f">

**Comment by Marchand-Nicolas** [comment]
This issue https://github.com/starknet-id/starknet.quest/issues/445 removed completed quests from trending ones. As the featured quest is a random trending quest, if there is no trending quest left, the featured quest card is empty. So, users who completed every trending quests have this issue. As there is only one trending quest on starknet.quest, it happens to a lot of people.
