### ISSUE TITLE
0 USDC card shown on expired boost 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#491]
On the bar, it should show the normal amount of the boost
<img width="598" alt="Capture d’écran 2024-01-29 à 17 00 44" src="https://github.com/starknet-id/starknet.quest/assets/78437165/4ac4ece3-b08e-4547-82b9-f0b133fb8bc4">

On the bar, it should show the normal amount of the boost
<img width="492" alt="Capture d’écran 2024-01-29 à 17 00 30" src="https://github.com/starknet-id/starknet.quest/assets/78437165/acc1d49e-6cd7-43fb-8c14-b7dc7ea89fb2">

**Comment by ayushtom** [comment]
this should be solved after my pr merge here #486
