### ISSUE TITLE
TVL achievement is not being updated 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#508]
There are many users who claim that they have enough funds in their wallet for the TVL achievement unlock in land 
Here is one of the user info :
Address : 0x044038938462230747E638A548F92B6D1d1413771659221E8af786120B128f75
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/fbf4f164-6f99-404e-8811-eacd8daf2585)
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/69200134-5219-4626-a643-5f012467f364)

Discord ticket : https://discord.com/channels/1154728104112177262/1201237663244628068

**Comment by ktarun1419** [comment]
I want to work on this issue

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
