### ISSUE TITLE
Braavos level 3 building in not updating in land

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#509]
User has all the required 5 NFT of braavos journey 
Address  : 0x05585a88136981ee160e4e7119ddb95362ef23aa3d249eca44a1b84b165618be 
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/2ef49a9c-383c-4eb3-b3ed-682e082292d8)
Discord ticket : https://discord.com/channels/1154728104112177262/1204022283946037278

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
