### ISSUE TITLE
Create a new rango quest

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#513]
## Campaign name: Golden Castle Bridge Quest

⏰Starting date: Feb 28th 
💰Reward: 2,000$ for 20 people (each 100$)

Off-chain tasks: 
1. Follow Rango on X
2. Join Rango’s Discord
3. RT the campaign post
4. Do $50 swap with AVNU on Rango

If you are ok, we should just change a small edit in API for the amount of swap.

Notion page ==> https://www.notion.so/lfg-labs/Starknet-Quest-x-Rango-ed74472952c14e33af2174313337ea56?pvs=4

**Comment by revengexd** [comment]
Would likely to recommend just **25$ swap on AVNU on Rango**
will be decent amount
