### ISSUE TITLE
Hide finished boosted quests

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#520]
![telegram-cloud-photo-size-4-6003631507303939840-y](https://github.com/starknet-id/starknet.quest/assets/78437165/ef12437d-64fa-4ddc-b290-c8d35b7c599e)

These quests expired a long time ago, we need to hide them in some way. I propose after 3 weeks of claiming period. 

We hide the quest from this page
Every boost on this page has an expiry which you can check from the API response and you can use that to check how much time has passed since the expiry

expected time: Should be around 2 hours

**Comment by Signor1** [comment]
Can I work on this ?

**Comment by ayushtom** [comment]
@Signor1 Issues labelled with open for contribution are available for you to pick up. Other issues are currently on hold so it might not be considered as your onlydust contribution

**Comment by Dharmik79** [comment]
@ayushtom Can I work on this?

**Comment by Oshioke-Salaki** [comment]
Please i would love to work on this issue.

**Comment by ayushtom** [comment]
Assigned!
