### ISSUE TITLE
Fix sizing of cards in home page

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#521]
When we open the home page in mobile view, we see that the quest category cards are not appropriately sized(too narrow). If you look carefully , you would be able to notice that the width is not of the correct length. Your mission in this issue would be to figure out what is causing this and make the final result of a length which feels better on mobile (not too narrow or wide) and check if your changes are also not changing behaviour of any other card throughout the app.

Attaching Screenshot for reference
<img width="320" alt="Screenshot 2024-03-08 at 3 09 48 AM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/0cf5ccd2-325e-44d5-90ff-bd8d070f9f41">

**Comment by Khemmie-Ray** [comment]
hello, can I hop on this?

**Comment by ayushtom** [comment]
Yes! Assigned to you!

**Comment by Khemmie-Ray** [comment]
alright then!
