### ISSUE TITLE
Quiz options are not well displayed when option exceeds a certain length

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#522]
In the attached screenshot you might be able to notice that one of the options in the box overflows(2nd one). This is not good looking and happens only when the options start to become longer. Your task in the issue would be to fix the sizing of this box such that this box can take options of any length and doesn't break when it comes to mobile view. Make sure that all screen sizes are checked so that no overflow happens. Also apply small padding so that the text doesn't stick to the edges of the box. All the best!

<img width="319" alt="Screenshot 2024-03-08 at 3 14 22 AM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/6514564f-9c8c-4509-b7a4-4ddcd687007a">

**Comment by ktarun1419** [comment]
Hi @ayushtom  Can you assign this issue to me?

**Comment by ayushtom** [comment]
Assigned! All the best!

**Comment by ktarun1419** [comment]
@ayushtom  Is there any group where we can discuss about the issue?

**Comment by ayushtom** [comment]
you can message me on telegram on this handle - `ayushtom`
