### ISSUE TITLE
Remove hover action on expired quests

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#523]
In the below screenshot we see that even though the quest has expired, we are still able to see the border of white color on hovering over the card. We dont allow any clicks on the card if the quest has expired. The white border tends to mislead the user when they hover over it.

This is not good UX and i think we can improve it by not showing this border on hovering if that particular quest has expired. This means that if the quest is still live then showing the border is necessary but if it has expired then we can disable any css changes which happen on hover. All the best!

<img width="1107" alt="Screenshot 2024-03-08 at 3 19 12 AM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/aca75329-d9e0-4867-bf57-1fe899cffece">

**Comment by ktarun1419** [comment]
Hi @ayushtom  I want to work on this issue

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
I think you are also working on #522 so i would suggest doing them one at a time so that others also get some issues. Once you complete that one i can assign this!

**Comment by VictoriaAde** [comment]
Hi, @ayushtom, I would like to be assigned this issue.

**Comment by ayushtom** [comment]
hey @VictoriaAde , this issue is already resolved by @ktarun1419 in his PR. Although not officially assigned , he picked this one too since it was small change. I can assign you one of the other issues which are open for contribution!
