### ISSUE TITLE
Add shimmer on leaderboard on first load

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#524]
When the user comes on the leaderboard page, we make some api calls to get the latest leaderboard data and in that time when this call is made , the user is able to see the leaderboard but nothing indicates that we are fetching data. I think a loading state like a shimmer should help here which takes up a certain height and is displayed until we get the data. A similar implementation of this shimmer is seen when you change the page with the help of the pagination buttons below but it would be nice if we showed the shimmer when the user lands on the page for the first time. 

The code for example shimmers can be found under the `skeletons` folder
![photo_2024-03-07_21-27-23](https://github.com/starknet-id/starknet.quest/assets/41674634/422b7cc1-bcca-43cc-bc9c-9320d71960c6)

**Comment by Goodness5** [comment]
Assign this task to me

**Comment by ayushtom** [comment]
Assigned!

**Comment by Goodness5** [comment]
on it....

**Comment by Goodness5** [comment]
can i get mock data for this 
apparently without any data available some components won't be displayed

**Comment by ayushtom** [comment]
you can use the goerli endpoint and use it in your `env` file

**Comment by fricoben** [comment]
> can i get mock data for this apparently without any data available some components won't be displayed

@Goodness5 waiting for your PR on this or issue will go to someone else :)

**Comment by Goodness5** [comment]
Done here is a link to the PR
https://github.com/starknet-id/starknet.quest/pull/551
