### ISSUE TITLE
Implement color from tailwind config throughout the app

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#525]
We have defined a certain set of color codes in the `globals.css` file which will be used throughout the app. refer [here](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/styles/globals.css#L22)

We avoid using any other colors to keep the design consistent throughout the app. In some places in the codebase , although the colors used are the same , we have added the hex codes manually and don't use css variables to use these colors directly from the `globals.css` file.

An example of using colors from the global file using css variable can be found [here](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/styles/leaderboard.module.css#L143)

Your mission is to rectify all these places throughout the css files and replace them with their respective css variable. If there's any color which is being used more than 2-3 times and isn't defined in the global file, do let us know and we can define it in the global file so that it can be used throughout the app. All the best!

**Estimated time:** 20-30 minutes

**Comment by manoahLinks** [comment]
can i hop on this ?

**Comment by ayushtom** [comment]
hey sure!
