### ISSUE TITLE
Replace manual fetch calls with a common function

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#526]
We make many api calls throughout the app and often times we call the same endpoint on multiple pages. Using the same fetch call again and again by manually pasting the whole string url can be quite time taking if we are just reusing the same long code in multiple places. This also means that if we ever want to upgrade this url, we will have to manually change it in all the places we used the endpoint.

To solve this, we have started to make these api calls in a function of their own with an appropriate name which we call when we want to make that api call.We have a folder called `services` which contains the `apiService.ts` file. This file contains some functions which are used throughout the app and we try to make an active effort to use these functions only. Any new api call will get it's function defined here and we will call that function if we want to make that api call.

In some places in the app like [this](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/app/achievements/page.tsx#L34) we see that we have placed a fetch call. Your mission in this task would be to give all such endpoints it's respective function inside the `apiService.ts` file and replace the fetch call with the function you created. We have some functions already which we use  so you also you can see through it and start doing them for the other endpoints. This also means that you will have to carefully test if all the calls which you replaced are working as expected and also make sure you use the correct url when making this function. 

Remember one thing, 
Naming variables/functions is one of the most difficult things in software engineering as the name which you give has to mean the same for everyone who will go through your code to build on it so take your time to think and implement this for all endpoints and i am certain by the end of this you will have a good walkthrough of our codebase too

**Comment by him2312** [comment]
@ayushtom can you assign this issue to me?
