### ISSUE TITLE
Add contributors list to readme

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#534]
Add contributors list to readme like so https://github.com/keep-starknet-strange/madara?tab=readme-ov-file#contributors-

You need to use this GitHub app https://github.com/apps/allcontributors

[Here is an example](https://github.com/cairo-book/cairo-book/issues/174) issue I made on the CairoBook where each contributors have to ask to be added to the issue

**Comment by Khemmie-Ray** [comment]
@fricoben can I hop on this?

**Comment by fishonamos** [comment]
Hi @fricoben. Can I work on this?

**Comment by ayushtom** [comment]
@Khemmie-Ray  @fishonamos Issues labelled with open for contribution are available for you to pick up. Other issues are currently on hold so it might not be considered as your onlydust contribution

**Comment by Khemmie-Ray** [comment]
Noted! Thanks

**Comment by fishonamos** [comment]
I have created a pull request for this.
