### ISSUE TITLE
Analytics front-end typo

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#540]
On our `Analytics` section we have a small typo where we don't have any `%` sign here so we don't understand what's the number 

![image](https://github.com/starknet-id/starknet.quest/assets/78437165/3b736054-f4e0-41a7-ab42-1cad8d856272)

Also change the title from - `Tasks Completion over time` to `Quests Completion over time`

**Comment by VictoriaAde** [comment]
Please @fricoben, can I be assigned to this?

**Comment by ayushtom** [comment]
Assigned to you @VictoriaAde

**Comment by fricoben** [comment]
@VictoriaAde waiting for your PR on this or issue will go to someone else :)

**Comment by VictoriaAde** [comment]
Hello @fricoben, apologies for the delay, I'm on the process of making a PR.
