### ISSUE TITLE
Land page is not loading ! 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#547]
https://www.loom.com/share/b6ddcfafa9824be091cda399ce0f80cc?sid=972b892b-62fe-4325-b348-53335a919a6c

**Comment by icortes99** [comment]
It seems that this problem has already been resolved since I tried to re-create it and didn't happen.
(I'm an OnlyDust user)

**Comment by ayushtom** [comment]
Land page will also be deprecated soon
https://github.com/starknet-id/starknet.quest/issues/570#issuecomment-2028748233
