### ISSUE TITLE
Error in Quest time shown left to expire !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#552]
https://www.loom.com/share/d3169af712e34f7db2148b29e3669e38?sid=73bbe779-62ed-4396-aae4-9dacfb968cce

**Comment by raizo07** [comment]
Hello, can I be assigned to work on this?

**Comment by Ayoazeez26** [comment]
@ayushtom @fricoben  I'd like to work on this, can this be assigned to me?

**Comment by krshishir1** [comment]
Hey @fricoben @ayushtom, I am working on this issue, Can you assign this to me?

**Comment by JeffreyJoel** [comment]
Hi, @Ayoazeez26 @fricoben, can I work on this?

**Comment by ayushtom** [comment]
@raizo07  I am assigning this to you!
@Ayoazeez26 @JeffreyJoel @krshishir1 I would suggest you guys to pick some other issues which are open since i will assign the issues on a first come first serve basis as in this case.

**Comment by ayushtom** [comment]
Closing this issue since this is a backend issue

**Comment by raizo07** [comment]
@ayushtom Is the backend returning a wrong time or it's not being parsed properly on the frontend?

**Comment by ayushtom** [comment]
Backend is returning wrong time so not much can be done on front. We will fix it on the back by tweaking a value and everything should be good to go

**Comment by raizo07** [comment]
Alright then, I'm available to be assigned to other issues.

**Comment by ayushtom** [comment]
Sure! You can see if there's any other issue you can work on. Comment there and i'll assign it to you!
