### ISSUE TITLE
New navbar

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#560]
Loom : https://www.loom.com/share/770e28863156472d902b5d7906c2391d

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=3615%3A11321&mode=design&t=3uxjfNZImJUAclf6-1

**Comment by Ayoazeez26** [comment]
@ayushtom I'd like to take this

**Comment by raizo07** [comment]
@ayushtom I'd love to work on this.

**Comment by ayushtom** [comment]
@Ayoazeez26 assigned to you!

**Comment by ayushtom** [comment]
@raizo07 i would suggest you to complete the issue you are already assigned on :)

**Comment by Dharmik79** [comment]
@Ayoazeez26 I would like to work on this.

**Comment by ayushtom** [comment]
@Dharmik79 since this issue is already assigned i would suggest you to pick any other available issue

**Comment by ayushtom** [comment]
@Ayoazeez26 i would suggest you to keep the options in the navbar as `Quests` and `Leaderboard`. No need of adding leaderboard button in the wallet button. We can show only two options in the navbar for now and remove the others
