### ISSUE TITLE
New rule for displaying the first section & change some details

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#561]
Loom : https://www.loom.com/share/19b27eab627a4c718812d15cba4877f7

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=3618%3A21491&mode=design&t=3uxjfNZImJUAclf6-1

**Comment by Ayoazeez26** [comment]
@ayushtom I'd like to work on this

**Comment by kenkomu** [comment]
@ayushtom I would like to work on this.

**Comment by ayushtom** [comment]
This is a api issue majorly. I'll work on this

**Comment by kateberryd** [comment]
@ayushtom I would love to work on this
