### ISSUE TITLE
New quest page

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#562]
Loom : https://www.loom.com/share/c1d763dbb2f741a1a3de9bde5c756d97

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=3627%3A23404&mode=design&t=bqtgDvSaJdzInFGY-1

EXPECTED TIME TO COMPLETE: 3 BUSINESS DAYS

**Comment by Ayoazeez26** [comment]
@ayushtom I'd like to work on this as well, thanks

**Comment by ayushtom** [comment]
@Ayoazeez26 i would suggest to finish a issue and then come back to this. If no one is assigned at the time then you can pick this. I believe i already assigned you #560

**Comment by kenkomu** [comment]
@ayushtom I would like to work on this.

**Comment by miiikovic** [comment]
I would love to work on this as well

**Comment by ayushtom** [comment]
@kenkomu assigned to you!

**Comment by Kevils** [comment]
Notice: We have removed the 'done quest' tab that you can see in the Loom video, because it will now be located on the dashboard page
![image](https://github.com/starknet-id/starknet.quest/assets/144677881/bdd6ec91-a975-4161-9fda-4ce32bcdc6ce)

**Comment by BlackStarkGoku** [comment]
I would love to contribute if re-assigned !

**Comment by kenkomu** [comment]
@ayushtom Could we arrange a meeting I would need some clarifications on something?

**Comment by ayushtom** [comment]
yes @kenkomu . please reach out to me @ayushtom on telegram

**Comment by ayushtom** [comment]
@kenkomu can you also raise a draft PR with the progress you've made

**Comment by kenkomu** [comment]
> yes @kenkomu . please reach out to me @ayushtom on telegram

Okay I will reach out

**Comment by ayushtom** [comment]
@kenkomu i haven't seen a PR yet and also i don't think i can go beyond the alloted time for you on this one. Unassigning

**Comment by ayushtom** [comment]
@BlackStarkGoku assigning you! All the best!
