### ISSUE TITLE
Quest - Twitter & discord verification task issue !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#563]
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/04378387-518a-4794-9c5d-1b0393c793e0)

**Some users claim that they are unable to verify the Twitter & discord task for the 
quest : https://starknet.quest/quest/1**

![image](https://github.com/starknet-id/starknet.quest/assets/55296770/07439ecf-d870-453f-9ac1-5dbdb6c52abd)

**Their domain is set as MAIN DOMAIN , Twitter & Discord has been verified** 

Error shown : **CONTRACT ERROR**

Users ticket :
https://discord.com/channels/1025416762835095674/1218192577723895959
https://discord.com/channels/1025416762835095674/1222653934619987998

**Comment by fricoben** [comment]
API problem due to the Cairo 1 upgrade
