### ISSUE TITLE
Handle invalid boost ids page

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#567]
Currently when we navigate to - https://starknet.quest/quest-boost/27, you might notice that the loader skeleton doesn't go away. We are indeed stuck in a infinite loading state because there is no boost id as 27. In the same scenario if someone comes on page - https://starknet.quest/quest-boost/9 then you will see that the skeleton only exists till we fetch data and once we do ,the page is filled with relevant data.

Your task is this issue would be to handle these cases where the boost id doesnt not exist and instead of showing a infinite loading state, we will display a page which looks similar to this - https://starknet.quest/quest/29. If there is no data for a boost id then show a message like - `This boost doesn't exist !` and the button should read as - `GO BACK TO BOOSTS`. 

The expected time on this issue should be around - 0.5 business day

**Comment by Ayoazeez26** [comment]
@ayushtom I would love to work on this

**Comment by Xaxxoo** [comment]
Hi @ayushtom assign this to me please.

**Comment by ayushtom** [comment]
@Xaxxoo assigned to you!. I think @Ayoazeez26 you are already having one issue

**Comment by Xaxxoo** [comment]
Hi @ayushtom, I have completed the task and created a pull request. Thank you for the opportunity to contribute.

**Comment by Xaxxoo** [comment]
Hi, I was wondering if there’s a reward for this task.
