### ISSUE TITLE
Carbonable achievement not getting verified ! 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#570]
https://www.loom.com/share/f501c3027ac8472390e2a63ac946e549?sid=322b4d26-e822-49cc-86cd-d7969ea342f4

**Comment by krshishir1** [comment]
@ayushtom assign this to me!

**Comment by ayushtom** [comment]
@krshishir1 this is a backend issue and would be handled in a seperate repo. Please feel free to pick from the other available issues

**Comment by fricoben** [comment]
Hey achievement will be deprecated soon no need to maintain them atm
