### ISSUE TITLE
New Quest Reward Flow

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#573]
Loom : https://www.loom.com/share/84bb44e008ae4a7fa0380088ab662e6c

Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=3723%3A23765&mode=design&t=T9OoOKnLhybS6HOd-1

**Comment by raizo07** [comment]
@ayushtom Kindly assign this to me

**Comment by Ayoazeez26** [comment]
@ayushtom can I pick this up?

**Comment by zintarh** [comment]
@ayushtom I would love to work on this

**Comment by ayushtom** [comment]
@Ayoazeez26 assigned to you!

@raizo07 i believe you have an issue which isn't closed yet so i can't assign you anything new yet.
i shall review the PR and merge soon (hopefully today)
