### ISSUE TITLE
Add contributors to readme

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#577]

**Comment by Dharmik79** [comment]
@ayushtom I would like to work on this.

**Comment by ayushtom** [comment]
@Dharmik79 this issue is not for contributors

**Comment by martinvibes** [comment]
hello @ayushtom can i work on this issue if it is still open?

**Comment by Sravya-212** [comment]
@ayushtom Hey I would like to add the content to the readme file

**Comment by CollinsC1O** [comment]
Hello @ayushtom I will love to work on this

**Comment by suhas-sensei** [comment]
Hello @ayushtom  I would like to work on this
