### ISSUE TITLE
Improving UX for Disconnected Users on Quests Boost List

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#578]
<img width="1439" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/144677881/45c3f6b4-7eb9-4064-a216-d8b20b284ef2">

The UX on the quests boost list is problematic when the user is disconnected because we can see "see my reward," which is not possible because the user is disconnected. Therefore, remove this message by default and make it appear only when the user is connected and has completed this quest boost.

**Comment by zintarh** [comment]
@ayushtom  I would love to work on this

**Comment by addegbenga** [comment]
@ayushtom please assign this task to me

**Comment by BlackStarkGoku** [comment]
Probably too late but would love to :) @ayushtom

**Comment by ayushtom** [comment]
@kateberryd assigned to you!

@BlackStarkGoku @addegbenga i follow a first come first serve basis while assigning issues(helps with transparency) so i would suggest you to lookout for any other available issues which you can work on and comment there
