### ISSUE TITLE
Contributors Management 04/04/24-18/04/2024

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#583]
## Description 

We want to onboard more contributors this sprint. 

For this, we have all these issues that need to be merged before the end of the sprint:
- [x] https://github.com/starknet-id/starknet.quest/issues/578
- [x] https://github.com/starknet-id/starknet.quest/issues/575
- [x] https://github.com/starknet-id/starknet.quest/issues/574
- [x] https://github.com/starknet-id/starknet.quest/issues/573
- [x] https://github.com/starknet-id/starknet.quest/issues/562
- [x] https://github.com/starknet-id/starknet.quest/issues/559

For these issues let's try to make 1 contributor per issue, We'll give more issues in the future to the faster and better contributors in this list and @ayushtom will be the lead on who is the best.

**Comment by BlackStarkGoku** [comment]
Really nice, hope to be able to bring my help !

**Comment by salisshuaibu11** [comment]
@ayushtom, i am interested

**Comment by kateberryd** [comment]
@ayushtom I will like to work on this

**Comment by Oshioke-Salaki** [comment]
Im interested in this
