### ISSUE TITLE
Admin page/flow

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#587]
Loom : https://www.loom.com/share/66017aa21ddd4e3aacbf717d40632bc6

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4046%3A26500&mode=design&t=IdkeDEC9eszrblik-1

**Comment by Ayoazeez26** [comment]
@ayushtom I would love to contribute to this

**Comment by okste1234** [comment]
@ayushtom  @Kevils I would love to work on this for the admin dashboard

**Comment by bhavyagosai** [comment]
is this issue up for grabs? Looks like a good big frontend development work which I love 😍 @Kevils @ayushtom

**Comment by ayushtom** [comment]
@Ayoazeez26 @okste1234 @bhavyagosai this issue is currently not added as a contributor issue. We will be adding some soon so you can pick from those!

**Comment by okste1234** [comment]
Alright... I'll be on the look out

**Comment by abdegenius** [comment]
Can this task be assigned to me? I will love to work on this.
