### ISSUE TITLE
Bug: images do not go through CDN

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/starknet.quest#591]
@ayushtom can you take a look? Looks like this takes 80% of our bandwith on Vercel instead of using CDN.

<img width="938" alt="image" src="https://github.com/starknet-id/starknet.quest/assets/41830259/2a6c38f4-519e-4c0f-a9a2-39a056b72e5a">

**Comment by ayushtom** [comment]
yup i'll check this
