### ISSUE TITLE
Quiz on Ekubo quest

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#594]
In the Ekubo quest, the quiz redirects to the Ekubo platform, making it impossible to complete the quest.

https://www.loom.com/share/7b6fd1687f1a4689adb5120d935bf15b

**Comment by zintarh** [comment]
Hi @ayushtom please can this be assign to me

**Comment by Dprof-in-tech** [comment]
hi @ayushtom 
please assign this to me

**Comment by fricoben** [comment]
Not a bug, but the CTA should have a different naming. I changed it to `Learn more about Ekubo`
