### ISSUE TITLE
View quests to claim rewards

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#595]
Loom : https://www.loom.com/share/7c8bcf7f8e36417683e68599caecb495

Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4310%3A5471&mode=design&t=8bKmyIjFe5zHvCIr-1

technical specifications:
- using the endpoint - `/boost/get_pending_claims?addr=${addr}`
This will show all rewards which can be claimed by the user from the boosts section

**Comment by Ayoazeez26** [comment]
@ayushtom Can I pick this up?

**Comment by Kevils** [comment]
This feature is to be developed once this issue is completed : https://github.com/starknet-id/starknet.quest/issues/575

**Comment by ayushtom** [comment]
@Ayoazeez26 i would be merging the dashboard PR soon here https://github.com/starknet-id/starknet.quest/pull/599. Then should be good for assigning to you!

**Comment by Dprof-in-tech** [comment]
Hi @ayushtom 
please can this be assigned to me?

**Comment by Dprof-in-tech** [comment]
Hi @fricoben , please could i be assigned to this?

**Comment by hemantwasthere** [comment]
Hey @Kevils, Can I work on this issue?

**Comment by Ugo-X** [comment]
Hello @Kevils , the name's Ugo, please can I be assigned to this? will like to. challenge myself and get it done pretty quickly

**Comment by abdegenius** [comment]
Can this task be assigned to me? i will handle it efficiently as i have worked on a similar issue in the past before..

**Comment by Ugo-X** [comment]
Hello @Kevils , the name's Ugo, please can I be assigned to this? will like to. challenge myself and get it done pretty quickly

**Comment by Iwueseiter** [comment]
Hi @Kevils can I work on this?

**Comment by Ugo-X** [comment]
Hello @Kevils , the name's Ugo, please can I be assigned to this? will like to. challenge myself and get it done pretty quickly

**Comment by Osatuyi** [comment]
Can I have this assigned to me, please?

**Comment by jedstroke** [comment]
Yo @Kevils assign me

**Comment by ayushtom** [comment]
@Ayoazeez26 assigned to you!

**Comment by Dprof-in-tech** [comment]
hi @ayushtom , can i jump on this if its not currently being worked on
