### ISSUE TITLE
Modify the information section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#596]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4310%3A5501&mode=design&t=8bKmyIjFe5zHvCIr-1

deadline to merge this issue - 1 business day

**Comment by BlackStarkGoku** [comment]
@ayushtom, I would love to contribute :)

**Comment by Khemmie-Ray** [comment]
Hi @ayushtom I will like to work on this.

**Comment by Dprof-in-tech** [comment]
hi @ayushtom 
Please assign this to me

**Comment by ayushtom** [comment]
@BlackStarkGoku assigned to you!

**Comment by Dprof-in-tech** [comment]
@fricoben 
i just made a pull request for this, I can't seem to be able to add the ready to review label myself.
