### ISSUE TITLE
chore: add test cases and types for api service

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#602]
## Description
We always make test cases for our app but as our codebase is growing we have a services folder which isn't tested well yet.
The `services` folder has all the api endpoints in it which we call to get our data. I would like you to prepare test cases for these endpoints and handle the following test cases i mention below. Also add typings for all api responses so that we can access them on the front.
You can find sample api test in `/tests/services/apiService.test.js` for reference. 

Note-
You get assigned one endpoint at a time only.
- comment on one of the issues below which you want to pick
- avoid testing multiple endpoints without being assigned to them because there might be a chance we won't consider this as your OnlyDust reward if you try to take away other's work
## PROPOSED TODO

You need to handle the following cases
- When api returns no response
- api returns response in unexpected format
- handle undefined and null cases in the test case for all endpoints which sends some values in it
- successful response

Estimated deadline to complete this issue for each endpoint is - 2 business days

- [x] #612
- [x] #613
- [x] #603
- [x] #614
- [x] #607
- [x] #604
- [x] #615
- [x] #616
- [x] #617
- [x] #618
- [x] #605
- [x] #608
- [x] #606
- [x] #609
- [x] #619
- [x] #620
- [x] #621
- [x] #622
- [x] #623
- [x] #610
- [x] #611

**Comment by ibsule** [comment]
Can I hop on this?

**Comment by ayushtom** [comment]
@princeibs mention the endpoint you want to get started on and i'll assign it to you!

**Comment by Dprof-in-tech** [comment]
@ayushtom Hello, It's Isaac here and i would love to contribute to this.
i would want to start with the #618 , /get_quests

**Comment by addegbenga** [comment]
i will like to work on:
[ /leaderboard/get_static_info?addr=${addr}&duration=${duration}](url)

**Comment by Ayoazeez26** [comment]
@ayushtom I would like to pick up this endpoint
`/boost/get_boost?id=${id}`

**Comment by ibsule** [comment]
I would like to work on `/get_boosted_quests`

**Comment by jaipaljadeja** [comment]
hey i would like to work on `/get_trending_quests` endpoint.

**Comment by muheebyusufbaba1** [comment]
I want to work on `/get_quest_participants?quest_id=${id}`

**Comment by krshishir1** [comment]
@ayushtom i would like to work on ``` /get_quest?id=${questId} ```.

**Comment by vibenedict** [comment]
I would like to work on `/get_completed_quests?addr=${addr}`

**Comment by bhavyagosai** [comment]
I can take up `/boost/get_boosts`

**Comment by Jemiiah** [comment]
I would love to work on this : /unique_page_visit?page_id=${id}

**Comment by saimeunt** [comment]
Hey I'd like to work on `/get_quiz?id=${quizId}&addr=${address}` please!

**Comment by Xaxxoo** [comment]
Hi  will like to work on  /get_tasks?quest_id=${questId}&addr=${address} (available)

**Comment by Joy-Adah** [comment]
Hi I'd love to work on /get_deployed_time?addr=${address} (available)

**Comment by mubarak23** [comment]
Hi @ayushtom i will like to work on this  -> `/analytics/get_quest_participation?id=${id} #622` (available)

**Comment by ayushtom** [comment]
@bhavyagosai @Ayoazeez26 @muheebyusufbaba1 @jaipaljadeja @vibenedict @princeibs @Jemiiah @krshishir1 @saimeunt 
i have added your names in a bracket. Please comment on the linked issues too so i can assign you there!

**Comment by Oshioke-Salaki** [comment]
Please can i handle - /analytics/get_unique_visitors?id=${id} endpoint

**Comment by MarvyNwaokobia** [comment]
I would like to handle - /boost/get_pending_claims?addr=${addr} - endpoint

**Comment by coxmars** [comment]
Hi @ayushtom, I really would like to work on this issue: /boost/get_quests?boost_id=${id} -> number #614

**Comment by jimenezz22** [comment]
Hello @ayushtom I would like to contribuite on this issue: /analytics/get_quest_activity?id=${id} #621

**Comment by ebukizy1** [comment]
would love to work on this endpoint assign me this .. if taken you can recommend one for me-id/starknet.quest/issues/ #623
