### ISSUE TITLE
test: `/boost/get_boosts`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#603]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by bhavyagosai** [comment]
you can assign it to me here!

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@bhavyagosai  how are you doing on this?

**Comment by bhavyagosai** [comment]
finalizing this by tonight! Sorry for the delay got preoccupied in something 😬
