### ISSUE TITLE
test: `/get_quest_participants?quest_id=${id}` 

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#604]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by muheebyusufbaba1** [comment]
Please kindly assign to me. Thanks

**Comment by ayushtom** [comment]
Assigned

**Comment by ayushtom** [comment]
@muheebyusufbaba1  how are you doing on this?

**Comment by muheebyusufbaba1** [comment]
Creating a PR for this before the end of today
