### ISSUE TITLE
test: `/get_trending_quests` 

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#605]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by jaipaljadeja** [comment]
hey, you can assign me this.

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@jaipaljadeja  how are you doing on this?

**Comment by jaipaljadeja** [comment]
> @jaipaljadeja how are you doing on this?

hey, sorry i was bit occupied with something else. i will wrap this up by tonight : )
