### ISSUE TITLE
test: `/boost/get_boost?id=${id}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#607]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by Ugo-X** [comment]
hello @ayushtom please can i be assigned to this?

**Comment by Ayoazeez26** [comment]
I would love to work on this also!

**Comment by ayushtom** [comment]
@Ayoazeez26 assigning to you because i assigned to you first according to the issue title
