### ISSUE TITLE
test: `/get_completed_quests?addr=${addr}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#608]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by vibenedict** [comment]
I indicated interest for this issue in the main thread. Can you assign to me please?

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@vibenedict  how are you doing on this?

**Comment by vibenedict** [comment]
Creating a PR right away
