### ISSUE TITLE
test: `/get_quiz?id=${quizId}&addr=${address}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#609]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by saimeunt** [comment]
@ayushtom Please assign to me! :)

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@saimeunt  how are you doing on this?

**Comment by saimeunt** [comment]
@ayushtom PR ready to review! 💪
