### ISSUE TITLE
test: `/get_quest?id=${questId}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#610]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by Ugo-X** [comment]
hello @ayushtom please can i be assigned to this?

**Comment by krshishir1** [comment]
@ayushtom please assign this to me.

**Comment by Ugo-X** [comment]
@ayushtom i already finished up the other task and sent a PR, please can i handle this one too? will get it done swiftly and efficiently

**Comment by Iwueseiter** [comment]
@ayushtom please can I work on this?

**Comment by Ugo-X** [comment]
@ayushtom Hello it's Ugo again, I already completed the other task and sent a PR, please can I get assigned to this? will equally handle it quickly and efficiently

**Comment by Ugo-X** [comment]
@ayushtom i already finished up the other task and sent a PR, please can i handle this one too? will get it done swiftly and efficiently

**Comment by ayushtom** [comment]
@krshishir1 assigned!

**Comment by ayushtom** [comment]
@krshishir1 how are you doing on this?

**Comment by krshishir1** [comment]
@ayushtom I am currently working on this.
