### ISSUE TITLE
test: `/boost/get_quests?boost_id=${id}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#614]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by Calebux** [comment]
Hi @ayushtom I'm interested in taking this up

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@Calebux  how are you doing on this?

**Comment by lindsaymb15** [comment]
Hi! I'm interested in taking this task @ayushtom

**Comment by ayushtom** [comment]
Assigned!

**Comment by lindsaymoralesb** [comment]
Please re-assign to this user, my bad!

**Comment by lindsaymb15** [comment]
Please re-assign to @lindsaymoralesb ! @ayushtom

**Comment by ayushtom** [comment]
done!

**Comment by lindsaymoralesb** [comment]
PR ready to review! @ayushtom
