### ISSUE TITLE
test: `/boost/get_pending_claims?addr=${addr}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#616]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by MarvyNwaokobia** [comment]
I would love to be assigned this

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
@MarvyNwaokobia  how are you doing on this?

**Comment by Naomi-Gift** [comment]
Hey please can I have this

**Comment by ayushtom** [comment]
Assigned!
