### ISSUE TITLE
test: `/boost/get_completed_boosts?addr=${addr}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#617]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by mubarak23** [comment]
@ayushtom please kindly assign this issue to me, i will like to work on it

**Comment by ayushtom** [comment]
Assigned!

**Comment by ayushtom** [comment]
https://github.com/starknet-id/starknet.quest/pull/661

can be used as reference

**Comment by leevigh** [comment]
I'd love to pick this up

**Comment by lindsaymoralesb** [comment]
I would like to work on this! @ayushtom

**Comment by Ugo-X** [comment]
can i work on this?

**Comment by Ugo-X** [comment]
will get it done quickly

**Comment by ayushtom** [comment]
@leevigh assigned to you!

**Comment by ayushtom** [comment]
@leevigh i think the linked pr here 
https://github.com/starknet-id/starknet.quest/issues/617#issuecomment-2088647095
should help you resolve this faster.
Just try to cherry pick the original commits from the previous contributor and fix the build issue which they faced

**Comment by leevigh** [comment]
> @leevigh i think the linked pr here 
> 
> https://github.com/starknet-id/starknet.quest/issues/617#issuecomment-2088647095
> 
> should help you resolve this faster.
> 
> Just try to cherry pick the original commits from the previous contributor and fix the build issue which they faced

Okay, will do, thanks

**Comment by ayushtom** [comment]
@leevigh how are you on this?

**Comment by leevigh** [comment]
> @leevigh how are you on this?

I'm not getting the build failure yet so I'm trying to reproduce the error first

**Comment by ayushtom** [comment]
you can do so by running `npm run build`
also can you raise the PR so i can review it once. We plan to merge this by tomorrow before OD hack is over

**Comment by leevigh** [comment]
> you can do so by running `npm run build`
> 
> also can you raise the PR so i can review it once. We plan to merge this by tomorrow before OD hack is over

Yes I did run `npm run build` but it was successful. However, I tried to pull from the branch of the other author but it seems like the branch isn't there

**Comment by leevigh** [comment]
Should I rewrite the tests for this service?
