### ISSUE TITLE
test: `/get_quests`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#618]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by Dprof-in-tech** [comment]
hi @ayushtom  i indicated an interest in working on this endpoint in the #602 issue. Please can I get assigned to it?

**Comment by 0xOlivanode** [comment]
I can work on this if its not yet assigned to anyone

**Comment by Ugo-X** [comment]
@ayushtom i already finished up the other task and sent a PR, please can i handle this one too? will get it done swiftly and efficiently

**Comment by Iwueseiter** [comment]
@ayushtom please can I work on this?

**Comment by Ugo-X** [comment]
@ayushtom Hello it's Ugo again, I already completed the other task and sent a PR, please can I get assigned to this? will equally handle it quickly and efficiently

**Comment by Ugo-X** [comment]
@ayushtom Hello it's Ugo again, I already completed the other task and sent a PR, please can I get assigned to this? will equally handle it quickly and efficiently

**Comment by ayushtom** [comment]
@Iwueseiter assigned to you!

**Comment by Dprof-in-tech** [comment]
hi @ayushtom , i would love to work on this if its not currently being worked on. Thank you
