### ISSUE TITLE
test: `/get_tasks?quest_id=${questId}&addr=${address}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#619]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by leevigh** [comment]
I'll love to work on this

**Comment by Ugo-X** [comment]
hello @ayushtom please can i be assigned to this?

**Comment by ayushtom** [comment]
@leevigh assigned!
