### ISSUE TITLE
test: `/analytics/get_quest_activity?id=${id}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#621]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by EjembiEmmanuel** [comment]
@ayushtom I'll love to work on this

**Comment by ayushtom** [comment]
@EjembiEmmanuel i think i already assigned you one issue. Lets keep this open for others to contribute too!

**Comment by ayushtom** [comment]
@EjembiEmmanuel i think i already assigned you one issue. Once we merge your assigned issue, i can assign you another one

**Comment by EjembiEmmanuel** [comment]
Alright, no worries!

**Comment by ayushtom** [comment]
@Jemiiah i believe you are also working on an issue so once you are finished with it then i can assign you another one

**Comment by No-bodyq** [comment]
Can I be assigned to this @ayushtom

**Comment by Ugo-X** [comment]
hello @ayushtom please can i be assigned to this?

**Comment by ayushtom** [comment]
@No-bodyq assigned!
