### ISSUE TITLE
test: `/analytics/get_quest_participation?id=${id}`

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#622]
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

**Comment by EjembiEmmanuel** [comment]
@ayushtom I'd be happy to work on this

**Comment by ayushtom** [comment]
Assigned!

**Comment by mubarak23** [comment]
i request to be assign this from the initial Issue, why was there a change in the flow @ayushtom

**Comment by EjembiEmmanuel** [comment]
Great!

**Comment by kenkomu** [comment]
Can I work on this @ayushtom?
