### ISSUE TITLE
State of the button keeps loading

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#668]
<img width="366" alt="Capture d’écran 2024-05-03 à 11 55 03" src="https://github.com/starknet-id/starknet.quest/assets/78437165/4f35f1da-8adc-4533-b595-15e7333991ea">

The button never stops. I minted the last hasstack quest and left the website before the tx passed (I think this created this state)

**Comment by Benjtalkshow** [comment]
hello @fricoben can i work on this as my first issue?
