### ISSUE TITLE
Quizz answer height bug

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#670]
## Description

When there are two possible answers only (and not 4) during a quiz question. The height becomes very large which doesn't make sense we can keep it the normal height (use the same height we have when there are 4 possible answers to the question).

<img width="1181" alt="Capture d’écran 2024-05-03 à 13 34 37" src="https://github.com/starknet-id/starknet.quest/assets/78437165/e4c374c0-43c2-48ec-b4d7-b7f857e2b729">

**Comment by addegbenga** [comment]
Can i work on this

**Comment by raizo07** [comment]
Hello @fricoben I'll like to work on this

**Comment by Jheweed** [comment]
Can I work on this ?

**Comment by ayushtom** [comment]
@Jheweed assigned to you!

**Comment by Jheweed** [comment]
@ayushtom how do I test this without having a starknet domain?
![image](https://github.com/starknet-id/starknet.quest/assets/168746172/cf15e26a-2a30-4dad-ac57-df272a9a35f9)

**Comment by Dprof-in-tech** [comment]
hi @fricoben , would love to work on this if its not already been handled
