### ISSUE TITLE
1 - Add "new quest" button ( Create new quest on admin V2)

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#673]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7476&mode=design&t=P3UHNuHmvh1bmw3G-1

Here is the default admin page. We have added a "new quest" button that allows the admin to create their own quests.

**Comment by raizo07** [comment]
@ayushtom Kindly assign this to me

**Comment by Pycomet** [comment]
Please add me to this @ayushtom @Kevils, I would love to work on this small feature. All other features already have lots of people showing interests
