### ISSUE TITLE
2 - First step (Create new quest on admin V2)

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#674]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7477&mode=design&t=P3UHNuHmvh1bmw3G-1

Loom : https://www.loom.com/share/b3757d1bf4294caea735d9b5fce3b18d

**Comment by leevigh** [comment]
Could I be assign to this

**Comment by abdulqaharu** [comment]
Would like to work on this @Kevils @ayushtom

**Comment by Dprof-in-tech** [comment]
Hi @Kevils please may I work on this
