### ISSUE TITLE
3 - Second step (Create new quest on admin V2)

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#675]
Figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7478&mode=design&t=P3UHNuHmvh1bmw3G-1

Loom : https://www.loom.com/share/1062afb0b1b540d582732e618bee5574

**Comment by bhavyagosai** [comment]
hi

**Comment by Ugo-X** [comment]
can i take this?

**Comment by addegbenga** [comment]
I will like to work on this.
