### ISSUE TITLE
4 - Third step (Create new quest on admin V2)

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#676]
Figma : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7479&mode=design&t=P3UHNuHmvh1bmw3G-1

Loom : https://www.loom.com/share/f86a6a8b84aa4895a78701de324577c3

**Comment by abdulqaharu** [comment]
@ayushtom I would like to work on this

**Comment by bhavyagosai** [comment]
hi @ayushtom , I can take this one up
