### ISSUE TITLE
5 - Fourth step & quest published (Create new quest on admin V2)

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#677]
Fourth step : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7480&mode=design&t=P3UHNuHmvh1bmw3G-1

Quest published : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7481&mode=design&t=P3UHNuHmvh1bmw3G-1

Loom : https://www.loom.com/share/5130b2fffdd04029893f0ee2f1567ffe

**Comment by Ugo-X** [comment]
Please can i take this?
can get it done efficiently. thank you

**Comment by addegbenga** [comment]
I will like to work on this.
