### ISSUE TITLE
Admin V2

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#678]
All figma file : https://www.figma.com/file/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?type=design&node-id=4766%3A7597&mode=design&t=P3UHNuHmvh1bmw3G-1

Divided by 5 issues : 
1 - Add "new quest" button : https://github.com/starknet-id/starknet.quest/issues/673
2 - First step : https://github.com/starknet-id/starknet.quest/issues/674
3 - Second step : https://github.com/starknet-id/starknet.quest/issues/675
4 - Third step : https://github.com/starknet-id/starknet.quest/issues/676
5 - Fourth step & quest published : https://github.com/starknet-id/starknet.quest/issues/677

**Comment by abdulqaharu** [comment]
Can I work on this?

**Comment by Dprof-in-tech** [comment]
Hi @ayushtom could I be assigned to this

**Comment by Pycomet** [comment]
Hey @abdulqaharu, please can I get task? Starting with #673 ofcourse

**Comment by rahulsingh3526** [comment]
Hey can you add me to this task ?

**Comment by Kevils** [comment]
New figma file : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5367-7215&t=UBcCpKoBWwcwFQBK-1

Admin V3

**Comment by Ayoazeez26** [comment]
@Kevils is this up for grabs?
