### ISSUE TITLE
On hold transaction in quest page 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#683]
https://www.loom.com/share/2d50e18129da48abbd7ed8949040efdb?sid=9e442b09-b529-4245-8719-efa16989a4ce

**Comment by kateberryd** [comment]
Hi can I work on this

**Comment by revengexd** [comment]
@kateberryd please wait if this will be changed to open contribution you will be assigned for it
 @ayushtom

**Comment by Georghino02** [comment]
can I be assigned this issue

**Comment by fricoben** [comment]
Have it also
