### ISSUE TITLE
Nimbora deposit quest task redirects to Haiko deposit ! 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#688]
https://starknet.quest/quest/22

Nimbora quest deposit task is directing to Hiako deposit 
and discord verification is also getting verified 

https://github.com/starknet-id/starknet.quest/assets/55296770/674c1c6f-8d18-4281-8613-dd0ff2a73b56

![image](https://github.com/starknet-id/starknet.quest/assets/55296770/4614d842-5691-4df7-b369-f13c9ac62561)

**Comment by Ayoazeez26** [comment]
Can I pick this up if it is a frontend bug?

**Comment by rahulsingh3526** [comment]
Hey can I get assigned to this task ?

**Comment by revengexd** [comment]
@Ayoazeez26 please wait , if this issue is open for contribution then @ayushtom will assign you for this bug

**Comment by martinvibes** [comment]
hey please kindly assign me to this please

**Comment by ayushtom** [comment]
this bug is a backend bug so i am closing it here
