### ISSUE TITLE
Onboard new contributors through Odhack

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#691]
## Description

For the new OD hack starting on 23 of May, we would like to create issues for contributors and build a design system. 

Here are the needed tasks to make it a success (@ayushtom will be responsible for the success of all of them). 

- [ ] Create a coherent list of issues that will end with a V1 of a design system (around 10 issues)
- [ ] Assign and review all issues prioritizing new contributors 

I'll add all issues created here as a TODO to close this issue and we'll assess the Hack success on the 30 of May.

**Comment by vibenedict** [comment]
Hi, can i jump on this issue
