### ISSUE TITLE
Building Component Library 

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#693]
**These are part of OD Hack and will be assigned from the 23rd of May 2024 when the hack starts! All the best!🚀**

We would like to build generalised components which we can use throughout the code. If you have used something like material ui then you know how the components provided by them are re-useable in all aspects.I would like you to build something similar for our repo and also drop these replacements throughout the codebase if neccessary. 

This also means that these components will be highly opinionated for our app, responsive for all screen sizes out of the box and also flexible enough to use it in a way which looks good and also makes sense.

Example of how you build a button component which is flexible but also useful in all scenarios - 
1) First we plan what does this component do and in what scenarios using this component will be useful. In our case this button would be useful to navigate to other pages and also usually the main component which the user will interact with.
2) Once we know how the component will be used we know can estimate basic scenarios which will need to be supported out of the box. A few things like in built loaders to handle functions which have a wait time to show the button is working on the changes triggered by user, disabled state to prevent user click without performing certain action, text can be provided as children of the button and will be capitalised by default by the button, Different color variants so can be used in different screens with different colors.
3) Button to be responsive without having fixed width and flexible with every screen size.
4) Can also have multiple color variants in the form of primary and secondary button similar to what we have in material ui.
4) Now that we have the requirements we can plan the props of the component as follows-

```
- loading?:boolean // this will check and display a spinning loader inside the button if the component needs to handle a loading state of a function
- onClick:()=>void // this will take in a function which will be called on button click of the user
- disabled?:boolean // this will handle disabling click functions and gray out the button to display disabled state
- children // any html code given as children of this button will be rendered inside the button at the center
```

The final component will look something like this which is close to what we implement in code - 

```
import React, { FunctionComponent, ReactNode } from "react";
import styles from "@styles/components/button.module.css";
import { CircularProgress } from "@mui/material";

type ButtonProps = {
  onClick: () => void;
  children: string | ReactNode;
  disabled?: boolean;
  color?: string;
  loading?: boolean;
};

const Button: FunctionComponent<ButtonProps> = ({
  children,
  onClick,
  disabled = false,
  color = "primary",
  loading = false,
}) => {
  return (
    <button
      disabled={disabled}
      onClick={onClick}
      className={
        styles["nq-button"] +
        " " +
        (color === "primary" ? "" : styles["nq-button-secondary"]) +
        " " +
        (disabled ? styles.disabled_button : "")
      }
    >
      {loading ? <CircularProgress size={20} /> : children}
    </button>
  );
};

export default Button;
```

- Now similarly we will be making these components with a good developer ux and following the above points as first principles. Also replace in all places your new component so we can check it in different scenarios while review. Some have figma links and some you will have to go through code to undertstand how to implement it!

Adding the issues below which will be picked under this category. 

Note -  each indivisual will be assigned only one issue at a time so please avoid commenting on multiple issues if you've been assigned on one.

- [x] #694
figma link - https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/🚀-Starknet-Quest?node-id=511-132&t=q4P6gaqq1RIMd7qE-11

required props -  
- children (this handles the value inside our customised `p` tag.
- color props which takes in all the possible colors which we use in the app for texts
- use the correct letter-spacing, line-height, font-weight, font-size and correct font-family for each variant

- [x] #695
https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/🚀-Starknet-Quest?node-id=1713-11155&t=q4P6gaqq1RIMd7qE-11

- [x] #698
These boxes which have the upper stroke are used throughout the app. I would like you to make this as a generalised container inside which we can provide the children elements so it can handle any type of layout. Some examples of how it is used below - 

<img width="980" alt="Screenshot 2024-05-22 at 9 55 02 PM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/1cfc7f81-695a-46f4-a94a-1947e6fce230">

<img width="549" alt="Screenshot 2024-05-22 at 9 59 27 PM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/f7bdffe2-6ed8-4202-ab96-03c1c8011569">

<img width="293" alt="Screenshot 2024-05-22 at 10 00 35 PM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/6d2b6704-e466-4811-a759-e1fe09028c33">

- [x] #696
<img width="191" alt="Screenshot 2024-05-22 at 10 02 16 PM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/9428efa4-2b13-4377-acff-8f374babf3c5">
<img width="297" alt="Screenshot 2024-05-22 at 10 03 48 PM" src="https://github.com/starknet-id/starknet.quest/assets/41674634/e6b2879f-49cd-4826-9ed3-1722ba8b7762">

- [x] #697
figma link - https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/🚀-Starknet-Quest?node-id=1713-9826&t=q4P6gaqq1RIMd7qE-11

**Comment by BlackStarkGoku** [comment]
I would like to contribute

**Comment by Ugo-X** [comment]
Hello good evening @ayushtom my name is Ugonna  I am a full-stack developer. I have worked on quite some projects before now, including previous OD hacks. You can check my profile to see my contributions.

I would tackle this issue by using the above provided method to build a reusable component library using react and javascript packages. The members of this library would be reusable in the global state with any custom content or message as required

Please can I be assigned this issue?

**Comment by krshishir1** [comment]
Hi @ayushtom, I would like to work on Typography component. I will finish the task by 25 May. Thanks!

**Comment by manlikeHB** [comment]
Hi @ayushtom, I would love to work on the dropdown component.

**Comment by jedstroke** [comment]
Yo @ayushom, I wanna get my hands dirty
