### ISSUE TITLE
Feedback Notification component

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#695]
refer https://github.com/starknet-id/starknet.quest/issues/693

**Comment by zintarh** [comment]
I would like to work on this

I would use toast notifications. They offer concise, non-intrusive feedback, automatically vanish after a brief display, and require no user interaction (which can also be customised). Implementing them is straightforward using libraries like react-toastify. 🚀😊

I would address this issue by creating a reusable component that receives the props below

**Success Props:**

- title: The notification title - default value should be `Success`.

-  message: A brief message to display.

-  duration: Sets the default display duration, with the option to override it for longer-lasting feedback.

**Error Props**

- message: I will get this from the response object returned  by the api containing the error message or messages  

- title: also gotten from the response object if any was sent by the backend else `Error as default`

- duration: Sets the default display duration, with the option to override it for longer-lasting feedback.

**Comment by martinvibes** [comment]
let me hop on this @ayushtom

**Comment by Calebux** [comment]
@ayushtom I can take this up and bring it to live

**Comment by Dprof-in-tech** [comment]
Hello @ayushtom, I would love to work on this issue.
I will tackle this issue by using the React toastify library to build a custom notification component for starknet quest and make it available on the global state so that it's reusable anywhere in the code, with any notification message or content. Will be awaiting your response.

**Comment by ayushtom** [comment]
Hey i think the mui library provides a component called snackbar to handle this so adding a new library won't be needed. We already mui components in some places in our codebase. You guys can look into the `Snackbar` component under mui library and let me know if it is something you can work with

**Comment by Dprof-in-tech** [comment]
> Hey i think the mui library provides a component called snackbar to handle this so adding a new library won't be needed. We already mui components in some places in our codebase. You guys can look into the `Snackbar` component under mui library and let me know if it is something you can work with

Just did chief and mui library is something I have worked with before now 

So I'll definitely be able to do this using the snack bar component  and react usestate

**Comment by zintarh** [comment]
@ayushtom Yes I can work with Snackbar from MUI. I'm very familiar with mui library

**Comment by ayushtom** [comment]
@Dprof-in-tech assigning to you!

@kateberryd your approach is also correct but i think @Dprof-in-tech didnt get more chances to contribute so i would be assigning them this one
