### ISSUE TITLE
Tag Component

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#696]
refer https://github.com/starknet-id/starknet.quest/issues/693

**Comment by Jemiiah** [comment]
Hjk

**Comment by coxmars** [comment]
Hi, @ayushtom I would like to help with this one if it hasn't been assigned yet, I already have experience with this tech stack so this could be interesting. Here’s my plan:

- Analyze the design and existing usage of tags in the app.
- Build a reusable and responsive Tag component with props for label, color, onClick etc if needed
- Test thoroughly and replace all current tag implementations with the new component.

Thanks

**Comment by Jemiiah** [comment]
@ayushtom I’m ready to start with the work may I🚀

**Comment by saimeunt** [comment]
Hi @ayushtom, I'm a returning contributor from last ODHack and would love to contribute more to StarknetQuest.

I will tacke this issue by analysing the app and find every occurence of hardcoded components that fit the definition of usage of a "Tag" and I will carefully extract the best component API that could replace the existing tags (icon, icon placement, label, interactivity, etc.)
I will check what other component libraries have designed to come up with something easy and future-proof, eg. MaterialUI has a "Chip" component which satisfies StarknetQuest "Tag" usage and I could use its API as an inspiration.

**Comment by VictoriaAde** [comment]
I would like to work on this.
I have a good idea of how this can be built.

**Comment by ayushtom** [comment]
@coxmars 
assigning to you since it's your first one with us too!

**Comment by coxmars** [comment]
> @coxmars 
> assigning to you since it's your first one with us too!

Thank you for the opportunity. I'll keep you updated with any progress or questions I have 👍🏼
