### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#697]
refer https://github.com/starknet-id/starknet.quest/issues/693

**Comment by Iwueseiter** [comment]
hi @ayushtom can I work on this?
using react, I would build a dropdown component that is highly responsive, dogmatic, and suitable for the application . I would make sure to identify how it would be used in the application . I would ensure the component is flexible for users to interact with. I would also ensure the build has a beautiful ui.
and would follow the requirements as specified in #693

**Comment by jimenezz22** [comment]
@ayushtom Could you assign this issue to me? I have experience in frontend in React, below I leave you my plan to solve the problem: 
1- Identify all use cases for the dropdown
2- Create a responsive dropdown with features you say before in issue #693 like loading states, disabled options, etc. 
3- Replace existing drop-down menus throughout the code base with the new component, ensuring consistency and maintainability in the future
Than you!

**Comment by martinvibes** [comment]
i would like to do this task @ayushtom ?

**Comment by VictoriaAde** [comment]
I would like to work on this.
I will build a dropdown component that can be used anywhere it's needed.

**Comment by fmmesen** [comment]
Hello @ayushtom I'm coming from ODHack.
Could you assign this to me, please?

**Comment by ayushtom** [comment]
@jimenezz22 since it's also your first issue and your approach is looking good to me.
Assigning you!

**Comment by jimenezz22** [comment]
@ayushtom Thank you very much!! I'm going to clone the repo to my local machine and start solving the issue. I'll keep you updated on my progress through Telegram
