### ISSUE TITLE
Accent Box Container Component

### ISSUE THREAD

**Issue by ayushtom** [starknet-id/starknet.quest#698]
refer https://github.com/starknet-id/starknet.quest/issues/693

**Comment by ooochoche** [comment]
@ayushtom let me hop on this

**Comment by Ayoazeez26** [comment]
Can I work on this @ayushtom

**Comment by od-hunter** [comment]
Hello @ayushtom  Can i work on this please? I promise to give in my best.

**Comment by juandiegocv27** [comment]
Hi, @ayushtom, 
I would love to contribute to this task #698 referring to #693: starting on May 23, 2024, to Completion Date: June 1, 2024. I'm Juan Diego Carballo, and I'm a full-stack developer with a software engineering degree. I have already contributed to other projects and am currently creating an on-chain game. I have experience with Cairo and blockchain development, including implementing and optimizing encoding algorithms. I have already joined the Telegram. 

To complete this issue, I will:
1. Review the Figma design linked in the issue to understand the visual requirements.
2. Define the necessary props for the component, ensuring flexibility and reusability.
3. Implement the Accent Box Container component with the required styles and functionality.
4. Test the component across different screen sizes to ensure responsiveness.
5. Replace existing instances in the codebase with the new component to verify its integration.

assign it to me

**Comment by Dprof-in-tech** [comment]
Hello @ayushtom i am Isaac a javascript developer and i would love to be assigned to this task.

I would solve this by creating a generalized dynamic component as specified in the brief and figma design file, style it to have the accent colors as needed and make sure it takes the required text as props to the component so that we can get that accent box container component as needed.

I will be awaiting your reply.
Thank you

**Comment by VictoriaAde** [comment]
I would like to work on this.
I have a good experience working on components and I have a good idea of how to go about this.

**Comment by ayushtom** [comment]
@juandiegocv27 
assigning to you since it's your first issue with us too!

**Comment by juandiegocv27** [comment]
@ayushtom thank you very much for this opportunity
