### ISSUE TITLE
Typo description

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#702]
<img width="808" alt="Capture d’écran 2024-05-24 à 10 08 39" src="https://github.com/starknet-id/starknet.quest/assets/78437165/957f1935-0d1b-4adf-9d50-588ff3490e8f">

Starknet Quest **helpS**

**Comment by jaipaljadeja** [comment]
i can take this

**Comment by Ayoazeez26** [comment]
I would like to work on this

**Comment by muheebyusufbaba1** [comment]
I'll like to work on this

**Comment by No-bodyq** [comment]
Hey @fricoben can I get assigned to this

**Comment by od-hunter** [comment]
Hi @fricoben can I be assigned this? I’m new to Starknet ecosystem and I’ll love to proof my skills, thank you

**Comment by Signor1** [comment]
Hi @fricoben, I would like to contribute. Can I be assigned this?

**Comment by od-hunter** [comment]
Hi @fricoben I'm waiting for go ahead to start work.

**Comment by Ugo-X** [comment]
Good afternoon @fricoben My name is Ugo and I am a fullstack dev. i would like to contribute, can i be assigned this?

**Comment by manlikeHB** [comment]
Hi @fricoben, I would like to take this task.

**Comment by od-hunter** [comment]
Hello @fricoben I'm waiting to be assigned by you

**Comment by mystical-prog** [comment]
@fricoben waiting for you to assign me this, have already made the changes
