### ISSUE TITLE
Quest proposal after confirmation

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#714]
<img width="705" alt="Capture d’écran 2024-05-31 à 16 18 17" src="https://github.com/starknet-id/starknet.quest/assets/78437165/dc6d77cf-1a95-437e-9585-bbd75462f945">

It just proposed me the Bountive quest after finishing the bountive quest :/

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by kenkomu** [comment]
Hello my name is Kenneth Komu. I am a Starknet developer and I would like to work on the issue.

**Comment by mystical-prog** [comment]
I am currently working on this issue, please assign this to me

**Comment by mystical-prog** [comment]
@ayushtom Please look into the PR, the issue has been resolved, let me know if there are changes to be made
