### ISSUE TITLE
Feedback on collections section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#720]
https://www.loom.com/share/be52667b4de04b12aa0d0cc3d06ddc8e

1. When I'm on a collection, the back button should take me back to the collection, not the main quests.

2. In the collection section, we need to hide quests that are no longer available. Only show active quests. 

3. The images for some collections are not working.

**Comment by Ayoazeez26** [comment]
Can I pick this up?

**Comment by fricoben** [comment]
Created three separated issues for this
