### ISSUE TITLE
Onboarding flow for dashboard on SQ

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#721]
Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5408-11294&t=siYIjELkI3CzUjfH-1

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by NueloSE** [comment]
@fricoben can I work

**Comment by petersdt** [comment]
@Kevils  can i work on this.

**Comment by petersdt** [comment]
@Kevils 
Can be assigned this issue?

**Comment by PedroCo3lho** [comment]
Hello @fricoben is this issue open for contribution? I'm interested to work in this issue

**Comment by Benjtalkshow** [comment]
@Kevils,

Can you assign this task to me? It will be my first task on Starknet.quest. I have been contributing to other OnlyDust projects. I am Benjamin, deeply rooted in TypeScript, Next.js, Tailwind CSS, and Redux, and I know how to seamlessly fetch data from APIs without delays. I have 3 years of experience and a track record of contributing to OnlyDust projects, with expertise in professional and responsive frontend designs. I will deliver an excellent job.

**Comment by Ayoazeez26** [comment]
@fricoben is this still open for contribution?

**Comment by od-hunter** [comment]
@Kevils , @fricoben please kindly assign me to work on this.
