### ISSUE TITLE
Empty 'To Claim' Quest View section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#722]
Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5409-29116&t=siYIjELkI3CzUjfH-1

**Comment by addegbenga** [comment]
Can i work on this

**Comment by Ugo-X** [comment]
Hello good afternoon @ayushtom , please can i be assigned this issue?

**Comment by estherbreath** [comment]
I would like to work on this please

**Comment by AYo101o** [comment]
hi, @Kevils @estherbreath  please can i be assigned to this issue?
