### ISSUE TITLE
Discover page 

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#724]
Loom : https://www.loom.com/share/f8fed2d9461043608869e7b56b0bc06b

Figma file : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5448-5136&t=7G045GpFt0Wt8yqV-1

Ressources : 
- Component: https://ui.shadcn.com/examples/tasks
- Notion: https://www.notion.so/lfg-labs/Discover-SQ-Page-3faf27010c004466a7529b92a5f4b401

**Comment by Ayoazeez26** [comment]
Can I work on this

**Comment by Ugo-X** [comment]
Hello good afternoon @ayushtom , please can i be assigned this issue?

**Comment by fricoben** [comment]
> Hello good afternoon @ayushtom , please can i be assigned this issue?

This issue is for @ayushtom himself :)
