### ISSUE TITLE
Padding disappeared

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#733]
<img width="287" alt="Capture d’écran 2024-06-19 à 21 14 48" src="https://github.com/starknet-id/starknet.quest/assets/78437165/0d08290f-e82d-4ed9-80ed-9f79a5ad529a">

**Comment by od-hunter** [comment]
Can I be assigned this please?

**Comment by raizo07** [comment]
@ayushtom I'll like to work on this

**Comment by estherbreath** [comment]
@ayushtom I am a smart contract developer in Solidity and Cairo, with frontend knowledge. 
Can I work on this please?
