### ISSUE TITLE
Margin bug

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#736]
<img width="227" alt="Capture d’écran 2024-06-20 à 14 20 06" src="https://github.com/starknet-id/starknet.quest/assets/78437165/b42cb5c5-986b-4e74-8124-b399a1a8fef0">

**Comment by raizo07** [comment]
Hey @ayushtom @fricoben I'll like to work on this

**Comment by ktarun1419** [comment]
Hi @ayushtom  
I'll like to work on this
