### ISSUE TITLE
Issue in claiming SITHSWAP raffle rewards

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#740]
Users who have won the raffle are unable to claim the rewards 
![image](https://github.com/starknet-id/starknet.quest/assets/55296770/40fb245d-7cfe-4e98-bb4e-40201efc47c9)

**Error code**

RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x423b456b79554552386fabf258476f57970b5c4a3e1111ecccfb207360b5022",
      "calldata": [
        "0x1",
        "0x70879acc1b0586803e740b5f1942e1f0574b85b5395077105c537ef04e27ac",
        "0xb758361d5e84380ef1e632f89d8e76a8677dbc3f4b93a4f9d75d2a6048f312",
        "0x7",
        "0x5150ae84a8cdf00000",
        "0x0",
        "0x6fedc8e5246e38e06c08c2e784e6a46eb2ae69433be04fe911f5726cb96b67e",
        "0xd",
        "0x2",
        "0x35e5dedf053b8beba4be27095d59cd00886e8f611fea11db05b52dbf7986e6b",
        "0x418779fa2a90e74a4cef4bd1b13ee192ee283484be0012fbe5cc0a65e0ffc1d"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [
        "0x1",
        "0x0",
        "0x0"
      ],
      "nonce": "0x6b",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": []
}
 
        41: Transaction execution error: {"transaction_index":0,"execution_error":"reverted: Error in the called contract (0x0423b456b79554552386fabf258476f57970b5c4a3e1111ecccfb207360b5022):\nError at pc=0:20259:\nGot an exception while executing a hint: Execution failed. Failure reason: 0x616d6f756e74206d6f7265207468616e2062616c616e6365 ('amount more than balance').\nCairo traceback (most recent call last):\nUnknown location (pc=0:309)\nUnknown location (pc=0:5819)\nUnknown location (pc=0:11008)\n\nError in the called contract (0x0070879acc1b0586803e740b5f1942e1f0574b85b5395077105c537ef04e27ac):\nExecution failed. Failure reason: 0x616d6f756e74206d6f7265207468616e2062616c616e6365 ('amount more than balance').\n"}
        
        
        
        
Discord tickets :
https://discord.com/channels/1154728104112177262/1256710069651902544
https://discord.com/channels/1154728104112177262/1257027940672082061

**Comment by Marchand-Nicolas** [comment]
Fixed by Thomas
