### ISSUE TITLE
Admin Optimizations

### ISSUE THREAD

**Issue by sdaav** [starknet-id/starknet.quest#758]
## Description
We can optimize a few things on backend and frontend sides to create a quest.

## PROPOSED TODO

- [ ] Custom checking balance parameters (currently 0.003ETH)
- [ ] Simplify task modifications: when I'm clicking on "save all tasks" just for modification (like the tweet to RT), that create all quests in double
- [ ] Ensure image displaying (NFT and favicon)
- [ ] Quiz not displayed into the database
- [ ] After clicking on "Go to quest", be able to open a new window to facilitate admin modification

<img width="755" alt="Capture d’écran 2024-07-19 à 19 34 17" src="https://github.com/user-attachments/assets/78181277-e3df-4fe2-8122-c2b2c31ddccc">

- [ ] Put the right contract instead of the name for the quest boost (i.e "STRK" -> put directly contract address)

![5825930207549309146 (1)](https://github.com/user-attachments/assets/d11bf729-40b6-4d70-9d8a-b55418cf3464)

**Comment by suhas-sensei** [comment]
@sdaav i would like to work on this.

**Comment by fricoben** [comment]
@Marchand-Nicolas how are we here ?

**Comment by Marchand-Nicolas** [comment]
All done
