### ISSUE TITLE
Quizz mobile issues

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#763]
<img width="176" alt="Capture d’écran 2024-07-23 à 17 23 52" src="https://github.com/user-attachments/assets/5b7d024d-ed6b-474c-a67a-505f6a28bfc3">

Replace. Start quizz by 'quizz' for small screen

<img width="509" alt="Capture d’écran 2024-07-23 à 18 23 23" src="https://github.com/user-attachments/assets/ad21c12f-41d8-464a-8d39-97e945736111">

Quizz not feasible on mobile

**Comment by Jemiiah** [comment]
I would love to work on this issue if you don’t mind @fricoben
