### ISSUE TITLE
When I'm on a collection, the back button should take me back to the collection, not the main quests.

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#768]
https://www.loom.com/share/be52667b4de04b12aa0d0cc3d06ddc8e

When I'm on a collection, the back button should take me back to the collection, not the main quests.

**Comment by Jemiiah** [comment]
@fricoben i would love to work on this issue

**Comment by ShantelPeters** [comment]
@fricoben can I be assigned to this issue

**Comment by martinvibes** [comment]
@fricoben i would love to be assigned on this issue and be a contributor

**I am a **frontend dev**  and i have experience using** `javascript`, `typescript`, `tailwind css`, `saas`, `react`, `solidity ` etc  

**this particular issue shouldn't take time to do**

**Comment by NueloSE** [comment]
@fricoben can I be assigned this

**Comment by lindsaymoralesb** [comment]
Hi @fricoben! I would like to help with this issue

## My experience
I'm a Software Engineer based in Costa Rica. I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development, developing and maintaining projects with the most known/used FE frameworks such as React, Next, Vue, and Angular. All this experience plus some courses I've taken had helped me master both javascript and typescript languages.

## How to tackle the issue?
With my extensive experience in frontend development it would be easy to tackle this issue. What I would do is check if there is a context I can use to save the state of the current selected tab. If not, I would see if it's easier to use the localStorage or to create a context.

**Comment by Ayoazeez26** [comment]
@fricoben can I work on this?

**Comment by fricoben** [comment]
I assigned @martinvibes for it's first issue with SQ

**Comment by martinvibes** [comment]
@fricoben thank you for the opportunity

**Comment by mystical-prog** [comment]
i can work on this issue, please assign it to me @fricoben

**Comment by od-hunter** [comment]
@fricoben , Can I work on this?

**Comment by mystical-prog** [comment]
I have made the necessary changes, please check it out @fricoben

**Comment by Marchand-Nicolas** [comment]
Fixed here: https://github.com/starknet-id/starknet.quest/pull/816
