### ISSUE TITLE
Only show active quests in the collection section

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#769]
In the collection section, we need to hide quests that are no longer available. Only show active quests.

https://www.loom.com/share/be52667b4de04b12aa0d0cc3d06ddc8e

**Comment by Khemmie-Ray** [comment]
Can I work on this?

**Comment by ShantelPeters** [comment]
Can I work on this?

**Comment by ShantelPeters** [comment]
@fricoben I would love to work on this

**Comment by martinvibes** [comment]
hello @fricoben can i be assign to this issue?
i will love to be a contributor on this repo

this shouldn't take time to do

**Comment by Ayoazeez26** [comment]
Hi @fricoben can I pick this up?

**Comment by fricoben** [comment]
I assigned @Ayoazeez26
