### ISSUE TITLE
The images for some collections are not working.

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#770]
The images for some collections are not working.

https://www.loom.com/share/be52667b4de04b12aa0d0cc3d06ddc8e

**Comment by EjembiEmmanuel** [comment]
@fricoben I'd love to work on this

**Comment by ShantelPeters** [comment]
@fricoben can I be assigned to this issue ?

**Comment by MullerTheScientist** [comment]
Hello @fricoben,
I want to address this issue.

**Comment by GoSTEAN** [comment]
@fricoben Please assign this to me.

**Comment by thiagoulloa** [comment]
Hello @fricoben,
can I be assigned to this issue as my first one?
Greetings from starknet community from Brazil!

**Comment by fricoben** [comment]
I assigned @GoSTEAN for its first issue with SQ. 

Other issues will follow today @thiagoulloa @EjembiEmmanuel :)

**Comment by GoSTEAN** [comment]
@fricoben Thank you, I am working on it.
