### ISSUE TITLE
Make warnings disappear after `npm run build`

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#772]
# Issue Description

When running the command `npm run build`, several warnings are displayed in your project. These warnings are primarily related to unused variables and the usage of the `any` type in TypeScript. Let's break down each type of warning and understand how to resolve them.

## Types of Warnings

1. **Unused Variables**: These warnings indicate that certain variables are defined in your code but never used. This is often an indication of leftover code from previous implementations or mistakes.

   Example:
   ```typescript
   const error = "Some error"; // 'error' is defined but never used.
   ```

2. **Explicit `any` Type**: These warnings appear when the `any` type is used in TypeScript. While `any` can be used to bypass type-checking, it is generally discouraged as it defeats the purpose of using TypeScript, which is to have strict type-checking.

   Example:
   ```typescript
   function handleEvent(event: any) { // Unexpected any. Specify a different type.
     // some code
   }
   ```

If you don't find a different type you can add this line on top of the line where your `any` is located `// eslint-disable-next-line @typescript-eslint/no-explicit-any` . This asks the linter to forget this particular `any` type.

## Steps to Resolve Warnings

1. **Remove Unused Variables**: For variables that are defined but never used, you should either remove them or use them appropriately if they are needed.

   Example Resolution:
   ```typescript
   // Remove the unused variable
   // const error = "Some error"; // Remove this line if 'error' is not used anywhere
   ```

2. **Replace `any` with Specific Types**: Instead of using `any`, define the type that the variable or function parameter should have. This ensures better type safety and code readability.

   Example Resolution:
   ```typescript
   type Event {
     type: string;
     payload: unknown;
   }

   function handleEvent(event: Event) {
     // some code
   }
   ```

## Detailed Steps to Fix Each Warning

1. **Open Your Project in a Code Editor**

   Use an editor like Visual Studio Code (VSCode).

2. **Navigate to Each File and Line Number**

   Refer to the warnings and go to the specified file and line number in your code editor.

3. **Fix Unused Variable Warnings**

   - **app/analytics/[questId]/page.tsx**:
     ```typescript
     // Line 35: Remove 'error' if not used
     // const error = someFunction(); // Remove this line if 'error' is not used
     ```

   - Repeat similar steps for other files with unused variable warnings.

4. **Fix Explicit `any` Type Warnings**

   - **components/admin/formSteps/QuestDetailsForm.tsx**:
     ```typescript
     // Line 133: Replace 'any' with a specific type
     type QuestDetail {
       // Define the properties of QuestDetail
     }

     function someFunction(detail: QuestDetail) {
       // implementation
     }
     ```

   - Repeat similar steps for other files with explicit `any` type warnings.

## Example Fixes

Here are some example fixes for your warnings:

- **app/analytics/[questId]/page.tsx**:
  ```typescript
  // Line 35: Remove or use 'error'
  // const error = someFunction(); // Remove this line if 'error' is not used
  ```

- **components/admin/formSteps/QuestDetailsForm.tsx**:
  ```typescript
  // Line 133: Replace 'any' with a specific type
  type QuestDetail {
    // Define the properties of QuestDetail
  }

  function someFunction(detail: QuestDetail) {
    // implementation
  }
  ```

- **components/UI/navbar.tsx**:
  ```typescript
  // Line 5: Remove 'AiOutlineMenu' if not used
  // import { AiOutlineMenu } from 'react-icons/ai'; // Remove this line if 'AiOutlineMenu' is not used
  ```

## Running ESLint to Check for Warnings

After making the necessary changes, you can run ESLint to check for any remaining warnings or errors.

1. **Install ESLint (if not already installed)**
   ```bash
   npm install eslint --save-dev
   ```

2. **Run ESLint**
   ```bash
   npx eslint . --ext .js,.jsx,.ts,.tsx
   ```

This command will scan your project files and report any linting issues. Make sure that all warnings and errors are resolved.

## Conclusion

By following these steps, you should be able to resolve all the warnings when running `npm run build`. This will make your code cleaner, more maintainable, and ensure that you are leveraging the full benefits of TypeScript's type-checking. If you have any further questions or run into issues, feel free to ask for more detailed assistance.

**Comment by Jemiiah** [comment]
d

**Comment by Ayoaris** [comment]
@fricoben  I would love to work on the issue

**Comment by fricoben** [comment]
Assigned to @Jemiiah 

@Jemiiah Your account seems fake, please add a Profile pic.

**Comment by Jemiiah** [comment]
okay ser would do that
