### ISSUE TITLE
Fix partnership css and alignement for laptop and mobile

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#778]
## Description

The [partnership](https://starknet.quest/partnership) page is completely bugged for mobile and laptop. This is probably due to a problem in the CSS or the tailwind. 

Fix it on both mobile and laptop.

**Comment by Oshioke-Salaki** [comment]
Please can I pick this up?

**Comment by josephchimebuka** [comment]
Can I handle this, I am a frontend dev with proficiency in react tailwind and nextjs here's something I worked with tailwind css and nextjs metacrypt.vercel.app. This would be my first issue for this project

**Comment by Naomi-Gift** [comment]
@fricoben please let me work on this issue.

**Comment by petersdt** [comment]
@fricoben am a frontend dev and i would like to make this my first contribution to the starknet quest project

**Comment by ShantelPeters** [comment]
This is my first time contributing to this ecosystem,can I please be assigned to this issue

**Comment by fricoben** [comment]
Go for it @josephchimebuka

**Comment by josephchimebuka** [comment]
Thank you @fricoben I'll give you constant feedback ASAP!
