### ISSUE TITLE
Add the notion of boost in the choice of the featured quest

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#779]
## Description 

The featured quest is the quest shown first on the Starknet quest home page as so:

<img width="995" alt="Capture d’écran 2024-07-31 à 12 18 46" src="https://github.com/user-attachments/assets/91cdd068-333a-4d88-bc11-a5542cc0be61">

Currently, this place shows randomly non-expired quests, I want you to refactor the `QuestProvider.tsx` code here line 104 

<img width="555" alt="Capture d’écran 2024-07-31 à 12 18 07" src="https://github.com/user-attachments/assets/b9a09039-f148-4a8f-bc57-0fe6b7931d8f">

So we do not feature a random non-expired quest but the last boosted quest and if no boosted quest is available then we feature a random non-expired quest. Moreover this code 

```ts
    const notExpired = quests.filter((quest) => !quest.expired);
    const randomQuest =
      notExpired[Math.floor(Math.random() * notExpired.length)];
    setFeaturedQuest(randomQuest);
```

Is repeated two times in two different useMemos, I don't think it's necessary so you may delete one.

This is a pretty fast issue, don't hesitate to use GPT to make a clean code.

**Comment by Iwueseiter** [comment]
Please can I work on this? @fricoben 
I’d push a PR quickly.

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by ShantelPeters** [comment]
@fricoben  This is my first time contributing to this ecosystem.. can I be assigned to this issue… 
I will push a PR between 3-5 working days after Been assigned

**Comment by josephchimebuka** [comment]
Hello @fricoben Can I handle this, I am a frontend dev with proficiency in react tailwind and nextjs here's something I worked with tailwind css and nextjs metacrypt.vercel.app. This would be my first issue for this project

**Comment by Naomi-Gift** [comment]
Hi @fricoben i am a frontend developer, I can handle this issues if I am being assigned, this will be my first issue on this project

**Comment by fricoben** [comment]
assigned to @Gift-Naomi
