### ISSUE TITLE
Broken Image and Overlapping Button on Mobile Interface

### ISSUE THREAD

**Issue by MullerTheScientist** [starknet-id/starknet.quest#780]
**Describe the bug**
On the mobile version of the website, there are two issues observed:
Broken Image: A broken image icon is visible near the top of the page.
Overlapping Button: The "Start quiz" button overlaps with other elements, leading to a poor user interface experience.

**To Reproduce**

1. Go to https://starknet.quest/
2. Click on the "Begin" button
3. Scroll down to the start quiz section
4. Observe the broken image and notice the overlapping "Start quiz" button.

**Expected behavior**
All images should load properly, and no broken images should be visible.
The "Start quiz" button should be properly aligned and not overlap with any other elements on the page.

**Actual behavior**
A broken image icon is displayed 
The "Start quiz" button is overlapping

**Priority Level**
Medium - While the broken image and UI overlap do not prevent the primary functionality, they impact the user experience

**Screenshots**
![Screenshot_20240731-115822](https://github.com/user-attachments/assets/0bbe8b0f-2d91-402c-a6eb-1236caec19cb)

**Smartphone**
- Device: Samsung Galaxy A5
- OS: 7.0
- Browser - chrome
- Version 119

**Recommendation**
Please address these issues to ensure a smoother and more professional user experience on mobile devices.

**Comment by Calebux** [comment]
I want to work on this

**Comment by Gift-Naomi** [comment]
@MullerTheScientist Can i be assigned to work on this issue?
I am a frontend developer.

**Comment by NueloSE** [comment]
@MullerTheScientist can I work on this

**Comment by thiagoulloa** [comment]
Can I work on this issue as my first contribution? @MullerTheScientist

**Comment by ShantelPeters** [comment]
Can I be assigned to this issue? This would be my first time contributing to this ecosystem.. @MullerTheScientist

**Comment by fricoben** [comment]
Appreciate the effort @MullerTheScientist but this bug has been fixed already in the latest release #784

**Comment by fricoben** [comment]
Appreciate the effort @MullerTheScientist but this bug has been fixed already in the latest release #784
