### ISSUE TITLE
`questDetail.tsx` skeletons

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#787]
<img width="1440" alt="Capture d’écran 2024-08-01 à 15 06 20" src="https://github.com/user-attachments/assets/33f55834-056a-4263-8c3c-de8bb3587206">

On this skeleton here you have 3 images + issue skeletons, these 3 skeletons are not necessary we just need one so you can delete two on `questDetail.tsx`. 

Please make sure it works well on mobile and laptop before sending the PR

**Comment by od-hunter** [comment]
Can I be assigned this please? @fricoben

**Comment by addegbenga** [comment]
Can i work on this

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by Ugo-X** [comment]
@fricoben Please can i be assigned this issue? already worked on something similar

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this? I will look at the file and remove the skeleton elements not needed then save the changes and  run the code to ensure it reflects as expected.

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by fricoben** [comment]
assigned to @petersdt

**Comment by mystical-prog** [comment]
I would like to contribute this issue if the current assignee is unable to contribute

**Comment by fricoben** [comment]
Issue done
