### ISSUE TITLE
If to claim contains 0 quests, do not show the tab

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#788]
## Description

<img width="382" alt="Capture d’écran 2024-08-01 à 16 36 12" src="https://github.com/user-attachments/assets/a01b63f2-d7f7-4954-9a8c-6c60e59708ef">

The `To claim` tab is showing even if 0 quests are in it. Refactor this current code to make sure that the tab is showing only if the user is connected and has something to claim. Change this way of working on both `questAndCollectionTabs.tsx` and `addressOrDomain/page.tsx` 

<img width="228" alt="Capture d’écran 2024-08-01 à 16 37 20" src="https://github.com/user-attachments/assets/41fa558d-437e-49b1-8e9c-b7405b2daa69">

Make sure to test before sending the PR

**Comment by od-hunter** [comment]
I

**Comment by EjembiEmmanuel** [comment]
@fricoben I'd be happy to work on this

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by Ugo-X** [comment]
Please can i be assigned to this @fricoben

**Comment by Iwueseiter** [comment]
@fricoben can I work on this?

**Comment by fricoben** [comment]
assigned @Iwueseiter
