### ISSUE TITLE
Cursor issue on the `dropdown.tsx` component

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#789]
## Description

https://github.com/user-attachments/assets/f3b7f8bf-4a01-4454-8d36-0f7b8eb1ce6a

There are 2 issues here. 

- [ ] The cursor changes from the Starknet Quest custom pointer to the regular pointer when we pass on the filter
- [ ] The cursor changes from a pointer to the text cursor when passing on the down arrow.

**Comment by Ugo-X** [comment]
@fricoben  can I take this please, would resolve it quickly

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by od-hunter** [comment]
Please assign me @fricoben

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this?

**Comment by Dprof-in-tech** [comment]
Hello @fricoben , I'm Isaac a regular contributor to the starknet quest project. I would love to take up this issue and solve it as soon as possible

**Comment by martinvibes** [comment]
hi @fricoben let me hop on this an get it done asap

**Comment by fricoben** [comment]
assigned @martinvibes

**Comment by fricoben** [comment]
was done
