### ISSUE TITLE
Quizz with one question has a messed-up progress bar

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#790]
<img width="1440" alt="Capture d’écran 2024-08-01 à 16 54 03" src="https://github.com/user-attachments/assets/c9ece49f-6455-49a6-8d94-3361d07a1367">

Example of a messed-up progress bar (because there is one question only): https://starknet.quest/quest/127
Example of a not messed-up progress bar: https://starknet.quest/quest/1

Make it so we only see the number one centered like so while not breaking the other quizzes with several questions

<img width="1302" alt="Capture d’écran 2024-08-01 à 16 57 26" src="https://github.com/user-attachments/assets/158258fc-6298-4fc0-af38-69577f4bde30">

**Comment by od-hunter** [comment]
Assign me please @fricoben

**Comment by Ugo-X** [comment]
@fricoben Please can i be assigned to this? will get it done very quickly

**Comment by martinvibes** [comment]
can i work on this an get it done @fricoben

this shouldn't take time and i'll love to contribute to your repo

**Comment by Iwueseiter** [comment]
@fricoben can I work on this?

**Comment by Ayoazeez26** [comment]
Can I pick this up?

**Comment by od-hunter** [comment]
@fricoben assign me please

**Comment by mexes20** [comment]
@fricoben can I work on this?

**Comment by fricoben** [comment]
assigned @Ayoazeez26
