### ISSUE TITLE
Selecting "Back" option in collection tab redirects to quest tab !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#803]
https://www.loom.com/share/8dc6022c2e074897a769b8e93694b380?sid=ecec8a91-c818-4564-8af6-6f28df5243e7

**Comment by Iwueseiter** [comment]
Hi @revengexd can I work on this?

**Comment by Ayoazeez26** [comment]
@revengexd can I work on this?

**Comment by martinvibes** [comment]
hello @revengexd this issue has already been assigned to me #768 
 i have already created a PR

**Comment by petersdt** [comment]
@revengexd  can i work on this

**Comment by Ugo-X** [comment]
please @fricoben and @revengexd can I be assigned this issue? I have a proven track record of efficiency and speed in delivering tasks.

**Comment by martinvibes** [comment]
someone is already on this issue #768  and has created a pr @revengexd @saimeunt

**Comment by fricoben** [comment]
> someone is already on this issue #768 and has created a pr @revengexd @saimeunt

yep
