### ISSUE TITLE
Collection quest info mismatch !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#804]
https://www.loom.com/share/b53911f887c64c9c87d56932f071057f?sid=4a333fa9-5384-44e5-a560-98b8f776c0cb

**Comment by od-hunter** [comment]
Hi @revengexd Can I be assigned this?

**Comment by Ayoazeez26** [comment]
@revengexd can I work on this?

**Comment by petersdt** [comment]
@revengexd can i work on this

**Comment by Ugo-X** [comment]
please @fricoben and @revengexd can I be assigned this issue? I have a proven track record of efficiency and speed in delivering tasks.

**Comment by MullerTheScientist** [comment]
Hello @revengexd let me address this issue.

**Comment by Luluameh** [comment]
Hi  @revengexd  I can work on this

**Comment by mystical-prog** [comment]
I have made the necessary changes in my PR, please assign this to me @revengexd

**Comment by od-hunter** [comment]
Hi @revengexd , let me work on this please.
