### ISSUE TITLE
Featured quest is expired 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#808]
https://www.loom.com/share/99422dd5805c4b8585a4baf164c47ecb

**Comment by Jemiiah** [comment]
I would love to work on this issue @fricoben

**Comment by Gift-Naomi** [comment]
Hi @fricoben

**Comment by Iwueseiter** [comment]
@fricoben can I work on this?

**Comment by Ayoazeez26** [comment]
Hi @fricoben can I work on this?

**Comment by GoSTEAN** [comment]
@fricoben can i work on this issue

**Comment by petersdt** [comment]
@fricoben  can i work on this

**Comment by Luluameh** [comment]
@fricoben I can handle this task , I will love to make this my first contribution to the starknet quest project.  kindly  assign me , if available
