### ISSUE TITLE
Wrong task deleted when trying to delete a task

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#840]
When I'm trying to delete a task in https://starknet.quest/admin/quests/dashboard/128 I click on delete and the preview is not what it's supposed to be, I refresh and I see that the wrong task was deleted (the n-1 one and not the N one).

**Comment by ShantelPeters** [comment]
Hi @fricoben i will like to work on this. Kindly assign

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this?
ETA: 24hrs

**Comment by Ayoazeez26** [comment]
@fricoben can I work on this?

**Comment by martinvibes** [comment]
Hello @fricoben please can I work on this issue? :)

**Comment by fricoben** [comment]
issue already exists
