### ISSUE TITLE
Add more margin between navbar & table

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#850]
Add something like 48px between navbar & table
![image](https://github.com/user-attachments/assets/039938d8-7e46-41d4-854c-8271df0a8a42)

**Comment by Iwueseiter** [comment]
Hi @Kevils can I work on this?

**Comment by martinvibes** [comment]
hello @Kevils i would love to work on this issue 
Please kindly assign :)

**Comment by petersdt** [comment]
@Kevils can i be assigned this issue

**Comment by ShantelPeters** [comment]
@Kevils please can I be assigned to this issue ?

**Comment by Kaminar-i** [comment]
hello @Kevils i am a **frontend developer** and i would love to work on this issue 
please kindly assign :) **this would be my first time contributing to this ecosystem**

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
I will Add something like 48px between navbar & table

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @Kevils I'm a front-end and a blockchain developer and I will love to work on this

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

Hey! I'm Lau Chaves, and I would like to contribute to this issue! this would me mmy first time contributing to this proyect.


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.

Feel free to check my onlydust profile [here](https://app.onlydust.com/u/lauchaves) and github profile: lauchaves!


### How I plan on tackling this issue
Id check current navbar and table styles and add a 48px padding/margin between them

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in blockchain software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest

### How I plan on tackling this issue
My Approach includes Pull Request (PR) includes:
- Read through the codes 
- add the required margin at the required components for a better UI
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on the Review of the PR

**Comment by fricoben** [comment]
assigned to @CollinsC1O ! Others issue available https://github.com/lfglabs-dev/starknet.quest/issues/
