### ISSUE TITLE
Create a Reusable CopyAddress Component for ProfileCard and WalletButton

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#851]
## Description

We've identified duplicate code for copying wallet addresses in two components: `components/UI/profileCard/profileCard.tsx` and `components/navbar/walletButton.tsx`. To improve code maintainability and reduce duplication, we should create a reusable `CopyAddress` component.

## Current Behavior

- Both `ProfileCard` and `WalletButton` implement their own logic for copying addresses and managing the "copied" state.
- This leads to code duplication and potential inconsistencies in behavior across different parts of the application.

## Proposed Solution

Create a new `CopyAddress` component that encapsulates the address copying functionality. This component should:

1. Accept an address as a prop
2. Handle the copying logic
3. Manage the "copied" state
4. Render a button or clickable element with appropriate icons and text

## Implementation Details

1. Create a new file `components/UI/CopyAddress.tsx`
2. Implement the `CopyAddress` component with the following features:
   - Props: `address: string`, `className?: string`, `iconSize?: string`
   - State: `copied: boolean`
   - Methods: `copyToClipboard()` to handle copying and setting the "copied" state
   - Render: A clickable element with `CopyIcon` or `VerifiedIcon` based on the `copied` state
3. Use the new `CopyAddress` component in `ProfileCard` and `WalletButton`, replacing the existing copy address functionality.

## Example Component Structure

```tsx
import React, { useState } from 'react';
import CopyIcon from "@components/UI/iconsComponents/icons/copyIcon";
import VerifiedIcon from "@components/UI/iconsComponents/icons/verifiedIcon";
import { Tooltip } from "@mui/material";
import { writeToClipboard } from "@utils/browserService";

interface CopyAddressProps {
  address: string;
  className?: string;
  iconSize?: string;
}

const CopyAddress: React.FC<CopyAddressProps> = ({ address, className, iconSize = "20" }) => {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = () => {
    setCopied(true);
    writeToClipboard(address);
    setTimeout(() => {
      setCopied(false);
    }, 1500);
  };

  return (
    <div className={className} onClick={copyToClipboard}>
      {!copied ? (
        <Tooltip title="Copy" arrow>
          <div>
            <CopyIcon width={iconSize} color="#F4FAFF" />
          </div>
        </Tooltip>
      ) : (
        <VerifiedIcon width={iconSize} />
      )}
    </div>
  );
};

export default CopyAddress;
```

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this?

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by NueloSE** [comment]
@fricoben can i work on this task

**Comment by petersdt** [comment]
@fricoben can i work on this

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am aWeb3/ frontend developer
with a lot of experiences in open source contribution

### How I plan on tackling this issue
1. Create a reusable `CopyAddress` component that handles the copying logic, manages the "copied" state, and accepts `address`, `className`, and `iconSize` as props.
2. Refactor `ProfileCard` and `WalletButton` to replace their individual copy logic with the `CopyAddress` component.
3. This ensures code reuse, reduces duplication, and maintains consistent behavior across components.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i would love to work on this issue 
Please kindly assign

### How I plan on tackling this issue
Identify Duplication: Recognize duplicate address copying logic in ProfileCard and WalletButton.

Define Purpose: Create a reusable CopyAddress component to handle address copying.

Create File: Set up a new file at components/UI/CopyAddress.tsx.

Import Dependencies: Import React, icons, Tooltip from MUI, and clipboard utility.

Define Props Interface: Create CopyAddressProps to specify address, className, and iconSize.

Manage State: Use useState to handle a copied boolean state.

Implement Copy Logic: Define copyToClipboard to copy the address and manage the "copied" state.

Render Component: Create a clickable div that conditionally shows CopyIcon or VerifiedIcon.

Export Component: Export the CopyAddress component.

Integrate: Replace existing copying logic in ProfileCard and WalletButton with CopyAddress

**Comment by Kaminar-i** [comment]
hello @fricoben  i would love to work on this issue 
Please this is will my first time contributing on this repo if i'm giving the opportunity

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end and a blockchain developer and I will love to work on this

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am blockchain developer and i will like to work on this issue 

### How I plan on tackling this issue
1. Create `components/UI/CopyAddress.tsx`:
   - Accept address, className, and iconSize as props.
   - Manage the copied state.
   - Implement copyToClipboard to copy the address and update copied state.
   - Render the clickable element with CopyIcon or VerifiedIcon based on copied.
2.  I will use the new CopyAddress component in both  ProfileCard and WalletButton, replacing their current copy logic. 
This reduces redundancy and ensures consistency across the app.

**Comment by Oshioke-Salaki** [comment]
Please can I work on this?

**Comment by fricoben** [comment]
Assigned to @sajalbnl
