### ISSUE TITLE
Merge Clickable Social Media Icon Components

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#852]
## Description

Currently, we have separate components for clickable social media icons:
- `clickableTwitterIcon.tsx`
- `clickableGithubIcon.tsx`
- `clickableDiscordIcon.tsx`

These components share similar structures and functionalities. To reduce code duplication and improve maintainability, we should merge them into a single, reusable component.

## Current Behavior

Each social media platform has its own component with duplicated logic for rendering icons and handling clicks.

## Proposed Solution

Create a new `ClickableSocialIcon` component that can handle multiple social media platforms based on props.

### Example Implementation

```typescript
import React from 'react';
import { Tooltip } from "@mui/material";
import TwitterIcon from "@components/UI/iconsComponents/icons/twitterIcon";
import GithubIcon from "@components/UI/iconsComponents/icons/githubIcon";
import DiscordIcon from "@components/UI/iconsComponents/icons/discordIcon";

type SocialPlatform = 'twitter' | 'github' | 'discord';

interface ClickableSocialIconProps {
  platform: SocialPlatform;
  width: string;
  domain?: string;
  profileId: string;
}

const ClickableSocialIcon: React.FC<ClickableSocialIconProps> = ({
  platform,
  width,
  domain,
  profileId
}) => {
  const getIcon = () => {
    switch (platform) {
      case 'twitter': return <TwitterIcon width={width} color="#1DA1F2" />;
      case 'github': return <GithubIcon width={width} color="#101012" />;
      case 'discord': return <DiscordIcon width={width} color="#5865F2" />;
    }
  };

  const getUrl = () => {
    switch (platform) {
      case 'twitter': return `https://twitter.com/${profileId}`;
      case 'github': return `https://github.com/${profileId}`;
      case 'discord': return `https://discord.com/users/${profileId}`;
    }
  };

  return (
    <Tooltip title={`Check ${domain} ${platform}`} arrow>
      <div onClick={() => window.open(getUrl())}>
        {getIcon()}
      </div>
    </Tooltip>
  );
};

export default ClickableSocialIcon;
```

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i am frontend developer 

### How I plan on tackling this issue
To solve this problem, I will refactor the duplicated social media icon components into a single ClickableSocial Icon component that takes in props to determine the platform (Twitter, GitHub, or Discord). The component dynamically selects the appropriate icon and URL based on the platform prop,thereby  reducing code duplication while maintaining functionality.
This implementation uses a switch statement in getIcon to render the correct icon and in getUrl to handle the URL generation. The component is wrapped in a Tooltip and uses an onClick event to open the corresponding social media link in a new window.

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

Hey! I'm Lau Chaves, and I would like to contribute to this issue! would be my first contributing to this proyect!


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components. 

Feel free to check my onlydust profile [here](https://app.onlydust.com/u/lauchaves) and github profile: lauchaves!


### How I plan on tackling this issue
Id use the proposed solution as base and guide and will create a reusable single component for social media icons

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by martinvibes** [comment]
hello @fricoben i would love to work on this issue kindly assign :)

**Comment by fricoben** [comment]
assigned to @lauchaves, other issues here https://github.com/lfglabs-dev/starknet.quest/issues/
