### ISSUE TITLE
Create Reusable Loading Component and implement it

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#853]
## Description

Currently, loading states are handled inconsistently across different components in our application. This leads to code duplication and potential inconsistencies in user experience. We need a centralized approach to manage loading states. 

## Current Behavior

Loading states are implemented separately in various components, often using different methods (e.g., skeletons, spinners) and styles.

## Proposed Solution

Create a reusable `LoadingWrapper` component that can be used across the application to standardize loading UI and behavior.

### Example Implementation

```typescript
import React from 'react';
import { Skeleton, CircularProgress } from '@mui/material';

type LoadingType = 'skeleton' | 'spinner';

interface LoadingWrapperProps {
  isLoading: boolean;
  loadingType?: LoadingType;
  children: React.ReactNode;
  width?: string | number;
  height?: string | number;
}

const LoadingWrapper: React.FC<LoadingWrapperProps> = ({
  isLoading,
  loadingType = 'skeleton',
  children,
  width = '100%',
  height = 100
}) => {
  if (!isLoading) return <>{children}</>;

  switch (loadingType) {
    case 'skeleton':
      return <Skeleton variant="rectangular" width={width} height={height} />;
    case 'spinner':
      return <CircularProgress />;
    default:
      return null;
  }
};

export default LoadingWrapper;
```

This component can be used to wrap content that might be in a loading state:

```typescript
<LoadingWrapper isLoading={isLoading} loadingType="skeleton">
  <YourComponent />
</LoadingWrapper>
```

By implementing this `LoadingWrapper`, we can standardize loading states across the application, improving consistency and reducing code duplication. To test your component please implement it once on `/quests/page.tsx` by replacing our current code here 

```tsx
        {loading ? (
          <FeaturedQuestSkeleton />
        ) : (
 ```

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a web3/frontend developer
With a lot of experiences in opensource contributions

### How I plan on tackling this issue
1. Import the `LoadingWrapper` component into `/quests/page.tsx`.
2. Replace the existing loading logic with the `LoadingWrapper`.
3. Use the `LoadingWrapper` component to wrap the content, specifying the `isLoading` and `loadingType` props.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by martinvibes** [comment]
i would love to take on this issue :) @fricoben

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey, Im Lau Chaves, Id like to work on this one! I have over 5 years of experience working with JS, TS, react among others, had solid bases on CSS, SCC, Styled components. 

Feel free to check my OD [profile](https://app.onlydust.com/u/lauchaves) or github profile!

### How I plan on tackling this issue
Id created the component where we would have all the loading state as in the proposed solution or just send as prop the type of loading instead of wrapper, id would check the best approach or discuss it with maintainer and Ill update/refactor all the loadings across the app to use the new loading component

**Comment by Kaminar-i** [comment]
hello @fricoben please i would love to take on this issue kindly assign i'm new

**Comment by Ugo-X** [comment]
hello @fricoben Please can i be assigned to this?

**Comment by fricoben** [comment]
assigned to @Ugo-X

**Comment by Ugo-X** [comment]
> assigned to @Ugo-X

Thank you ser, will get to it.
