### ISSUE TITLE
Delete the notion of XP and leaderboard from the dashboard

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#854]
## Description
<img width="540" alt="Capture d’écran 2024-10-04 à 11 30 11" src="https://github.com/user-attachments/assets/db479120-4c06-4f65-8e8a-47e734b8f629">

The ProfileCard component currently includes a feature that displays the user's percentile ranking compared to other players. This feature is no longer needed and should be removed to simplify the component and improve performance.

## Current Behavior

The ProfileCard component calculates and displays a user's percentile ranking. This includes:
- State management for `userPercentile`
- Calculation logic in the `computeData` function
- Conditional rendering of the percentile information or a loading skeleton

## Proposed Solution

Remove all code related to the user percentile feature from the ProfileCard component. This includes:

1. Remove the `userPercentile` state and its setter
2. Remove the percentile calculation logic from the `computeData` function
3. Remove the JSX that renders the percentile information
4. Remove any unused imports related to this feature

## Implementation Details

1. Remove state declaration:
   ```typescript
   const [userPercentile, setUserPercentile] = useState("");
   ```

2. Remove percentile calculation from `computeData`:
   ```typescript
   // Remove this block
   const computedUserPercentile = calculatePercentile(
     leaderboardData?.position ?? 0,
     leaderboardData?.total_users ?? 0
   ).toString();
   setUserPercentile(computedUserPercentile);
   ```

3. Remove the JSX that renders the percentile information:
   ```typescript
   <Typography type={TEXT_TYPE.BODY_SMALL} className={styles.percentileText} color="secondary">
     {userPercentile.length > 0 && userPercentile !== "NA" ? (
       <>
         {isOwner ? "You are " : "This user is "}
         <span className={styles.green_span}>
           better than {userPercentile}%
         </span>{" "}
         of other players.
       </>
     ) : (
       <Skeleton
         variant="text"
         className={questStyles.featuredQuestContentLoading}
         sx={{ fontSize: "1rem", bgcolor: "grey.800" }}
       />
     )}
   </Typography>
   ```

4. Remove any unused imports, such as:
   ```typescript
   import { calculatePercentile } from "@utils/numberService";
   ```

5. Remove any styles related to the percentile text in the CSS files.

By implementing these changes, we will simplify the ProfileCard component and remove an unused feature.

**Comment by ShantelPeters** [comment]
Hi @fricoben please let me work on this issue

**Comment by Crosstons** [comment]
@fricoben  Let me work on this, it will be my first contribution to starknet quest

**Comment by Iwueseiter** [comment]
Hello @fricoben please can I be assigned to this task?

**Comment by martinvibes** [comment]
**hello @fricoben please can i work on this issue :)** 🙃

**Comment by NueloSE** [comment]
@fricoben can i be assigned this

**Comment by Kaminar-i** [comment]
@fricoben can i be assigned this issue please assign me

**Comment by petersdt** [comment]
@fricoben can i work on this issue

**Comment by EnochScript** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a frontend developer with expertise in html, CSS,  CSS frameworks, JavaScript and react. This presents an opportunity for me to make my first contribution in an ODHack. My skill and knowledge in what is required  and my  ability to find  solutions to problems will be helpful.

### How I plan on tackling this issue
I will locate the jsx file that contains the code for the feature, I will delete the state declaration and the code for the percentile calculation. I will then delete the code that renders the percentile calculation and unused imports for the feature.

**Comment by vinaykumar0103** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
With my background as a full-stack blockchain developer, I have experience working with React.js and JavaScript/TypeScript. I’ve worked on projects where I've had to clean up and optimize frontend components by removing unused features, improving state management, and ensuring everything runs efficiently.

Remove Unneeded State: I’m used to working with React's useState, and I can easily remove the userPercentile state and related logic.

Simplify the Code: I've handled similar tasks before where I’ve cleaned up components by removing unnecessary calculations and rendering logic.

Clean Up Imports and Styles: I’m familiar with making sure unused imports and styles are removed to keep the codebase clean and maintainable.

### How I plan on tackling this issue
Remove the State: Take out the userPercentile state and its setter from the component.

Delete the Logic: Remove the percentile calculation from the computeData function.

Update the UI: Get rid of the JSX code that displays the percentile ranking or loading skeleton.

Clean Up Imports: Remove any imports related to the percentile calculation.

Remove CSS: Delete any CSS styles used for the percentile text.

Test: Finally, test the component to ensure everything functions correctly after the changes.

**Comment by Benjtalkshow** [comment]
@fricoben Can you assign thisw task to me? i am tackle this issue asap. Thanks

**Comment by 0xdevcollins** [comment]
Hi @fricoben, could you please assign this issue to me? I’ll make sure to deliver quality work.

**Comment by fricoben** [comment]
> Hi @fricoben, could you please assign this issue to me? I’ll make sure to deliver quality work.

assigned @devcollinss
