### ISSUE TITLE
refactor `profileCard.tsx` margin 

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#865]
## Description 

refactor `profileCard.tsx` margin from 
<img width="565" alt="Capture d’écran 2024-10-08 à 18 08 31" src="https://github.com/user-attachments/assets/5f1548e5-4eca-4dc0-9593-0381116d5813">
 
to 

<img width="596" alt="Capture d’écran 2024-10-08 à 18 09 12" src="https://github.com/user-attachments/assets/172075dc-2aa5-4715-87e4-dd180ee0dc55">

## Proposed Changes
1. Change the justification from `justify-between` to `justify-center` for better vertical alignment.
2. Add a small margin (0.5rem) to the domain part to improve spacing.

## Implementation Details

In the `components/UI/profileCard/profileCard.tsx` file, make the following changes:

1. Modify the flex container for the profile information:

   From:
   ```jsx
   <div className="flex flex-col h-full justify-between">
   ```
   To:
   ```jsx
   <div className="flex flex-col h-full justify-center">
   ```

2. Add margin to the domain (profile name) Typography component:

   From:
   ```jsx
   <Typography type={TEXT_TYPE.H2} className={styles.profile_name}>{identity.domain.domain}</Typography>
   ```
   To:
   ```jsx
   <Typography type={TEXT_TYPE.H2} className={`${styles.profile_name} mt-2`}>{identity.domain.domain}</Typography>
   ```

I'm not sure it works so make it work as the image.

**Comment by Iwueseiter** [comment]
Hi @fricoben  can I work on this?
I’m a frontend and smart contract developer and I’d get this done ASAP.
Kindly assign.

ETA: 6hrs.

**Comment by ShantelPeters** [comment]
Hi @fricoben  please i will like to work on this issue

**Comment by 0xdevcollins** [comment]
Hello @fricoben  Can i be assigned this task, i will deliver in 24hrs

**Comment by fishseabowl** [comment]
Hi @fricoben could I work on this? I believe it should be completed in about an hour.

**Comment by DiegoB1911** [comment]
Hi! I am a Full Stack Developer with two years of experience, primarily working with Next.js, and I have also worked with Tailwind. I am an active member of Dojo Coding, where I am expanding my expertise in Cairo and Web3 technologies. I am enthusiastic about learning and contributing to this project.

To solve this issue, I would first try what you propose. I will change the justification from justify-between to justify-center in the flex container and add a small margin to the Typography component.

**Comment by lauchaves** [comment]
Hey, Ive been working on the profilecard, may I give this one a try?

**Comment by martinvibes** [comment]
hello @fricoben i would love to be the one to work on this issue :)

**Comment by NueloSE** [comment]
hi @fricoben  can i be assigned this task

**Comment by Kaminar-i** [comment]
hello @fricoben please can i work on this issue?
i would love to be a contributor

**Comment by petersdt** [comment]
good day @fricoben i would like to make this my first contribution to the starkquest project. kindly assign me.
ETA 48hours

**Comment by MatiasAchucarro** [comment]
Hello @fricoben  , how are you?  I would love to take this issue as it would be my second contribution to Starknet Quest. I’m really motivated to keep learning and working with you, and I would be excited to continue contributing to the project.

**Comment by fricoben** [comment]
assigned @fishseabowl
