### ISSUE TITLE
Claim reward flow

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#868]
## Claim reward flow

Implement the design from https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5850-398&t=c7GUSczdc1oYxVIF-1
into the "Earn" page.

It currently looks like that:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/e1c7a907-64f7-4678-b81e-f896fdae44a3">

Use mock values (template values) for the modal. We'll implement the backend later.

## PROPOSED TODO

- [ ] Add the "Claim all button" :
<img width="494" alt="image" src="https://github.com/user-attachments/assets/7e5a07cb-dca9-4972-99d5-0564c5ccd6d2">

- [ ] Add the claim modal:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/fa7d2a30-91f2-414b-b57c-1e82d7e03b2c">

- [ ] Show the popup (reuse the component we already wrote):
<img width="648" alt="image" src="https://github.com/user-attachments/assets/b8e4f50e-2722-4abd-aeaa-bf7888e528ab">

- [ ] Make the interactions working: clicking the button -> show the modal -> confirm -> success popup

**Comment by Oshioke-Salaki** [comment]
can i do this please?

**Comment by od-hunter** [comment]
Can I work on this please? @Marchand-Nicolas 
I’ll go through the Figma file carefully and make sure to implement the right changes correctly and make sure to add interactions.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi @Marchand-Nicolas please can I be assigned to this issue ? I  am a frontend developer and i will like to contribute more to this ecosystem .

### How I plan on tackling this issue
1. Add "Claim All" button on Earn page.
2. Create a claim modal using mock values.
3. Set button to show modal on click.
4. Add confirm -> success popup flow.
5. Test with mock data.

**Comment by Ugo-X** [comment]
@Marchand-Nicolas , please can i be assigned this?

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
Hi @Marchand-Nicolas, I’d like to take on this task. I’ll ensure it's delivered as soon as possible

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi , I am a fullstack developer with 3 years experience , first time contributing and would love to hop on the issue 

### How I plan on tackling this issue
I would replicate the design to detail . E.T.C == 2 days

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years doing Full Stack with Js and Ts

**Comment by mimisavage** [comment]
Hi @Marchand-Nicolas, this is my first time contributing to this project, and I’d love to give it a try. I promise to deliver as soon as possible

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Can I work on this as soon as possible?

I am good at converting figma design to a responsive and functional page. Permit me work on this.

**Comment by KevinMB0220** [comment]
My name is Kevin, and I would like to apply to work on the frontend issue you have posted. I have experience in frontend development using technologies like Angular, TypeScript, and Ionic, among others. Additionally, I am part of Dojo Coding, which has allowed me to gain knowledge in innovative projects within the blockchain ecosystem and tools like Dojo and Unity. @Marchand-Nicolas

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I'm a front-end and a blockchain developer. I will love to work on this

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas 
Can I work on this task? I will carefully implement this feature.

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi! My name is Wheval Meze-Egbe and I’m a Frontend Developer with 2 years of experience, specializing in TypeScript, React, and Tailwindcss. I'm gonna be happy to help with this good first issue.

### How I plan on tackling this issue
Can I be assigned? I would do this in a few steps.
1. Firstly, I would create a Claim All button component and add it to the table on the Earn Page.
2. Secondly, I would create a claim modal using mock data. This modal would open when the Claim button is clicked.
3. Next, I would create a Success Component inside the Modal component that is displayed when the claim is successful.
4. The cancel button or clicking outside the claim modal would close the modal.
5. I would ensure the components are responsive on mobile devices and exactly match the designs in the figma file.

ETA is 2 days max. 
Thank you!

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Full Stack Developer with two years of experience, primarily working with Next.js. I am also an active member of Dojo Coding, where I am expanding my expertise in Cairo and Web3 technologies. I am enthusiastic about learning and contributing to this project.

### How I plan on tackling this issue
1. Check the Figma models.
2. Implement the 'Claim All' button.
3. Implement the claim modal with mock data.
4. Reuse the pop-up component when the 'Claim All' button is clicked in the modal.
5. Verify that everything is working and document the code."

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I’m a Software Developer with +3 years of experience, and I would love 
 continue making contribution to this project. I'm also a member of the Dojo Coding community CR.

### How I plan on tackling this issue
I would start by examining the Figma design to understand the necessary layout and components. Then, I would integrate the "Claim All" button, ensuring it matches the visual specifications outlined in the design.

Following this, I would construct the claim modal with placeholder data to simulate functionality until we integrate the backend later. I would also ensure the existing popup component is utilized when the "Claim All" button is activated, providing a consistent user experience.

Once the modal is implemented, I would focus on making the interaction seamless: clicking the button should open the modal, and users should be able to confirm their claim action, which would then trigger a success notification. Lastly, I would run comprehensive tests to confirm the entire flow works correctly and document the code for clarity and future development needs.

If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

Thank you for reading my application.

**Comment by martinvibes** [comment]
**hey @fricoben i'm a `frontend developer `and i would love to please work on this issue :)**
Please let me work on this issue

**Comment by Kaminar-i** [comment]
hello @fricoben can i have this issue and get it done to pixel perfect :)

**Comment by petersdt** [comment]
hello @fricoben i will like to take on this task.
 kindly assign me
 
 ETA <= 48hrs
