### ISSUE TITLE
Add wallet amount in $

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#877]
Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5992-2849&t=dvRbR5qAwsX8KioR-1

![image](https://github.com/user-attachments/assets/ad842fdc-671f-45e7-8d25-c5bca18a06a7)

**Comment by ooochoche** [comment]
@Kevils can I work on this?

**Comment by 0xdevcollins** [comment]
can i work on this?

**Comment by thiagoulloa** [comment]
@Kevils can I work on this?

**Comment by sajalbnl** [comment]
@fricoben i want to work on this

**Comment by emmz3230** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

### How I plan on tackling this issue
 understanding the design and how to interpret it step by step to the desire result using my front-end web development skills

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Blockchain developer experienced in JavaScript and TypeScript.

### How I plan on tackling this issue
[1]=>Review the Figma design for the wallet amount display.
[2]=>Implement code to fetch the wallet balance and convert it to USD.
[3]=>Integrate the feature into the application, ensuring design alignment.
[4]=>Test for accuracy and user experience.
[5]=> Sir/Mam please assign me this issue.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

I am a frontend developer with a strong background in integrating APIs and designing responsive UI components based on Figma designs. I have experience in working with cryptocurrency wallets and displaying real-time wallet balances by integrating financial APIs. My skills in React and JavaScript allow me to effectively manage currency conversions and data handling.





### How I plan on tackling this issue

1. **Design Analysis**: Review the Figma design to identify where and how the wallet balance in USD needs to be displayed.

2. **API Integration**: Fetch the current exchange rate for the wallet’s native currency (e.g., ETH or any other token) to USD using a reliable crypto API (like CoinGecko or CoinMarketCap).

3. **Currency Conversion**: Calculate the equivalent wallet balance in USD by multiplying the current wallet amount with the fetched exchange rate.

4. **UI Update**: Display the calculated USD amount next to the wallet balance in a well-styled format, ensuring alignment with the design in Figma.

5. **Testing**: Validate the functionality by simulating different wallet balances and ensuring the conversion updates dynamically and accurately across various devices.

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, Im part of Dojo Coding Costa Rica! I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby...

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.


### How I plan on tackling this issue
I’d create a function to format the amount to $ :) so it looks as the design! Id would use Intl.NumberFormat or regex

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years full stack dev

**Comment by ridwanalaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a frontend developer with 2 years experience building applications, this is my first contribution to starknet quest

### How I plan on tackling this issue
use the figma design to add the wallet amount in $

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Reviewing of the Figma file where the amount is implemented,
- Do the proper implementation in dollars
- Run the code and ensure proper implementation .
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by BrunoAmbricca** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello guys. I have been working for the past 4 years as a developer with js and ts.

### How I plan on tackling this issue
I would look how the wallet amount is being obtained from the wallet then do the right formatting to get it done.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Blockchain developer from Dojo Coding looking to contribute to Starknet Quest, I have experience with both TypeScript and JavaScript which makes me confident I can complete this issue.

### How I plan on tackling this issue
- Review the Figma file where the amount is implemented.
- Implement the correct dollar amount display.
- Run the code to ensure everything is working correctly.

**Comment by PedroCo3lho** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience working on projects where I implemented new designs and integrated them with the backend. I am familiar with frameworks such as React and Next.js, and proficient in JavaScript and TypeScript.

### How I plan on tackling this issue
I would start by fetching the user's portfolio data, then implement a responsive UI. To calculate the value in USD, I would fetch the current price from a cryptocurrency API.

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in blockchain and web development. I’m interested in contributing to this issue regarding displaying the wallet amount in dollars ($) as shown in the Figma design.

### How I plan on tackling this issue
I will first inspect the Figma design to understand how and where the wallet amount in dollars ($) should be displayed on the interface.I will ensure the wallet amount is fetched from the blockchain or API. If it's stored in cryptocurrency, a conversion service (such as an API for current exchange rates) will be needed to calculate the dollar equivalent.Once the wallet amount is converted to USD, I will ensure it's displayed in the appropriate location in the UI, formatted correctly as dollars

**Comment by Marchand-Nicolas** [comment]
@emmz3230 You can set a template value for now for the wallet amount. Also for the "eye" icon, don't make it interactive, another issue focuses on that. So basically, you just have to add a static template amount and a static privacy icon next to it

**Comment by Marchand-Nicolas** [comment]
Hello @emmz3230, are you working on the issue ? If it's not feasible, I can assign someone else. Keep me informed!

**Comment by emmz3230** [comment]
yes i am

**Comment by omsant02** [comment]
i would like to work on this issue @Marchand-Nicolas 
would resolve this by converting the amount into $

**Comment by Marchand-Nicolas** [comment]
@SudiptaPaul-31 
Basically, you just need to add the wallet amount here as shown in the new design, instead of the user address.
![image](https://github.com/user-attachments/assets/45f218ab-72dd-45cf-8fac-fba97f2604d4)
No need to fetch the wallet amount, nor to make the eye icon clickable, you just need to have a static visual of the thing. Two other issues are dedicated to make it dynamic and interactive!
So for example, you can simply set "2,338.54" as the wallet value

**Comment by SudiptaPaul-31** [comment]
@Marchand-Nicolas Understood thanks for assigning me this issue by when the issue should be submitted?
