### ISSUE TITLE
Add "Portfolio by protocol used" section with a donut chart and a "Claim your reward" button

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#880]
Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5992-2849&t=dvRbR5qAwsX8KioR-1

![image](https://github.com/user-attachments/assets/f5b19d3e-0959-4f04-bed3-c8ef3521e83c)

**Comment by evgongora** [comment]
Hello my name is Erick! I would like to work on this issue, I'm part of Dojo Coding and I'm a systems engineer student focusing on fullstack web development, I have experience working with TS, JS, React with Tailwind here's my profile :) https://app.onlydust.com/u/evgongora

**Comment by notlelouch** [comment]
can you please assign this to me, i would like to work on this. I can complete this task in a day or two.

**Comment by od-hunter** [comment]
Hi @Kevils , can I work on this please! I’m ready to work.

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years full stack dev

**Comment by 0xDeon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, It’s Deon again, I am Full-Stack web3 developer with significant experience in the Frontend track, i am highly proficient in writing in HTML, CSS, JavaScript and Typescript, and have worked with frameworks like React, Next and Vue. 

I’m passionate about open source and if given this chance to contribute will be my second contribution to the Starknet Quest repo, since my last contribution to Starknet quest, I have worked on improving and building on my code skills, writing and maintaining good and clean code structure, I am excited to contribute once again to this project and hope i get the chance to, Have a great day.

### How I plan on tackling this issue
- I’ll first go through and analyze the provided Figma design to understand the layout and components needed for the "Portfolio by Protocol Used" section.

- Next I’ll create the code structure and apply CSS styles to match the design specifications, also depending on the css framework, I’ll apply my expertise in Vanilla CSS, Bootstrap, Material UI, Sass, Tailwind, or Chakra UI to achieve the desired look.

- After working on the styling, I would depending on if the code already has a charting library use the existing one or opt out if not and install a much suitable charting library like recharts or chart.js to develop the donut chart, ensuring it accurately represents the portfolio data.

- After completing the donut chart, I will then implement the "Claim Your Reward" button, ensuring it’s functional and styled as per the design in the figma file.

-- Once that is completed I’ll test the section for responsiveness and cross-browser compatibility, making sure everything functions perfectly and would make adjustments if needed.

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in the field of blockchain and web development. I'm excited to work on the addition of the "Portfolio by protocol used" section as described in this issue.

### How I plan on tackling this issue
My approach to solve this issue:
I will start by closely examining the Figma design to understand the layout and visual style of the donut chart and the "Claim your reward" button.

I will use a charting library, such as recharts or chart.js, to implement the donut chart. I will gather the necessary data to display the portfolio breakdown by protocol used

Below the donut chart, I will add a button for claiming rewards, styled according to the Figma design. A simple implementation might look like this:
jsxconst ClaimRewardButton = () => (
    <button className="claim-reward-button">Claim Your Reward</button>
);
I will create a new section component that includes both the PortfolioChart and the ClaimRewardButton. This section will be integrated into the existing layout.
ETA-1day

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi I'm Alvaro Lazarus a blockchain developer, and a new member of Dojo Coding. I have contributed to Starknet Quest in the past and would love to work on the project again, I'm well versed with data visualization which makes me confident I can work on this section smoothly.

### How I plan on tackling this issue
- Analyze the Figma design for the "Portfolio by Protocol Used" section.
- Build the code structure and apply CSS styles using the appropriate framework.
- Develop the donut chart with a suitable charting library.
- Implement and style the "Claim Your Reward" button.
- Test for responsiveness and cross-browser compatibility.

Best regards,
Lazarus

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a solid background in front-end web development, with experience in converting design specifications into functional web pages. I am proficient in HTML, CSS, and JavaScript, and I have worked extensively with design tools like Figma to ensure pixel-perfect implementations. My strong understanding of responsive design principles enables me to create user-friendly interfaces that work across various devices and screen sizes.

### How I plan on tackling this issue
To implement the design from the provided Figma file, I will first analyze the layout and elements outlined in the design. I will create a detailed plan for structuring the HTML to ensure semantic and accessible markup. Next, I will use CSS to accurately replicate the styles from Figma, focusing on colors, fonts, and spacing to achieve a pixel-perfect result.

For responsiveness, I will adopt a mobile-first approach, utilizing media queries to adapt the layout for different screen sizes seamlessly. I will also implement interactive elements using JavaScript, ensuring they function smoothly and enhance the overall user experience. Throughout the development process, I will conduct cross-browser testing to identify and resolve any discrepancies, maintaining a consistent look and feel across all platforms. Finally, I will document the implementation process to aid future maintenance and improvements.

**Comment by Villarley** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am Santiago Villarreal Arley, a passionate software developer with a growing interest in Web3 technologies. Over the past few months, I've had the opportunity to work on innovative projects, such as BuildMyEvent, an open-source initiative that leverages blockchain and decentralized systems. I thrive on problem-solving and enjoy the challenge of integrating cutting-edge solutions into real-world applications. My goal is to contribute to the Web3 ecosystem by staying ahead of emerging trends, learning continuously, and developing projects that push the boundaries of decentralized technologies.


### How I plan on tackling this issue
To tackle the "Portfolio by protocol used" section, here’s my proposed solution:

Donut Chart Implementation:

I would utilize a charting library like Chart.js or Recharts to create a clean and interactive donut chart. The chart would dynamically display the portfolio distribution based on protocols used.
The data could be fetched via an API or passed as props, ensuring each protocol is visually represented as a segment of the donut chart with its corresponding percentage of use.
"Claim your reward" Button:

The button will be positioned below the chart, styled according to the Figma design.
On click, it will trigger an action to claim the user’s reward, which can involve calling an API or handling any necessary authentication flow.
I’ll make sure to include visual feedback (loading indicator, success confirmation) to provide a smooth user experience.
Design & Layout:

I’ll strictly follow the Figma design to match the overall layout and feel of the project, ensuring responsiveness and consistency.
Using Tailwind CSS (or the project's current styling approach), I’ll maintain a clean, scalable layout.
Testing and Feedback:

I would ensure the chart is responsive and that the "Claim your reward" button is functional and user-friendly.
Proper integration with the backend will be key for a seamless reward claim process.
I look forward to contributing to this feature and bringing it to life as part of the Starknet.quest project!

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a React developer with over two years of experience and have recently developed a strong interest in blockchain technology. I have valuable experience navigating codebases and I have worked on this codebase before fixing a small bug. I will be happy to take on the challenge by work on this task and submit within 1-2days.



### How I plan on tackling this issue
locate the folder to add the section
study the figma file and start conversion
implement design and functionalities
test thoroughly to make the functionalities are working fine

**Comment by Marchand-Nicolas** [comment]
@joeperpetua To collect the necessary data, you can use the Argent Portfolio API. I suggest you to check in the network tab of the console what call they do on their official website: https://portfolio.argent.xyz/overview/0x05f1f8de723d8117daa26ec24320d0eacabc53a3d642acb0880846486e73283a.
