### ISSUE TITLE
Bug image

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#883]
![image](https://github.com/user-attachments/assets/497b28e1-84de-4690-90ff-24f7ae6e91a2)

The image of "Defi Quest" category is not diplaying

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Fullstack developer, with experience building dapps

### How I plan on tackling this issue
Would find image link and make it display

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Can I be assigned this issue? I will deliver as soon as possible

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Reviewing of the file while the DefiQuest image is implemented:
-check through the method of implementation.
- implement the image properly for display in the right magnitude .
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on the Review of the PR

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a developer with 4 years of hands-on experience in JavaScript and TypeScript, specializing in frontend development and troubleshooting UI issues. I've worked extensively with image rendering in web applications and have contributed to several open-source projects dealing with similar display problems.

### How I plan on tackling this issue
Approach to the Problem:
Based on the "Defi Quest" category image not displaying, I would:

First inspect the image source URL and network tab to verify if the image is loading correctly
Check the image component implementation, looking for:

Correct path/URL configuration
Image import method
Proper error handling


Review related CSS styles to ensure visibility properties and dimensions are set correctly
Implement a fallback/error state to improve user experience

Proposed solution would likely involve:
typescriptCopy// Adding error handling and fallback
const CategoryImage = ({ src, alt }: ImageProps) => {
  const [hasError, setHasError] = useState(false);
  
  return (
    <img 
      src={hasError ? '/fallback-image.png' : src}
      alt={alt}
      onError={() => setHasError(true)}
      className="category-image"
    />
  );
};
I can provide a PR with the fix within 24 hours of assignment.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a full stack Blockchain developer, experienced in writing smart contracts, client side applications, open source contributor.

### How I plan on tackling this issue
I will identify the source/cause of the broken image and have it fixed

**Comment by AlakaTahir** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am writing to express my interest in this bug fix task. With a strong background in application development and a proven track record of successfully delivering high-quality tasks, I am excited about the opportunity to contribute on your projects.

Throughout my career, I have developed a variety of applications, including an employee service ERP system, a leave service API application, and an organization application with an approval workflow. In each project, I applied the Software Development Life Cycle (SDLC) approach to ensure robust design and effective execution. My work involved careful consideration of architecture, database schema design, and a commitment to clean, maintainable code.

With solid expertise on stacks including javacript, typescript, html etc. I would be fit perfectly to take on this fix.

### How I plan on tackling this issue
I will do a project setup for starknet and debugging the page affected. After that I will be able to see why defi quest category is not displaying picture.

**Comment by martinvibes** [comment]
hello @Kevils I would love to hop on this issue

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
3+ years full stack experience

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
 

### How I plan on tackling this issue
3+ years Front End developer experience

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I would like to pick this up and deliver asap

**Comment by JosueBrenes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take 1 day to complete.

### How I plan on tackling this issue
**1. Verify the image URL**

I will check that the URL is correctly set in the component that displays the image, ensuring it’s not empty or incorrectly referenced.

```jsx
<img src={imageURL} alt="Defi Quest" />
```

**2. Add error handling**

I will implement a fallback to display a backup image if the main one fails to load.

```jsx
<img src={imageURL} alt="Defi Quest" onError={(e) => e.target.src = 'fallbackImage.png'} />
```

**3. Data validation**

I will validate that the image URL is present before trying to display it.

**Comment by GradleD** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Full Stack Web Developer with over 4+ years of Experience

### How I plan on tackling this issue
Potential Issues and Solutions
1. Image Not Displaying
If the image (category.img) is not displaying, consider the following:
Check Image URL: Ensure that the URL provided in category.img is valid and accessible. You can log it to verify:
javascript
console.log(category.img);

Fallback Image: Implement a fallback image in case the provided URL fails to load:
javascript
<CDNImg src={category.img} loading="lazy" onError={(e) => { e.target.src = '/path/to/fallback/image.png'; }} />

2. Completed Quest Count Logic
Make sure that the logic for counting completed quests is accurate:
Ensure Data Integrity: Verify that completedQuestIds and category.quests are populated correctly. You can log them for debugging:
javascript
console.log(completedQuestIds, category.quests);

Check Filtering Logic: The filtering logic should be correct. If q.id does not match any id in completedQuestIds, then it will return zero:
javascript
const completedQuestNumber = useMemo(
  () => category.quests.filter((q) => completedQuestIds?.includes(q.id)).length,
  [category.quests, completedQuestIds] // Ensure dependencies are correct
);

3. CSS Styles
If styles are not applying as expected:
Inspect Element: Use browser developer tools to inspect the rendered HTML and check if styles are being overridden or not applied.
Class Names: Ensure that class names from your CSS modules are correctly referenced.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am deeply interested in the Web3 space, and currently, I’m working as a frontend development intern at a Web2 company, where I’m primarily using Next.js. I’m eager to gain more experience and would love for this to be my first issue to tackle. It would be a great opportunity for me to contribut and I’d really appreciate the chance to work on it!

### How I plan on tackling this issue
To resolve the "Defi Quest" image not displaying, I would:

Check the image URL in the browser's dev tools to ensure it's correct.
Verify the image path and confirm it's stored in the correct directory.
Check file permissions to ensure the server can serve the image.
Clear browser cache to rule out caching issues.
Implement a placeholder image as a fallback if the original doesn't load.
Check network issues in the dev tools for failed requests.

**Comment by fricoben** [comment]
@Otaiki1 I assigned you there

**Comment by Otaiki1** [comment]
Oh , Would get on it asap

**Comment by fricoben** [comment]
> Oh , Would get on it asap

Still waiting, if I see no PR today I'll reassign

**Comment by Otaiki1** [comment]
> > Oh , Would get on it asap
> 
> Still waiting, if I see no PR today I'll reassign

Hi , I have been able to trace down the issue to the image URL not being fetched from the API , Is it possible that no image was added for that particular quest ? . My solution would be to have a default image URL for images that fail to load ( would that suffice ?)

**Comment by fricoben** [comment]
> Hi , I have been able to trace down the issue to the image URL not being fetched from the API , Is it possible that no image was added for that particular quest ? . My solution would be to have a default image URL for images that fail to load ( would that suffice ?)

Yes so this is a problem of category I just checked and fixed it but it'll appear again, to make it not appear again you need to change the `DeFi` string here to `deFi` in the const `CATEGORY_OPTIONS` of the `admin.ts` file. 

Please raise a PR and I'll merge it.

**Comment by Otaiki1** [comment]
@fricoben  , i have raised a PR
