### ISSUE TITLE
Add Kepler wallet to the app

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#886]
Following the work done in the PR closing this issue https://github.com/lfglabs-dev/app.starknet.id/issues/898 please add the kepler wallet to the starknet quest app. 

You need to test it works by trying to connect and launch tx through [the Kepler wallet](https://chromewebstore.google.com/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap)

**Comment by Iwueseiter** [comment]
Hi @fricoben can I work on this?

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
As a fullstack blockchain developer, my work with StarkLudo (a starknet onchain game's frontend) in the recently concluded O.D hack 8.0 and subgraphs for querying on-chain data shows my familiarity with the Starknet ecosystem and integrating wallets with smart contracts. 

### How I plan on tackling this issue
Review the PR that resolved the original issue (GitHub issue #898) to understand:
 - How the existing wallets were integrated.
 - Dependencies or libraries used for Starknet wallet connections (like ethers.js or starknet.js).
 - Any connection management logic or middleware used for transaction handling.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Understanding the way existing wallets are integrated:
- Check through the codes and follow the same procedure to implement the Kepler wallet.
- Make use of the existing and needed libraries .
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Fullstack blockchain developer with exp building dapps that interact with kepler

### How I plan on tackling this issue
I would add the proper requests and demo it workinbg

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a solid foundation in web development and blockchain technologies, focusing on integrating wallets with decentralized applications. My experience includes both frontend and backend systems, allowing me to effectively manage wallet connectivity and user interactions. 

### How I plan on tackling this issue
I would start by reviewing the previous pull request to understand the existing wallet integration structure. Then, I would implement the Kepler wallet integration using its SDK or API, adding the required connection buttons and managing authentication.
After integration, I would conduct thorough testing, simulating successful connections, failed attempts, and transaction launches. 
Finally, I would document the integration process and any issues encountered while seeking feedback from the team to ensure all requirements are met.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @fricoben  I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. I would like to contribute to this project 

### How I plan on tackling this issue
First, I will install and import the Kepler wallet connector/SDK according to their documentation. Then I will update the wallet connection logic to include Kepler as a supported option alongside existing wallets.  Next, I'll implement the connection handler that initializes the Kepler provider and requests user approval. Then for transaction testing, I'll create a test transaction, trigger it through the app's interface, and verify that the Kepler wallet popup appears correctly for signing.

**Comment by jaiminRaiyani** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a computer engineering student with a strong foundation in software development and a passion for creating innovative solutions. My educational background has equipped me with solid knowledge in programming languages such as C, .NET, JavaScript, Node.js, and React.js, alongside extensive experience in blockchain technology.
 I have worked on several projects, including a Dynamic Form application and a React Voting Application. These experiences have reinforced my skills in state management using Redux and designing user-friendly interfaces while ensuring optimal performance and security.

### How I plan on tackling this issue
To add the Keplr wallet to the application, I would follow a structured approach to ensure seamless integration and functionality. Here’s how I would tackle the task:

Understanding the Requirements:

I would begin by reviewing the requirements for integrating the Keplr wallet, ensuring clarity on its features, such as connecting, signing transactions, and displaying the user’s wallet information.

Adding the Keplr Wallet Logo and Information:

I would ensure that the Keplr wallet logo is available in the project directory (e.g., src/assets/keplr-logo.png).
I would update the wallet configuration file (e.g., wallets.js) to include the Keplr wallet information. 

Integrating Keplr Wallet:

I would implement the logic to connect to the Keplr wallet using its API. This includes adding the necessary methods to handle wallet connections.

Testing the Integration:

After implementing the integration, I would conduct thorough testing to ensure the wallet functions as expected. This would involve:
Checking if the wallet connects successfully.
Verifying the ability to sign transactions.
Testing the handling of any errors that may arise during the connection process

I would update the UI components to include a button for connecting the Keplr wallet. The button would call the connectKeplrWallet function when clicked.

Review and Deployment:

Finally, after ensuring that everything works well through testing, I would conduct a review of the code and implementation with team members. I would gather feedback and make necessary adjustments before merging the changes into the main branch for deployment.
