### ISSUE TITLE
Error in claiming defi-rewards through " claim all " option

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#887]
Details : https://www.loom.com/share/c4f4ee2443ef46448fe731b0f3164d64?sid=ad8ddc96-6f1d-45e5-bf20-265a94e905e0

Wallet used Braavos 
Defi rewards are from " Nimbora "
Error code : 
LibraryError: RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x54e0ab67bd384312d640915b55d7e918fe2031269ec26f8fc7fde9abbd1e0a5",
      "calldata": [
        "0x1",
        "0x7ed46700bd12bb1ee8a33a8594791003f9710a1ab18edd958aed86a8f82d3d1",
        "0xb758361d5e84380ef1e632f89d8e76a8677dbc3f4b93a4f9d75d2a6048f312",
        "0xf",
        "0x103920ae6001811ee",
        "0xd",
        "0x235b2aed107f7d3e255e6a3571d15aa4d90021f553ed41e25f533c1c0b93d70",
        "0x13791458da6faf50789e37266703942a628664224618bb5f225b45a31d97526",
        "0x72c60ac647c995829504eb3c99ad5d431bc65e68a1e43c9f1482755107669c8",
        "0x4c4b01fa101662a383f1006627bd11ec99473a9355923b2514b60a9f9a4b3b1",
        "0x5a6a29b96ec25d9b8a61ab6fccaaa9e372e43e132b838bd80e136e80307c0d9",
        "0x61f6386b5249329c5266fc643a78faf52839ff1c833fdc35b8b9fc924bdd1",
        "0x4640295ad56582f8f926239768e89ce9c2cb51992ecaa01220f10abd51c96c",
        "0x1cefeba33828480f9b4665f231bc00a927c1e8ccff13c58195d5cc0930d2e78",
        "0x647e2345df95e19cd72fde6f813d25360d4a86670b2f97fdd1f5f44a30c4b4a",
        "0x5550ac8026eecf5065dbb11721625eb3b8b89a6d174edfc852385ebf68997b0",
        "0xaa6a96a91a6d8de706dd40b86124e265e0adc0dd66413b1afd5886fa4d6b6b",
        "0x5c41a47303845fd6589f455b73e915dc16943326f8ef5738fc28a331138e15d",
        "0x4d0c4166e73cf884e4eb0c8f5c6674886b95b37908d3579e8b89efcc8b71a1b"
      ],
      "version": "0x100000000000000000000000000000003",
      "signature": [
        "0x5",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0",
        "0x0"
      ],
      "nonce": "0x1af",
      "resource_bounds": {
        "l2_gas": {
          "max_amount": "0x0",
          "max_price_per_unit": "0x0"
        },
        "l1_gas": {
          "max_amount": "0x0",
          "max_price_per_unit": "0x0"
        }
      },
      "tip": "0x0",
      "paymaster_data": [],
      "nonce_data_availability_mode": "L1",
      "fee_data_availability_mode": "L1",
      "account_deployment_data": []
    }
  ],
  "block_id": "pending",
  "simulation_flags": []
}
 
        41: Transaction execution error: {"transaction_index":0,"execution_error":"reverted: Transaction execution has failed:\n0: Error in the called contract (contract address: 0x054e0ab67bd384312d640915b55d7e918fe2031269ec26f8fc7fde9abbd1e0a5, class hash: 0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):\nError at pc=0:20259:\nCairo traceback (most recent call last):\nUnknown location (pc=0:309)\nUnknown location (pc=0:5819)\nUnknown location (pc=0:11008)\n\n1: Error in the called contract (contract address: 0x07ed46700bd12bb1ee8a33a8594791003f9710a1ab18edd958aed86a8f82d3d1, class hash: 0x006a54af2934978ac59b27b91291d3da634f161fd5f22a2993da425893c44c64, selector: 0x00b758361d5e84380ef1e632f89d8e76a8677dbc3f4b93a4f9d75d2a6048f312):\nExecution failed. Failure reason: 0x494e56414c49442050524f4f46 ('INVALID PROOF').\n"}

**Comment by Abeeujah** [comment]
Hi, I would love to work on resolving this.

**Comment by fishseabowl** [comment]
@revengexd Could I work on this? Thanks

**Comment by od-hunter** [comment]
Can I work on this asap please? @fricoben
