### ISSUE TITLE
Needs correction in info shown for boost quest !

### ISSUE THREAD

**Issue by revengexd** [starknet-id/starknet.quest#889]
Link : https://starknet.quest/

<img width="755" alt="Screenshot 2024-10-19 at 1 31 50 AM" src="https://github.com/user-attachments/assets/e2f9f5c7-1439-432b-a783-b7b46684a968">

Boost quest shows 13/13 but shows only 3 ...either it must show " 3/13 or 3 "
<img width="755" alt="Screenshot 2024-10-19 at 1 33 08 AM" src="https://github.com/user-attachments/assets/85e77415-deb5-465e-a158-8a6ef04d0d52">

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by fishseabowl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain full-stack developer and have contributed to numerous open-source projects, including StarkNet.quest.

### How I plan on tackling this issue
I would check the fetchBoosts variable, update, and test. I believe it should be completed in about a couple of hours.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.


### How I plan on tackling this issue
i will have it as soon as possible

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
 

### How I plan on tackling this issue
3+ years Front End developer experience

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @revengexd,
I'm Wheval, a frontend developer with 3 years experience building responsive and user-friendly interfaces with React, typescript and css. I would really love to contribute to the Starknet quest. From my experience I can fix this issue.

### How I plan on tackling this issue
I have cloned the repo, I would ensure that the completedBoostsNumber in the questCategories.tsx file returns the right value by filtering the completedBoosts properly. I would test it to ensure that it works properly, while preserving the UI.

I estimate this would take a few hours to complete.

**Comment by ooochoche** [comment]
@revengexd GM, I have reviewed the issue, and it is something I can assist with.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a strong background in software development and user experience design, which enables me to identify and resolve issues effectively. My experience with similar projects has provided me with a solid understanding of both frontend and backend development, allowing me to implement comprehensive solutions. 

### How I plan on tackling this issue
To address the Boost quest display issue, I would first study the code to understand how the count is derived and displayed. 
I’d examine the function calculating completed quests and its interaction with the user interface.
I would use debugging tools to trace data flow and locate discrepancies.
Based on my findings, I would suggest changes to ensure the display shows either '3/13' or just '3' correctly.
After implementing the fix, I would run tests to confirm the display works as intended across scenarios.

**Comment by martinvibes** [comment]
Hello @revengexd I would love to take up on this issue

**Comment by fricoben** [comment]
I think the 13/13 is good here cause it means you made all the boosted quests, I agree the wording can be changed tho so I think we can keep it like this except if the connected user did all the quest (so it means except if `done_quest/total_boosted_quest=1`. 

In this case, you can show: `All quests were done`

I assigned @Akshola00 , for the others there will be a lot of new issue coming for the OD hack

**Comment by Akshola00** [comment]
@fricoben thanks for the opportunity 
will start work right away
