### ISSUE TITLE
Fix correct option

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#893]
In `components/admin/taskSteps/quizStep.tsx` around line 230, the admin can select the correct option for the quiz.
The API expects a number between 0 and 3: the first option is 0, the second is 1, the third is 2, and, finally, the fourth option is 3. But we still show options from 1 to 4 as it's better for users that aren't dev. The problem is that we currently return to the API a number between 1 and 4 instead of 0 and 3. Please simply update it to return a number between 0 and 3 while still showing a number between 1 and 4.

**Comment by ooochoche** [comment]
@Marchand-Nicolas can I work on this?

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a strong background in front-end development, particularly in working with TypeScript and React

### How I plan on tackling this issue
I would approach this issue with the following steps:
I would update the function handling the option selection. Specifically, when the admin selects an option (1-4), I would subtract 1 before sending the value to the API, converting it to the 0-3 range. This ensures the correct format for the API while keeping the display user-friendly. The UI would still show options as 1 to 4, but the underlying data sent to the API would be properly adjusted.

**Comment by snehaa-eth** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

I specialize in full-stack development using React, Node.js, and TypeScript. My experience building user-friendly interfaces and integrating APIs will help deliver efficient, scalable solutions to enhance your project’s functionality and user experience.

**Comment by AbrahamTolu** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a background in front-end development with a focus on user experience and UI design

### How I plan on tackling this issue
To address the problem, I would:

Identify the Selection Logic: 
Locate the part of the code where the selected option is processed (around line 230).
Adjust the Mapping: 
Modify the code to subtract 1 from the selected value before sending it to the API. This way, options 1-4 will correctly map to 0-3.
Test the Changes:
 Ensure that the display remains unchanged for users, while the API receives the correct values.
Review and Refactor:
 Confirm that the change does not impact other parts of the component and refactor if necessary for clarity.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Full stack Blockchain developer with a solid background in React, TypeScript, and frontend development .

### How I plan on tackling this issue
Find the logic that sends the selected option to the API.

Adjust the Returned Value.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.


### How I plan on tackling this issue

To tackle this problem, I would implement a seamless solution that maintains a user-friendly experience while ensuring the API receives the correct data format. My approach would involve adjusting the value just before sending it to the API, specifically by subtracting 1 from the selected option. This way, the admin still sees options labeled 1 through 4, making the interface intuitive, but the underlying logic sends values between 0 and 3 as required by the API.

Additionally, I would ensure this change is clean, well-documented, and fully tested to prevent any disruption in the current functionality. My focus would be on minimizing any impact on the user interface while ensuring the backend receives exactly what it needs. This solution not only fixes the issue but also improves the robustness of the code by ensuring the API interaction is correct. Given my attention to detail and commitment to maintaining both code quality and user experience, I’m confident I can implement this fix efficiently and without complications.

**Comment by JosueBrenes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

### How I plan on tackling this issue
### Update API Submission Logic:

I will modify the logic for submitting the selected option in the quizStep.tsx component. The selected option will be reduced by 1 before sending it to the API, ensuring the values are in the range 0 to 3. Here’s the updated code:

```tsx
const handleSubmit = () => {
  const apiOption = selectedOption - 1;
  sendToApi(apiOption);
};
```
###Maintain User-Friendly Display:

I will ensure that the options displayed to the admin are still between 1 and 4 to keep the interface intuitive. This will remain unchanged:

```tsx
<div>
  <label>Option 1</label>
  <input type="radio" name="quizOption" value={1} onChange={handleOptionChange} />
  <label>Option 2</label>
  <input type="radio" name="quizOption" value={2} onChange={handleOptionChange} />
  <label>Option 3</label>
  <input type="radio" name="quizOption" value={3} onChange={handleOptionChange} />
  <label>Option 4</label>
  <input type="radio" name="quizOption" value={4} onChange={handleOptionChange} />
</div>
```

### Ensure Correct State Update:
I will ensure that when the admin selects an option (from 1 to 4), the state is updated correctly:

```tsx
const handleOptionChange = (e) => {
  setSelectedOption(Number(e.target.value));
};
```

**Comment by gadyrcdz** [comment]
Hello, @Marchand-Nicolas, if this issue is still available I'd like to take it

**Comment by GradleD** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Full stack Web Developer with over 4+ years of experience

### How I plan on tackling this issue
Steps:
Update the handleCorrectAnswer function:

Subtract 1 from the selected option before storing it in correct_answers.
Update the Dropdown component:

When showing the correct answer in the dropdown, add 1 to map the 0-based API value back to a user-friendly 1-based format.

import React, { FunctionComponent, useCallback } from "react";
import TextInput from "../textInput";
import { QuizQuestionDefaultInput } from "@constants/admin";
import styles from "@styles/admin.module.css";
import Typography from "@components/UI/typography/typography";
import { TEXT_TYPE } from "@constants/typography";
import InputCard from "../inputCard";
import Dropdown from "@components/UI/dropdown";
import { SelectChangeEvent } from "@mui/material";

type QuizStepProps = {
  handleTasksInputChange: (
    e: React.ChangeEvent<HTMLInputElement>,
    index: number
  ) => void;
  step: StepMap;
  index: number;
  steps: StepMap[];
  setSteps: React.Dispatch<React.SetStateAction<StepMap[]>>;
};

const QuizStep: FunctionComponent<QuizStepProps> = ({
  handleTasksInputChange,
  step,
  index,
  steps,
  setSteps,
}) => {
  const handleQuestionChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>, questionIndex: number) => {
      const updatedSteps = steps.map((step, i) => {
        if (i === index && step.type === "Quiz") {
          const updatedQuestions = step.data.questions.map(
            (questionObj: typeof QuizQuestionDefaultInput, qIndex: number) => {
              if (qIndex === questionIndex) {
                return {
                  ...questionObj,
                  question: e.target.value,
                };
              }
              return questionObj;
            }
          );

          return {
            ...step,
            data: {
              ...step.data,
              questions: updatedQuestions,
            },
          };
        }
        return step;
      });

      setSteps(updatedSteps);
    },
    [steps, index, setSteps]
  );

  const handleOptionChange = useCallback(
    (
      e: React.ChangeEvent<HTMLInputElement>,
      optionIndex: number,
      questionIndex: number
    ) => {
      const updatedSteps = steps.map((step, i) => {
        if (i === index && step.type === "Quiz") {
          const updatedQuestions = step.data.questions.map(
            (questionObj: typeof QuizQuestionDefaultInput, qIndex: number) => {
              if (qIndex === questionIndex) {
                const updatedOptions = questionObj.options.map(
                  (option, oIndex) => {
                    if (oIndex === optionIndex) {
                      return e.target.value;
                    }
                    return option;
                  }
                );
                return {
                  ...questionObj,
                  options: updatedOptions,
                };
              }
              return questionObj;
            }
          );

          return {
            ...step,
            data: {
              ...step.data,
              questions: updatedQuestions,
            },
          };
        }
        return step;
      });

      setSteps(updatedSteps);
    },
    [steps, index, setSteps]
  );

  const handleCorrectAnswer = useCallback(
    (optionIndex: number, questionIndex: number) => {
      const updatedSteps = steps.map((step, i) => {
        if (i === index && step.type === "Quiz") {
          const updatedQuestions = step.data.questions.map(
            (questionObj: typeof QuizQuestionDefaultInput, qIndex: number) => {
              if (qIndex === questionIndex) {
                return {
                  ...questionObj,
                  correct_answers: [optionIndex - 1], // Subtract 1 to map to API
                };
              }
              return questionObj;
            }
          );

          return {
            ...step,
            data: {
              ...step.data,
              questions: updatedQuestions,
            },
          };
        }
        return step;
      });
      setSteps(updatedSteps);
    },
    [steps, index, setSteps]
  );

  const handleAddQuestion = useCallback(() => {
    const updatedSteps = steps.map((step, i) => {
      if (i === index && step.type === "Quiz") {
        return {
          ...step,
          data: {
            ...step.data,
            questions: [...step.data.questions, QuizQuestionDefaultInput],
          },
        };
      }
      return step;
    });

    setSteps(updatedSteps);
  }, [steps, index, setSteps]);

  return (
    <div className="flex flex-col gap-8 pt-2">
      {/* Rest of the component remains the same */}
      <div className="flex flex-col gap-8">
        {step.data.questions?.map(
          (
            eachQuestion: typeof QuizQuestionDefaultInput,
            questionIndex: number
          ) => (
            <InputCard key={"questionCategory-" + questionIndex}>
              {/* Question input */}
              <div className="flex flex-col gap-1">
                <TextInput
                  onChange={(e) => handleQuestionChange(e, questionIndex)}
                  value={eachQuestion.question}
                  name="question"
                  label={`Describe your question`}
                  placeholder={`Question ${questionIndex + 1}`}
                />
                <Typography type={TEXT_TYPE.BODY_MICRO} color="textGray">
                  Write the question&apos;s description.
                </Typography>
              </div>

              {/* Options and correct answer */}
              <div className="flex flex-col gap-1">
                <Dropdown
                  value={
                    step.data.questions[questionIndex].correct_answers[0] + 1 // Add 1 to map back to user-friendly value
                  }
                  backgroundColor="#101012"
                  textColor="#fff"
                  handleChange={(event: SelectChangeEvent) => {
                    handleCorrectAnswer(
                      parseInt(event.target.value),
                      questionIndex
                    );
                  }}
                  options={[
                    { value: "1", label: "1" },
                    { value: "2", label: "2" },
                    { value: "3", label: "3" },
                    { value: "4", label: "4" },
                  ]}
                />
                <Typography type={TEXT_TYPE.BODY_MICRO} color="textGray">
                  Specify the correct answer to the question.
                </Typography>
              </div>
            </InputCard>
          )
        )}
        {/* Add question */}
        <div
          onClick={handleAddQuestion}
          className={`${styles.addQuestion} modified-cursor-pointer`}
        >
          + Add question
        </div>
      </div>
    </div>
  );
};

export default QuizStep;
handleCorrectAnswer function:

The selected optionIndex is now adjusted by subtracting 1 before storing it in correct_answers. This ensures that the API receives 0 to 3 as expected.
Dropdown value:

The correct answer displayed in the Dropdown is adjusted by adding 1 to the stored value. This way, users still see options numbered from 1 to 4, but internally, the correct answer is stored and sent as a 0-based index.

**Comment by Villarley** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am Santiago Villarreal Arley, a passionate software developer with a growing interest in Web3 technologies. Over the past few months, I've had the opportunity to work on innovative projects, such as BuildMyEvent, an open-source initiative that leverages blockchain and decentralized systems. I thrive on problem-solving and enjoy the challenge of integrating cutting-edge solutions into real-world applications. My goal is to contribute to the Web3 ecosystem by staying ahead of emerging trends, learning continuously, and developing projects that push the boundaries of decentralized technologies.



### How I plan on tackling this issue
In the quiz component, users currently see options labeled 1 to 4, which is user-friendly. However, the API expects different values: 0 for the first option, 1 for the second, 2 for the third, and 3 for the fourth.

To solve this, I would keep the interface as it is, showing 1 through 4 to the users. But when sending the selected option to the API, I would subtract 1 from the user’s choice before submitting the value.

For example, if a user selects option 1, the system will send 0 to the API, and if they choose option 2, it will send 1, and so on. This approach ensures that the API receives the correct values without affecting the user experience. I look forward to contributing to the project by implementing this solution!

**Comment by emmz3230** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

contributing got me my first github badge

### How I plan on tackling this issue
1 i will understand the codebase as listed above 
2. i will update it by write the function to add  1 to the counting of the figure instead of writing it in javascript computer language

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by mariocodecr** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
When sending the selected option to the API, adjust the value by subtracting 1 from the selected option (which is between 1 and 4) to return the correct value between 0 and 3. Ensure that the UI still displays options 1 through 4 to the admin, but map those selections internally to 0 through 3 before sending the data to the API. Finally, test to ensure the correct values are being sent to the API and the user experience remains unchanged.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience in front-end development with React.js and TypeScript. I build user-friendly interfaces and ensure the correct data is sent to backend APIs. I know how to make the user display different from the data sent to the backend, creating an intuitive interface without losing accuracy.

### How I plan on tackling this issue
To solve the current issue, I will check the code around line 230 in the quizStep.tsx file where the admin selects an option. I will keep the options for the admin as 1 to 4, but subtract 1 from the selected value before sending it to the API. This way, a value between 0 and 3 is sent. I'll adjust the code for form submission and test the updated component to ensure the options remain labeled 1 to 4 while sending the correct values (0 to 3) to the API. This will keep the user experience smooth and the data accurate.

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in the field of blockchain and web development. I'm excited about the opportunity to contribute to this issue regarding the quiz component.

### How I plan on tackling this issue
My approach of tackling this issue:

I will locate the relevant code in components/admin/taskSteps/quizStep.tsx . Understanding how the current logic handles the selection of quiz options will be my first step.
I will locate the relevant code in components/admin/taskSteps/quizStep.tsx around line 230. Understanding how the current logic handles the selection of quiz options will be my first step.
After making the necessary adjustments, I will thoroughly test the functionality to ensure that the correct option is sent to the API while maintaining the user-friendly display of options.

**Comment by chibokaxavier** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I’m Chiboka Xavier, a full-stack developer with over 4 years of experience building applications that not only work well but feels great to use. I’m passionate about turning creative UI/UX designs into real, responsive user interfaces with tools like Next.js, React, and Tailwind CSS. On the backend, I use Express and MongoDB to make sure everything runs smoothly behind the scenes. I love exploring new technologies and finding ways to create seamless, enjoyable experiences for users, blending both the frontend and backend to bring ideas to life.

### How I plan on tackling this issue
To fix the  issue for the endpoint `components/admin/taskSteps/quizStep.tsx` around line 230. I’ll still  keep the options displayed as 1 to 4 for the admins since that’s more user-friendly and easier to work with, but when they select an option, I’ll change the value that gets sent to the API. How ill do that excavftly  is , ill subtract 1 from the selected option so that option 1 sends 0 to the API, option 2 sends 1, and so on, up to option 4 sending 3. This way, we keep it easy for users while making sure the API gets the right values.

**Comment by fricoben** [comment]
assigned to @Snehagupta1907

**Comment by fricoben** [comment]
> assigned to @Snehagupta1907

actually I assigned to @GradleD and @Snehagupta1907 I gave you another issue
