### ISSUE TITLE
Add Opus protocol infos

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#897]
## Description 

1. Add opus protocol to `defi.ts` linkMap const

```ts
  opus: {
    Strategies: "https://app.opus.money/",
  },
  ```
  
 2. Create an `/opus/opus.ico` folder, add this image and make it a `.ico` file (just rename it from .png to .ico)

![opus](https://github.com/user-attachments/assets/4ec46915-9af5-4ac4-ba4e-257a3b0b2995)

**Comment by 0xOlivanode** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

I’ve spent the past three years specializing in web3 development with a focus on smart contract programming, particularly in Solidity and Cairo. This hands-on experience has allowed me to build and deploy decentralized applications (dApps) on Ethereum and StarkNet. I can leverage this expertise to integrate the Opus protocol into the DeFi space by ensuring smooth contract development, protocol optimization, and cross-platform compatibility. My technical background, coupled with open-source contributions, has equipped me to effectively solve issues around DeFi infrastructure and deliver seamless user experiences.

**Comment by sajalbnl** [comment]
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.
@fricoben i want to work on this

**Comment by JosueBrenes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged

Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

### How I plan on tackling this issue
### Proposed solution:

1. **Add Opus protocol in `defi.ts`:**

   Open the `defi.ts` file and add the following code to the `linkMap` object to include the Opus protocol:

   ```tsx
   opus: {
       Strategies: "https://app.opus.money/",
   },
   
   Create the /opus/opus.ico folder and add the image:

### Create a new folder called opus in the appropriate location.

Rename the provided image file (currently in .png format) to .ico.

If renaming the file doesn’t properly convert the image to an icon, you can use an online tool like Convertio to do the conversion.

Once you have the .ico file, save it in the newly created folder: /opus/opus.ico.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am deeply interested in Web3, and currently, I’m working as a Frontend Developer Intern at a Web2 company, where I’m primarily using Next.js. I am also a member of Dojo Coding, the premier Web3 community in LATAM, and I’m currently working on a project for the Buildathon (hackathon) from Base LATAM. I’m eager to gain more experience and would love for this to be my first issue to tackle. It would be a great opportunity for me to contribute, and I’d really appreciate the chance to work on it!

### How I plan on tackling this issue

To efficiently resolve this issue, I would first update the `defi.ts` file to seamlessly integrate the Opus protocol into the `linkMap` constant. After that, I would create a dedicated `opus` folder and correctly position the Opus logo within it. To meet the file format requirements, I would ensure the image is converted to `.ico` format, either by renaming it or using a specialized tool to guarantee proper conversion. This approach will maintain the integrity of the project while ensuring compliance with all specifications. 

I have the experience and attention to detail needed to complete this task accurately and promptly. You can be confident that I will deliver a high-quality solution.   @fricoben, I would love the opportunity to contribute to this amazing project by working on this issue.

**Comment by fricoben** [comment]
assigned @KevinLatino
