### ISSUE TITLE
Add keplr wallet

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#901]
## Description 

Add keplr wallet following the method we used [here](https://github.com/lfglabs-dev/app.starknet.id/pull/899). 

You'll need to add the keplr wallet logo and info as in the above PR and test that the wallet works well.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I want to work on this 
 
ETA 1 Day

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I bring significant experience in developing decentralized applications

### How I plan on tackling this issue
install the required libraries to integrate Keplr into the frontend.

Frontend Wallet Integration

Create a wallet connection

Test wallet integration

**Comment by raizo07** [comment]
Hey @fricoben can I be assigned to work on this

ETA: One day

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. 

### How I plan on tackling this issue
I will add the Keplr wallet according to the description in 2-3 days

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. Looking forward to collaborating!

### How I plan on tackling this issue
To tackle this task, I will follow the method used in the referenced PR to integrate the Keplr wallet into the system. I will:

Add the Keplr wallet logo and relevant information, ensuring consistency with the style and approach used in the PR (https://github.com/lfglabs-dev/app.starknet.id/pull/899).
Update the wallet integration logic to include Keplr, ensuring it works seamlessly alongside any existing wallets.
Test the Keplr wallet thoroughly to confirm that it connects properly, handles transactions, and functions as expected.
This approach will ensure the integration is smooth and reliable while following the established pattern for wallet additions.

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have worked with many similar projects in the past

### How I plan on tackling this issue
install all the required dependencies and then integrate Keplr, then test it.
I'll need a day or lesser for this.

**Comment by fricoben** [comment]
Assigned @anonfedora !
