### ISSUE TITLE
Implement Portfolio API for wallet amount

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#903]
Replace the static wallet amount introduced here:
- https://github.com/lfglabs-dev/starknet.quest/issues/877

By the actual wallet amount using the Argent portfolio API.

I suggest you to check in the network tab of the console what call they do on their official website: https://portfolio.argent.xyz/overview/0x05f1f8de723d8117daa26ec24320d0eacabc53a3d642acb0880846486e73283a.
Or how other contributors are doing in the ongoing issues (https://github.com/lfglabs-dev/starknet.quest/issues/880 & https://github.com/lfglabs-dev/starknet.quest/issues/879)

**Comment by Marchand-Nicolas** [comment]
I will assign someone after the 3 mentioned issues are merged

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello @Marchand-Nicolas, I would love to handle this,

### How I plan on tackling this issue

- Get Argent portfolio api from the network tab of the provided portfolio link
- write a hook for the portofolio balance
- replace the dummy from the design to the value coming from the api 

ETA: 4hrs

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

### How I plan on tackling this issue
Replace the static wallet amount in the code with data from the Argent portfolio API. Check the network tab on Argent’s website to see the API call they use. I'll work diligently until the desired outcome is achieved, ensuring the implementation works seamlessly and integrates with ongoing contributions.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity, participated in ODHacks since 7.0 as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. Use the network tab in the browser developer tools on argents portfolio website to identify the API call that fetches wallet details.
2. Implement the argent portfolio API using the identified API endpoint to fetch dynamic wallet data
3. Check related GitHub issues (#880 and #879) for similar solutions from other contributors
4. Replace the static wallet amount with the real-time data from the API response

**Comment by BrunoAmbricca** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey guys, Im a software developer with 4+ years of experience and currently working on a gaming app that implements the argent wallet

### How I plan on tackling this issue
I would check the docs provided about the argent API and check the necessary information required to get the wallet amount

**Comment by caxtonacollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am applying to this issue  via: https://app.onlydust.com/p/starknet-quest

I am a fullstack developer with a strong background in integrating APIs and designing responsive UI components based on Figma designs. I have experience in working with cryptocurrency wallets and displaying real-time wallet balances by integrating financial APIs. My skills in React and JavaScript allow me to effectively manage currency conversions and data handling.

### How I plan on tackling this issue
Design Review: Analyze the Figma design to identify where to display the USD conversion of the wallet balance.
API Integration: Use a crypto API (e.g., CoinGecko) to fetch the current exchange rate of the wallet's token to USD.
Conversion Logic: Calculate the wallet balance in USD by multiplying the wallet's token amount with the fetched rate.
UI Update: Display the USD balance in alignment with the design, ensuring consistency in style.
Testing: Verify the conversion updates dynamically by simulating different balances and checking responsiveness across devices.

**Comment by mimisavage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.



### How I plan on tackling this issue
To tackle this task, I will first review the existing implementation of the static wallet amount and identify where the change needs to be made. Then, I will explore the Argent portfolio API to understand how to integrate it for dynamically fetching wallet amounts. I will check the network tab in the console of the Argent portfolio website to observe the API calls made and replicate that process in my code. Additionally, I will examine contributions made by others in the ongoing issues on GitHub to gather insights and best practices for this integration. After implementing the API call, I will test the functionality to ensure that the wallet amount updates correctly based on the real-time data retrieved from the Argent portfolio API.

**Comment by ooochoche** [comment]
Can I take this issue? I've read through what is needed, and I can implement portfolio API for the wallet amount

**Comment by blessingbytes** [comment]
I'd like to take this issue

**Comment by Benjtalkshow** [comment]
Hi @Marchand-Nicolas,
Give me the chance to work on this task.
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.


To implement the Portfolio API for wallet amount, the goal is to replace the current static wallet amount with dynamic data retrieved from the Argent Portfolio API. Here's the approach I would take to tackle this:

1. The first step is to analyze the network activity on Argent's official website to determine the API call responsible for retrieving the wallet balance. This can be done by inspecting the network tab of the browser's developer tools while visiting the URL you provided. By doing so, I will identify the endpoint, request parameters, and the structure of the response that contains the wallet balance information.

2. Once the API call structure is understood, the next step is to integrate it into our codebase. This involves making an HTTP request to the Argent Portfolio API using the wallet address of the user. The returned data will include the wallet's balance, portfolio value, and possibly other relevant details. I will extract the wallet amount from the response and use it to dynamically display the user's balance.

3. The static wallet amount currently implemented will be replaced with the data obtained from the API. This will involve updating the relevant component responsible for displaying the wallet amount, ensuring that the value is dynamically fetched and rendered in real-time, based on the API response.

Finally, I will implement error handling to manage failed requests and edge cases. After integrating the API, testing will be conducted to ensure accurate data retrieval and proper display of the wallet balance. Thanks. My ETA is 24hrs.

**Comment by jaiminRaiyani** [comment]
Can I take this issue?

**Comment by aniruddhaaps** [comment]
I'm a typescript dev. A new-comer here, willing to and ready to contribute to solve the issue.

**Comment by pheobeayo** [comment]
I’d love to work on this task.
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

**Comment by ShantelPeters** [comment]
Can I attempt this issue? 

I will replace the static wallet amount in the project with real-time data from the Argent Portfolio API. This will involve making an API call to retrieve the wallet balance for the specified address. I will analyze the network requests in the console of the Argent portfolio website to understand the request structure and parameters required. 
Following that, I'll implement the API call in the appropriate component, ensuring the wallet amount updates dynamically in the UI. I'll also handle error responses gracefully and ensure the application maintains performance and user experience during data fetching. 
Finally, I will test the integration thoroughly to confirm accurate data display and responsiveness.

**Comment by DotworldX** [comment]
I’m interested in this one.

**Comment by reetbatra** [comment]
Can I try solving this issue? HER DAO

**Comment by wheval** [comment]
Hello, I'd like to take this issue. I would ensure to follow the Argent official website to integrate the portfolio Api and replace the static amount correctly.
Thanks.

ETA is 1 day.

**Comment by ooochoche** [comment]
@Marchand-Nicolas Please I would love to work on this issue

**Comment by OWK50GA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

I am Wilfrid Okorie, a seasoned React and Next.js developer, with experience with Cairo for Starknet Smart contracts, and frontend Integration of Smart contracts using Next.js, and I would like to work on this issue.

I estimate this issue takes me 1 day

**Here's how I plan to take on this issue:**

- First of all, I will examine the existing data flow i.e. the method that displays the current static wallet amount, checking how and where the data is managed.
- Next, I will use the network tab on Argent's official website to inspect the relevant API calls for obtaining wallet amount.
- I will then set it up to fetch the wallet balance dynamically, handling response formats and errors, and making sure to stick to the current convention, with only the static wallet balance replaced.
- I will use loading states indicators to ensure it is non-blocking. After this, I will test different cases to make sure the call works, and edge cases do not break the user interface.
- In all of this, I will make sure my code is clean and well commented, for the sake of future contributors.

I will also welcome any feedback for something to be changed or improved.

It will be a privilege to work on this issue

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

# My background and how it can be leveraged

Hi, I'm Alvaro Lazarus a Blockchain developer and new member of Dojo Coding, I have experience with TypeScript and JavaScript which makes me confident that I can complete this issue. Also it seems like a fun one to tackle.

# How I plan on tackling this issue

To address this issue, I’ll start by using the Network tab in the browser’s developer tools on Argent's portfolio website to locate the API call that retrieves wallet details. With the API endpoint identified, I’ll integrate the Argent portfolio API, enabling the application to fetch dynamic wallet data. I’ll also reference related GitHub issues, such as #880 and #879, to examine similar solutions contributed by others. Finally, I’ll replace the static wallet amount with data from the API response, ensuring that the wallet information remains accurate and up to date.

Thank you for your consideration

**Comment by soomtochukwu** [comment]
May I handle this issue?

**Comment by deeseeker** [comment]
I’d love to work on this task.

**Comment by funkycadet** [comment]
I'd love to handle this issue!

**Comment by jedstroke** [comment]
May I try my hand at this?
ETA: 80 hours

**Comment by PoulavBhowmick03** [comment]
I’d like to help with this. I am a contributor to the Starknet Quest repositories, I am also a Starknet wolf and I can solve this issue

I will examine the network requests to understand how they retrieve wallet balance. then i will replace the static wallet amount with dynamic data from the API

### ETA - 2 days

**Comment by martinvibes** [comment]
Ihey @fricoben Can I contribute to this one?

**Comment by Ugo-X** [comment]
Would love to tackle this!
please can i be assigned to this?

**Comment by ikemHood** [comment]
Hey @Marchand-Nicolas , I am still available to take this

**Comment by Aditya-040** [comment]
Can I be assigned to this?

**Comment by Akshola00** [comment]
Is this issue still available?

**Comment by bruhhgnik** [comment]
i am a newbie contributor, i have experience in python, solidity and JS, can i work on this?

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
software engineering background, backend & smart contract dev looking to make first contribution on this project

How I plan on tackling this issue
1. I’ll go to Argent Portfolio and use the DevTools > Network tab to inspect the request used to retrieve wallet balances.
2. Note the URL endpoint, any necessary headers, and the JSON response structure to correctly replicate the request in our code.
3. Using axios or fetch, I’ll create a function that fetches the wallet balance for any given address
4. Replace Static Wallet Balance with Dynamic Data

work on feedback & recommendations. can deliver within a day upon assignment

**Comment by sigmadawg** [comment]
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by Michaelkingsdev** [comment]
I'd love to work on this!

**Comment by Kingsuite** [comment]
I’d love to work on this task.

**Comment by mimisavage** [comment]
I would love to take this up. I like 🍒

**Comment by Kaminar-i** [comment]
Would there be a chance for me to take on this issue?

**Comment by snehaa-eth** [comment]
can i work on this issue?

**Comment by SoarinSkySagar** [comment]
May I try my hand at this? I've worked on starknet quest before so I can work with this.
ETA: 2 Days

**Comment by Marchand-Nicolas** [comment]
https://github.com/lfglabs-dev/starknet.quest/pull/925
