### ISSUE TITLE
Implement claim reward button

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#913]
In the dashboard e.g. `/0x05f1f8de723d8117daa26ec24320d0eacabc53a3d642acb0880846486e73283a`,
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/5b9a2e62-fc6e-4348-a36b-d286d245717b">
we just added new defi category, with a "Claim all reward" button. It currently does nothing. You simply have to make it do the same thing as this one in `/discover/defi`
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/009fbf8f-17de-451c-bca2-cbfb41f3169f">

**Comment by ooochoche** [comment]
@Marchand-Nicolas I can work on this

**Comment by anonfedora** [comment]
I can handle this issue, assign me.

**Comment by ikemHood** [comment]
Hello @Marchand-Nicolas, can I jump on this,

I would look that what is done in `discover/defi` and replicate that,

ETA: 4Hrs

**Comment by suhas-sensei** [comment]
would be happy to contribute again

**Comment by Bosun-Josh121** [comment]
I'd love to give this a go. would check linked implementation and deliver soon

**Comment by 0xBinayak** [comment]
I would like to work on this issue "Claim all reward" button in the new DeFi category on the dashboard (/0x05f1f8...) needs to function like the one in /discover/defi. I have experience working with React and API integrations (using Axios), and I can refactor and reuse the existing functionality from /discover/defi to implement this efficiently.

**Comment by Jemiiah** [comment]
I can work on this issue @Marchand-Nicolas @fricoben 
ETA : 24HRS

**Comment by tasneemtoolba** [comment]
Mind if I try this one?
my background
I'm a software engineer of 3 years of experience, recently shifted to web3 with H.E.R DAO, and would love to get the chance to do my first contribution!

**Comment by MrRoudyk** [comment]
I’m interested in this one.

**Comment by lombardini-jeremias** [comment]
Hello! I'm Jeremias, a software developer with nearly 2 years of experience in full-stack roles. Most of my work has been focused on implementing API integrations, creating data-driven queries, and building user-friendly UIs to present information effectively.

I'm now eager to transition into Web3 development and begin contributing to the ecosystem. Although I'm new to the space, I'm excited to make my first contribution and start building my Web3 profile ! 
I would love to be considered.

**Comment by lombardini-jeremias** [comment]
Hello! I'm Jeremias, a software developer with nearly 2 years of experience in full-stack roles. Most of my work has been focused on implementing API integrations, creating data-driven queries, and building user-friendly UIs to present information effectively.

I'm now eager to transition into Web3 development and begin contributing to the ecosystem. Although I'm new to the space, I'm excited to make my first contribution and start building my Web3 profile !
I would love to be considered.

**Comment by wheval** [comment]
Hi, @Marchand-Nicolas Can I tackle this one? I would ensure to replicate the same thing in the /discover/defi to the Claim All Reward button in the dashboard. Hope i get a chance at this. Thanks!
ETA is 1 day.

**Comment by Neurvinch** [comment]
Can I take this from here?

**Comment by aniruddhaaps** [comment]
I'm a Javascript dev, a new-comer here. Want to contribute to the problem and provide with a solution.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

To implement the "Claim Your Reward" button on the dashboard, I’ll adapt the existing claim functionality from `/discover/defi`. The current `ClaimModal` component for `discover/defi` handles Starknet.quest-based rewards claims by fetching data through `getRewards`, verifying the user’s wallet address, and executing claims with `useContractWrite`.

I will integrate a similar functionality on the dashboard page, linking it to the "Claim All Reward" button to initiate the same rewards-fetching and claiming process. This ensures the dashboard button performs identically to the DeFi claim feature, maintaining consistency in user experience and functionality. After integration, I will test the dashboard's claim feature to confirm its proper operation and alignment with `/discover/defi`.

My ETA is 24hrs.

**Comment by omsant02** [comment]
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer


For solving this issue as i can see the "claim all" button and it triggers the function "doClaimRewards" in the ClaimModal component, so the same thing i would be implementing in the dashboard page

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged

I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/

### How I plan on tackling this issue
To implement the "Claim all reward" button in the dashboard for the new DeFi category, I can replicate the existing reward-claiming logic from `/discover/defi`. This will involve reusing the reward function and adapting it to the dashboard's structure, ensuring it performs consistently with the current implementation. I’ll handle any necessary adjustments to error management and validation to ensure seamless functionality on the dashboard. Once integrated, I’ll conduct tests in the dashboard environment to confirm it matches the `/discover/defi` behavior and performs as expected.

@Marchand-Nicolas I would love to contribute to this amazing project! I hope you can give me the opportunity!

**Comment by omsant02** [comment]
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

For solving this issue as i can see the "claim all" button and it triggers the function "doClaimRewards" in the ClaimModal component, so the same thing i would be implementing in the dashboard page

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://www.onlydust.com/).

## My background and how it can be leveraged

Hi, I'm Alvaro Lazarus a new member of Dojo Coding, im relativley new to blockchain but I have worked extensively with TypeScript and JavaScript before which makes me confident that I can complete this issue.

## How I plan on tackling this issue

- Replicate the reward claiming logic from /discover/defi 
- Test the integration thoroughly in the dashboard environment to verify it matches the behavior and performance of /discover/defi.

Please consider 

ETA: 24 hrs

**Comment by BrunoAmbricca** [comment]
Hello, Im a software engineer with 4+ years of experience and I would like to contribute to this project

**Comment by Aditya-040** [comment]
Is it okay if I take this?

**Comment by vijay-kesanakurthi** [comment]
Can I be assigned to this? i'm new to this communit
