### ISSUE TITLE
Help with npm i in Readme 

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#916]
Update the npm i part of the readme to precise that to avoid any failure to resolve the dependency tree, the `--force` flag should be added: `npm i --force`

**Comment by aniruddhaaps** [comment]
i'd like to work on this, this is my first odhack and im on the lookout for some issues like these, would be grateful if assigned.

**Comment by suhas-sensei** [comment]
May I be assigned to this? Looking forward to contribute.

**Comment by raizo07** [comment]
@Marchand-Nicolas can I work on this? 

ETA: One hour

**Comment by martinvibes** [comment]
May I take this issue on?
kindly assign

**Comment by od-hunter** [comment]
Hi @Marchand-Nicolas , can I work on this please?

**Comment by lauchaves** [comment]
Hey 👋 I’m Lau from dojo coding, may I take this issue on?  I already set up this repo so I’ll document the step clearly :)

**Comment by akintewe** [comment]
I have experience in JavaScript and TypeScript development environments, I frequently deal with package management and dependency concerns. I appreciate the importance of having clear installation instructions, particularly for dependency resolution. For this documentation update, I would make clear, easy changes to the README.md that clarify why the --force parameter is required and what it does. I'd make sure that the installation section explicitly states this requirement while retaining a professional tone that helps consumers understand why they're utilising the force flag.

**Comment by tasneemtoolba** [comment]
Mind if I try this one? a new h.e.r dao member

**Comment by vitaliypopel** [comment]
Hey! I will help you with npm, had experience with Node and will do my best

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas, 
Can I take care of this issue?
My ETA is 5hrs. Thanks you

**Comment by tasneemtoolba** [comment]
@Marchand-Nicolas sorry I'm a bit new to the contribution, which branch should I branch out the new branch for the readme? the main(i.e testnet)? or I guess I can edit it directly in the main(i.e testnet) and create a PR for it?

**Comment by Marchand-Nicolas** [comment]
@tasneemtoolba Yes, you can fork the repo, create your own branch, and make a pull request from your branch to the testnet branch

**Comment by Marchand-Nicolas** [comment]
The way you created the PR is perfect, but you need to listen to the comments that the AI is providing automatically

**Comment by fricoben** [comment]
done
