### ISSUE TITLE
Render big numbers in a better way

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#927]
I tested our new dashboard with different wallets, big numbers are not displayed correctly on the `Portfolio by protocol usage`. 

`$230242.31` should be displayed like `$230,242.31`

<img width="164" alt="Capture d’écran 2024-11-07 à 10 55 23" src="https://github.com/user-attachments/assets/643e617e-bef2-4d53-b9b7-8a3536361886">

**Comment by ooochoche** [comment]
@fricoben I would love to work on this

**Comment by sajalbnl** [comment]
Can I tackle this one?

**Comment by wheval** [comment]
hello, @fricoben.

can i work on this?

ETA is 1 day.

**Comment by ShantelPeters** [comment]
Can I please be assigned to this issue @fricoben

**Comment by 0xdevcollins** [comment]
Could I grab this task?

ETA: 1hr

**Comment by wheval** [comment]
hello, @fricoben.

can i work on this? 

ETA is 1 day.

**Comment by jaiminRaiyani** [comment]
Is this issue still available?

**Comment by snehaa-eth** [comment]
Can I take care of this issue?I ahve worked on this repo before

**Comment by mimisavage** [comment]
@fricoben can i work on this?

**Comment by Benjtalkshow** [comment]
Hello @fricoben 
Give me the opportunity to tackle this issue.
ETA is 2hrs

**Comment by Michaelkingsdev** [comment]
This will be my first time contributing to this repo @fricoben .
I wanna take on this issue and deliver it in 1hr max.

**Comment by anonfedora** [comment]
May I take this issue on?

**Comment by GradleD** [comment]
I'd like to take this issue.

**Comment by Shaarps** [comment]
I’d love to work on this task.

**Comment by caxtonacollins** [comment]
Can I be assigned to this?
