### ISSUE TITLE
profile pic is never defined

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#928]
<img width="537" alt="Capture d’écran 2024-11-07 à 10 59 15" src="https://github.com/user-attachments/assets/7232c0e1-0e54-4f96-a21b-3480f4efb5bc">

On our new dashboard page, the avatar is never defined, we want it to be the same image we have on the connection button and the `Avatar.tsx` component. 

You can use 

```tsx
  const { data: profileData } = useStarkProfile({ address });
```

**Comment by ShantelPeters** [comment]
Hi @fricoben can I work on this issue please

**Comment by jaiminRaiyani** [comment]
Hi @fricoben i would love to tackle this issue

**Comment by GradleD** [comment]
Can I contribute to this one?

**Comment by wheval** [comment]
Hello, @fricoben.

I'm Wheval, a frontend developer.
Can i work on this? I would ensure the Avatar matches the same one on the connection button bg using the Stark profile of the user for consistency.
Thank you!.

ETA is 1 day.

**Comment by Michaelkingsdev** [comment]
This will be my first time contributing to this repo @fricoben .
I wanna take on this issue and deliver it in 2hr max.

**Comment by 0xdevcollins** [comment]
Hi @fricoben can I work on this issue please?

I have worked on this repo and will make a PR in 2hrs

**Comment by Benjtalkshow** [comment]
Hello @fricoben
Give me the opportunity to tackle this issue.
ETA is 2hrs

**Comment by anonfedora** [comment]
Can I start working on this?

**Comment by Shaarps** [comment]
Can I work on this, please?

**Comment by caxtonacollins** [comment]
i will love handle this issue, please assign me

**Comment by wheval** [comment]
Thank you, would make a pr soon!

**Comment by caxtonacollins** [comment]
yes sir i will
