### ISSUE TITLE
If bitget wallet is not installed, logo doesn't work

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#930]
If Bitget wallet is not installed, logo doesn't appear and we see `Bitget Wallet` Instead of `Install Bitget Wallet`

Please make the logo appear and change the messaging to `Install Bitget Wallet`

You can inspire yourself by what we did here https://github.com/lfglabs-dev/app.starknet.id/blob/c15caf3281e3a6916fc5e5922edc719097a2f04d/utils/connectorWrapper.ts#L143C1-L152C5

**Comment by ikemHood** [comment]
Hi @fricoben, Can I get this done

**Comment by 0xdevcollins** [comment]
Can I take this up?

**Comment by Shaarps** [comment]
Mind if I take this issue?

**Comment by jaiminRaiyani** [comment]
Can I start working on this?

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue?

**Comment by SudiptaPaul-31** [comment]
Can I get this issue assigned

**Comment by mimisavage** [comment]
Mind if I take this issue?

**Comment by caxtonacollins** [comment]
I'd love to give this a go. am ready to put in the work

**Comment by Benjtalkshow** [comment]
Hello @fricoben 
I would love to work on this issue. 
To implement this, I will check if "Bitget Wallet" is installed using the `available()` method in the referenced file. If not, I will display a message such as "Install Bitget Wallet" and show its logo. I will use a placeholder if the wallet isn’t installed, similar to how other connectors are handled in the existing code.
I will deliver in 5hrs. 
Thanks

**Comment by godekina** [comment]
Can I tackle this one?

**Comment by Michaelkingsdev** [comment]
@fricoben
Can this task be assigned to me please?

**Comment by ooochoche** [comment]
Please, I would love to work on this.

**Comment by Aditya-040** [comment]
Can I contribute to this one? I can solve this issue.

**Comment by GideonBature** [comment]
I'd like to take this issue. Can you please assign me this issue?

**Comment by godekina** [comment]
@fricoben please can I chat you privately? I need further clarification on tackling this issue.

**Comment by fricoben** [comment]
done
