### ISSUE TITLE
Change adress of dashboard when changing wallets

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#933]
https://www.loom.com/share/041aca94f3cc4a7b9bc996a68d38a6b8

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @fricoben

**Comment by 0xdevcollins** [comment]
Could I grab this task? I will make sure the component you mentioned on the video get updated with with the correct  detail when  the wallet changes

**Comment by jaiminRaiyani** [comment]
Can I jump on this task?

**Comment by Shaarps** [comment]
Can I contribute to this one?

**Comment by wheval** [comment]
Hello, @fricoben.

I'm Wheval, a frontend developer.
I can resolve this issue perfectly.

ETA is 1 day.

**Comment by snehaa-eth** [comment]
Is this issue still available?

**Comment by sajalbnl** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by Michaelkingsdev** [comment]
Hello @fricoben 
I am a newbie contributor. Can i get my hands on this task?
To achieve automatic page updates when switching wallets, I will write a logic to detect wallet address changes via `window.ethereum.on('accountsChanged')`. Update the page content dynamically based on the new address without reloading the page. Optionally, persist the wallet address using localStorage for continuity.
Thanks
ETA: 24hrs

**Comment by caxtonacollins** [comment]
Can I contribute to this one?

**Comment by Benjtalkshow** [comment]
@fricoben 
I can easily fix this issue. I know my way around it. My ETA is 10hrs. Thanks
