### ISSUE TITLE
Add skeleton for porfolio value sum

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#936]
Here we have the sum of my portfolio value that takes more time to charge than the rest which gives me a strange buggy impression, to get rid of this buggy impression I propose you add a skeleton to this section (including the privacy Icon). 

You can use `loading.tsx` to create this skeleton, please be sure to pull origin because of this change https://github.com/lfglabs-dev/starknet.quest/pull/935

Before 
<img width="456" alt="Capture d’écran 2024-11-07 à 11 38 27" src="https://github.com/user-attachments/assets/d7c51602-460c-47a5-8aaa-bc7a8d0c1716">

 After
<img width="434" alt="Capture d’écran 2024-11-07 à 11 38 34" src="https://github.com/user-attachments/assets/0a1f0bac-f751-4c14-82bd-5bd3f104bb60">

**Comment by GradleD** [comment]
Let me Work on this

**Comment by 0xdevcollins** [comment]
Is it okay if I take this?

**Comment by ShantelPeters** [comment]
Please I will like to work on this issue. Kindly assign

**Comment by mimisavage** [comment]
May I try my hand at this?

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by ooochoche** [comment]
Can I contribute to this?

**Comment by godspowerufot** [comment]
May I take care of this?
I am new on this platform and would love to make this my first contribution to this project I am really good at typescript , and js
Thank you

**Comment by Aditya-040** [comment]
Can I take this from here? I am a full-stack developer and have experience in typescript and javascript. I can solve this issue

**Comment by GideonBature** [comment]
I’m interested in this one. Can you please assign me this project?

**Comment by Benjtalkshow** [comment]
Can I work on this one? @fricoben

**Comment by Michaelkingsdev** [comment]
Can I work on this task ?

**Comment by fricoben** [comment]
Assigned to @GradleD 

Please be sure to understand the issue before raising a PR (your last PR I closed wasn't what I asked).

**Comment by GradleD** [comment]
@fricoben  Can you check it again?

**Comment by Akshola00** [comment]
Can I handle this task?

**Comment by 0xdevcollins** [comment]
I can handle this task @fricoben

**Comment by ShantelPeters** [comment]
> Please I will like to work on this issue. Kindly assign

Please can I be assigned to this issue @fricoben

**Comment by godspowerufot** [comment]
I hope to be able to solve this issue in the most simplified way

**Comment by vestor-dev** [comment]
Hello @fricoben please I would love to work on this issue 
I'm new here and would like to contribute 
Kindly assign

**Comment by Yunusabdul38** [comment]
I'd like to handle this task.

**Comment by fricoben** [comment]
> I'd like to handle this task.

I assigned you
