### ISSUE TITLE
Rename `Earn` to `deFi` on navbar

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#952]
## Description 📹

We need to update the navigation bar to rename the 'earn' button to 'DeFi' to better align with our terminology and content. This change should be reflected across all instances where this navigation item appears.

## Proposed Actions 🛠️

1. **Fork and Create Branch**:  
``bash
git checkout -b fix-[issue-number]
``

2. **Implementation Steps**:
   - [ ] Update the navigation item text from 'earn' to 'DeFi' in the navbar component
   - [ ] Verify that the href path remains unchanged
   - [ ] Check for any mobile/responsive menu instances of this text
   - [ ] Verify that the styling remains consistent with the new text
   - [ ] Test that the navigation still works correctly
   - [ ] Check for any hardcoded references to 'earn' in related components

3. **Run Tests and Commit Changes**:  
``bash
git commit -m "Fix: Rename earn to DeFi in navigation bar"
``

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by raizo07** [comment]
@fricoben can I work on this

**Comment by Yunusabdul38** [comment]
@fricoben  I'd like to work on this issue to implement the necessary changes and also make sure it is responsive

**Comment by 0xshubhs** [comment]
@fricoben Assign me this issue

**Comment by omsant02** [comment]
i would like to take this issue @fricoben 

i am a new contributor to this repo and want to start my contribution journey with starknet.quest, also i have knowledge of nextjs and page router
ETA : 20 mins
Thank you

**Comment by trashcancries** [comment]
gm @fricoben, I'm new to this repo and I have understood the task and read all guidelines. Would love to start working on starknet quest with this issue, kindly assign.

**Comment by vestor-dev** [comment]
Hey @fricoben please let me work on this one 
I'm new here and would love to also be a contributor 
Please kindly assign :)

**Comment by martinvibes** [comment]
Hey @fricoben would love to handle this issue 

ETA: 4hrs

**Comment by mayasimi** [comment]
@fricoben kindly assign me this would like to me this my first contribution to starkquest

**Comment by pheobeayo** [comment]
Hello @fricoben I would love to contribute to this project.
I am a web3 frontend developer, I have worked successfully on api-starknet quest and other projects on Onlydust. I am skilled in Typescript, Javascript, Cairo and Rust. 

I will rename the navbar to Defi, verify the path, check the responsiveness of the changed text and verify the styling and link consistency. check the compilation and test.

**Comment by Akshola00** [comment]
@fricoben can i hop on this

**Comment by Kaminar-i** [comment]
hey @fricoben i would love to work on this issue :)

**Comment by blessingbytes** [comment]
Hi @fricoben, pls i would love to work on this issue, and i promise to deliver

**Comment by Benjtalkshow** [comment]
I'd love to give this a go.

**Comment by Emmanex01** [comment]
I’d like to resolve this.

**Comment by 0xdevcollins** [comment]
May I take this issue on?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by SYLVIANNORUKA** [comment]
Can I start working on this?
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by SudiptaPaul-31** [comment]
Can I get this issue?

My approach:

Locate the text Earn and rename with with text deFi on the navbar present.
Add proper styling if required and test it.

ETA-1day

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by imoleayomi19** [comment]
I’d like to work on this. yes
I am a frontend-developer.  I will search where `Earn` is in the code and change it to `deFi `

**Comment by NueloSE** [comment]
Can I take this from here?

ETA <= 24hrs

**Comment by RJMadrigal** [comment]
Hi team!

I would like to request this issue related to updating the text in the navigation bar. I am a systems engineer from Costa Rica, with experience in software development using C#, and I am currently delving into Cairo and Rust. Although this is my first Oddhack, I am excited to contribute and learn while adding value to the project.

I am confident that I can make the necessary updates by following the guidelines provided:

Change text from 'earn' to 'DeFi' in all relevant contexts.
Verify that the link (href) remains unchanged.
Ensure that the design is consistent and that the menu works correctly, including the mobile version.
Perform local tests and make sure everything works correctly before committing.
Additionally, I agree to complete the work within the established deadline and follow best workflow practices, including required labeling and testing.

I look forward to taking on this challenge and collaborating with you on this project. Thank you for your consideration!

**Comment by jancris100** [comment]
Can I be assigned to this?Would love to tackle this! I'm from dojo coding I have 2 years of experience as full stack developer and also Im actually work as mobile developer with figma

**Comment by emmz3230** [comment]
Could I take on this issue? yes
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics.
how i intend to tackle the issue
I will search where the earn is used in the navbar and change it to DEFI. I will make sure the link is checked and changed to DEFI as requested. I will ask the maintainer where the earn are also needed to be changed and do it.

will be glad to work on this project.

Thanks

**Comment by 0xDeon** [comment]
May I pick this up? I'm a returning contributor and can have this delivered in 24hrs

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by ONEONUORA** [comment]
Let me handle this issue!

**Comment by Amarjeet325** [comment]
Hi , I am a proficient Frontend developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by dahtee** [comment]
Can I contribute to this?
I'm a frontend and smart contract developer. I'm a new contributor and I'm looking forward to working on this task.
I have a solid background  in tailwindcss,  react,  nextjs, typescript, js , Cairo and rust. with my experience, I will implement this task as expected.

To implement this, I will fork the repository and checkout to the new branch as expected.
I will implement the following steps:
- Update the navigation item text from 'earn' to 'DeFi' in the navbar component
-  Verify that the href path remains unchanged
-  Check for any mobile/responsive menu instances of this text
 - Verify that the styling remains consistent with the new text
 - Test that the navigation still works correctly
 - Check for any hardcoded references to 'earn' in related components
I will run necessary tests, commit my work and create a PR. 

ETA: 24hrs

**Comment by akintola4** [comment]
Can I handle this task? i would be really happy if I'm assigned this task and e able to help the community, this a link to my twitter https://x.com/photofola

**Comment by akintola4** [comment]
Can I handle this task? i would be really happy if I'm assigned this task and e able to help the community, this a link to my twitter https://x.com/photofola and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by akdavis83** [comment]
I’d like to resolve this. I will run a local instance of this repo and make sure all of the buttons are changed to DeFi as requested.

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. I’d love to help with this update to ensure the navigation bar aligns with the project’s terminology and content.

My workflow:

- Update the navigation bar to rename the ‘earn’ button to ‘DeFi’
- Ensure the change is reflected across all instances in the project
- Verify functionality and consistency after the update

ETA: 48 hrs

**Comment by aspiringLilCoder** [comment]
Is this issue still available?
