### ISSUE TITLE
Create a `/public/tokens` folder for all Starknet yielding tokens icons

### ISSUE THREAD

**Issue by fricoben** [starknet-id/starknet.quest#954]
## Description 📹

Create a `/public/tokens` folder for all Starknet yielding tokens icons. I want all these tokens in SVG form[ imported from this figma
](https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6331-10149&t=VM6Kdu04hCPgKd1U-1)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Add DAI
- [ ] Add USDT
- [ ] Add USDC
- [ ] Add ETH
- [ ] Add BTC
- [ ] Add STRK
- [ ] Add WSTETH
- [ ] Add Ekubo
- [ ] Add Nostra
- [ ] Add ZEND

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by mexes20** [comment]
@fricoben Kindly assign this to me

**Comment by Villarley** [comment]
Hi @fricoben,
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would like to contribute to this issue, I already worked with the project so I understand the workflow of the project and the way to contribute! 
Looking forward to keep contributing to this amazing project!!!

**Comment by NueloSE** [comment]
@fricoben kindly assign me this task.

## steps to solve 

-  create a new `/public/tokens` directory specifically for the icons
- for each token implementation i will:
export each token from the figma as svg, use the appropriate naming convention e.g: dai.svg, usdt.svg etc
- I will handle specific tokens: stablecoins, major crypto, starknet, defi, protocol tokens


ETA <= 10hrs

**Comment by Joe-joe25** [comment]
@fricoben kindly assign me this issue

**Comment by OWK50GA** [comment]
Hi, @fricoben I will like to work on this.
All the steps are listed and simple to follow. ETA is 2 days

**Comment by wheval** [comment]
Hello @fricoben , I'm Wheval and i'm a frontend developer. I have lots of experience working with Figma. 
I would ensure to export the correct frames containing the icons listed above. I would export them in svg format with the appropriate file names and add them to the `/public/tokens` folder.

ETA is <5hrs

**Comment by Benjtalkshow** [comment]
I’d love to work on this task.

**Comment by omsant02** [comment]
i would like to take this issue @fricoben 

i am a new contributor to this repo and want to start my contribution journey with starknet.quest, also i have knowledge of nextjs and page router
ETA : 1 day
Thank you

**Comment by Emmanex01** [comment]
I'd like to take this issue.

**Comment by Akshola00** [comment]
Can I contribute to this one?

**Comment by SYLVIANNORUKA** [comment]
May I take care of this?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by Birdmannn** [comment]
Please I can solve this issue. I initially saw this issue before the ODHack started, and I waited patiently till this time. I will follow all laid down rules, whilst gracefully putting my OnlyDUst blacklisting on the line. I shall no disappoint you sir. Let me quickly hop on this...the details are as clear as day

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by caxtonacollins** [comment]
please assign me this issue, ETA 2days.

**Comment by josephpdf** [comment]
Hi! @fricoben 
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Fork the Repository and Create a Branch:**
- Fork the repository and create a new branch using the issue number:
`git checkout -b fix-[issue-number]`
2. **Implement Changes:**
- Create a /public/tokens folder.
- Add the following token icons in SVG form:
- DAI
- USDT
- USDC
- ETH
- BTC
- STRK
- WSTETH
- Ekubo
- Nostra
- ZEND
3. **Run Tests and Commit Changes:**
- Ensure your changes do not break existing functionality.
- Commit your changes with a clear message:
`git commit -m "Fix: [Short description of the fix]"`
4. **Follow Contribution Guidelines:**
- Make sure you are assigned to the issue before creating a pull request.
- Complete the task within 3 business days.
- In your PR description, close the issue by writing Close #[issue_id].
5. **Review Process:** 
- Submit your PR and change the label to “ready for review”.
- Address any requested changes and update the label back to “ready for review” once done.
- Test your PR locally before pushing and verify that tests and build are working after pushing.

**Comment by ShantelPeters** [comment]
May I be assigned to this?

Firstly i will create a new branch using git checkout -b fix-[issue-number], and then create a /public/tokens folder. 
And then i will Import the SVG icons for DAI, USDT, USDC, ETH, BTC, STRK, WSTETH, Ekubo, Nostra, and ZEND from the provided Figma link into this folder, i wlll run tests to ensure nothing is broken, and commit the changes with a clear message: git commit -m "Fix: Added SVG token icons to /public/tokens folder".

**Comment by SudiptaPaul-31** [comment]
Can I take this issue

**Comment by Michaelkingsdev** [comment]
Let me try this one!

**Comment by PedroCo3lho** [comment]
May I try my hand at this?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript and javascript, would love to work on this , my ETA is >24 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by Yunusabdul38** [comment]
I’d like to work on this,
and make sure it meets the requirements

**Comment by Amarjeet325** [comment]
I’d like to resolve this.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by aspiringLilCoder** [comment]
Can I try solving this issue?
