### ISSUE TITLE
Essential DeFi Concepts Section

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#956]
## Description 📹

**We've added a new section to the DeFi page, located below the table section. This section is designed to help users understand specific DeFi concepts through simple, easy-to-read cards.**

Current page : https://starknet.quest/discover/defi
Design link : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6356-1377&t=9Ky1zTkRkLF10uV9-1

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Create a `Card.tsx` component for each glossary element (without installing new dependencies)
- [ ] Use a similar architecture than this to use your Card component https://v0.dev/chat/B0eTJshQO61?b=b_jRkGxYcCcQD&p=0

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by ShantelPeters** [comment]
Hi @Kevils please can I be assigned to this issue 

i will solve this issue by  creating  a new branch using the command git checkout -b fix-[issue-number]. 
 Next i will implement the changes by creating a Card.tsx component for each glossary element, following the design from Figma and the provided architecture reference.Thereby ensuring the cards are simple, readable, and properly placed below the table on the DeFi page, run tests to verify no existing functionality is broken. Once verified, commit the changes with a clear message, such as "Fix: Added glossary cards to DeFi section," then push and create a pull request for review.

**Comment by thiagoulloa** [comment]
Can I work on this? @Kevils 
I have a solid understanding of Next.js and TailwindCss, and I've previously worked on the project's frontend.
The requirements seem clear to me, and I can get it done quickly!

**Comment by Benjtalkshow** [comment]
Let me try this one!

**Comment by omsant02** [comment]
i would like to take this issue 

i am a new contributor to this repo and want to start my contribution journey with starknet.quest, also i have knowledge of nextjs and page router
ETA : 1 day
Thank you

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by Akshola00** [comment]
Can I tackle this one?

**Comment by 0xdevcollins** [comment]
Is this issue still available?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by SYLVIANNORUKA** [comment]
May I try my hand at this?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Supa-mega** [comment]
Could I take on this issue?

**Comment by blessingbytes** [comment]
hi @Kevils , can you pls assign this issue to me, i promise to deliver

**Comment by Ekene001** [comment]
Hi; is this issue available? I'm a frontend and blockchain developer with proficiency in Next.js, Rust, TypeScript, React and Node.js. I excel at tackling different challenges, staying on top of tight deadlines, and creating solutions that work seamlessly and are user-friendly.
Let me know if I can assist with this task!

**Comment by Ekene001** [comment]
Hi, is this issue available? I'm a frontend and blockchain developer with proficiency in Next.js, Rust, TypeScript, React and Node.js. I excel at tackling different challenges, staying on top of tight deadlines, and creating solutions that work seamlessly and are user-friendly.
Let me know if I can assist with this task!

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Amarjeet325** [comment]
Could I grab this task?

**Comment by aspiringLilCoder** [comment]
May I be assigned to this?

**Comment by Emmanex01** [comment]
Hi, 
Is it okay if I tackle this?

**Comment by omsant02** [comment]
Hi @Kevils ,

i have raised a PR with necessary changes, 
please review it and tell me if any changes needed,

Thank You
