### ISSUE TITLE
Add icon on "bridge" card

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#970]
**An icon is missing or it's not loading on the 'bridge' card on the DeFi page. You can find the icon in the design**

Link : https://starknet.quest/discover/defi

<img width="1440" alt="Screenshot 2024-12-03 at 14 33 51" src="https://github.com/user-attachments/assets/cdc224c2-24de-4dc5-9210-2f57a7af10f8">

Design link : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6356-1640&t=LJZf2qYvEPPdGh7d-1
<img width="401" alt="image" src="https://github.com/user-attachments/assets/680a6db9-cd98-484e-b041-b49e921b37ae">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by michojekunle** [comment]
Hello, is it okay if I tackle this?

I’d like to work on the issue to fix the missing icon on the 'bridge' card in the DeFi page. 

Here’s my approach:

- Analyze the Issue: Compare the 'bridge' card with the provided Figma design to locate the missing icon.
- Implement the Fix: Add the correct icon from the design file to the card and ensure it loads properly.
- Test Locally: Verify the icon displays consistently across browsers and screen sizes.
- Submit PR: Follow the repo’s contribution workflow and reference the issue in the PR.

I’ll complete this task within the 3-day timeframe and ensure the fix meets the design standards.

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by dare117** [comment]
May I try my hand at this?

**Comment by PrathamJha1** [comment]
Can I handle this task?

**Comment by ryzen-xp** [comment]
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by Emmykeyz101** [comment]
Could I take over this issue?

**Comment by Uyouyou** [comment]
HI! Can i be assigned to this task?

**Comment by Shalomnze** [comment]
May I pick this up?
