### ISSUE TITLE
Center the social media buttons in the footer

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#971]
## Description 📹

**Center the social media buttons in the footer**
<img width="1440" alt="Screenshot 2024-12-03 at 14 32 27" src="https://github.com/user-attachments/assets/61ad5cc5-e20a-43ad-9dac-070332177fe2">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by michojekunle** [comment]
I’d like to work on the issue to center the social media buttons in the footer. 

My approach:

- Analyze Current Layout: Identify misalignment issues and review the CSS affecting the buttons.
- Implement Fix: Adjust the CSS to center-align the social media buttons within the footer.
- Test Locally: Ensure the buttons remain centered across all screen sizes and browsers.
- Submit PR: Follow the repo’s workflow and reference the issue in the PR.

I’ll complete this task within the 3-day timeframe, ensuring adherence to design and functionality standards.

Looking forward to your approval to proceed!

**Comment by Nityam573** [comment]
Could I take a shot at this?

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by RomThpt** [comment]
Can I start working on this?

**Comment by dare117** [comment]
Is it okay if I take this?

**Comment by PrathamJha1** [comment]
I’m interested in this one.

**Comment by ryzen-xp** [comment]
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by davedumto** [comment]
Hi I am Dumto, I am a frontend developer and a new contributor to Only Dust. I would love to be assigned this issue. ETA 1 day

**Comment by Prosper1218** [comment]
May I take care of this?

**Comment by Uyouyou** [comment]
Hi, I am a frontend dev. I'd love to be assigned to this task

**Comment by Shalomnze** [comment]
Could I take a shot at this?

**Comment by hoangkianh** [comment]
I can work on this. The est time is 5 mins :D
