### ISSUE TITLE
Remove the footer from the home page

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#972]
## Description 📹

**Remove the footer from the home page**

Link : https://starknet.quest/

<img width="1440" alt="Screenshot 2024-12-03 at 14 31 58" src="https://github.com/user-attachments/assets/7aec790e-b804-4f04-a652-143f1a76772a">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by michojekunle** [comment]
Hi, I’d like to work on the issue to remove the footer from the home page. 

My approach:

- Analyze Current Setup: Review the home page structure and identify the footer’s implementation.
- Implement Changes: Modify the code to remove the footer while ensuring no impact on other pages.
- Test Locally: Verify the footer is removed only on the home page and all functionality remains intact.
- Submit PR: Follow the repo’s workflow and reference the issue in the PR.

I’ll complete this task within the 3-day timeframe, ensuring compliance with project guidelines.

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by aurlic** [comment]
Hey I would be thrilled to work on this issue as it would be my first in this project. I want to keep learning and perfect my skills and think that this issue would be a really good one to work on. Thanks in advance !

**Comment by RomThpt** [comment]
I’d love to work on this task.

**Comment by PrathamJha1** [comment]
Could I take over this issue?

**Comment by ryzen-xp** [comment]
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by davedumto** [comment]
Hi I am Dumto, I am a new contributor to Only dust and this project. I would love to be assigned this issue. ETA 1 day

**Comment by Prosper1218** [comment]
I'd fix this with route grouping or conditionally removing the footer from the home page. I'd love to work on this!

**Comment by Uyouyou** [comment]
Hi, can i be assigned this task? thank you

**Comment by 3th-Enjay** [comment]
I’d love to work on this task.

**Comment by OWK50GA** [comment]
Hi, I'd love to work on this issue.
I'm Wilfrid Okorie, a Frontend Web Developer, and I eat Frontend issues for Breakfast.
I would love to contribute to starknet.quest

I'll first analyze the current setup, and check/how the home page is rendered (the component) and how the footer comes into the home page, and then I'll make my fix. 
My first PR will come within 12 hours
Please assign me to this issue

**Comment by anthozg** [comment]
May I handle this issue?

**Comment by SimplementeCao** [comment]
---

**Hey! I'm SimplementeCao 👋**  

I've contributed to several projects, including:  
- **Cairo Book**  
- **Starknet Book**  
- **Starknet Docs**  
- **Starknet Security Challenges Factory**  
- **Starkane**  
- **SocialSphere**  
- **SafeSwap**  
- **SafeTrustcr**  

Estimated time 24hs

You can learn more about my work through my [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao) and my [GitHub Profile](https://github.com/SimplementeCao).  

**🛠️ Plan to Solve the Issue:**  
1. **Analyze the Codebase:** Review its structure and functionality to understand the current implementation.  
2. **Understand the Issue:** Carefully read the problem description to clarify requirements.  
3. **Research & Plan:** Use provided resources and documentation for deeper insight.  
4. **Ask Questions:** Reach out in the relevant communication channels if any clarification is needed.  
5. **Submit a PR:** Implement the solution and submit a pull request for feedback.  

Let me know if I can start working on this! 🚀  

---

**Comment by Marchand-Nicolas** [comment]
Hello @anthozg are you working on the issue ? Please keep me informed not to be unassigned

**Comment by Munish-Yadav** [comment]
@Marchand-Nicolas  May i work on this issue ? if nobody is working on it currently

**Comment by OWK50GA** [comment]
@Marchand-Nicolas I can work on this 😂
The ODHack is coming to an end

**Comment by Marchand-Nicolas** [comment]
Hello @SimplementeCao still good for you ?

**Comment by SimplementeCao** [comment]
Hi @Marchand-Nicolas yes of course, I'll start it right away 🚀. Thx
