### ISSUE TITLE
Set a different margin/padding and change the Twitter Icon

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#974]
## Description 📹

**Set a different margin/padding between the social network icons and the share button. I suggest setting 8px between the icons and 48px between the icons and the share button. Also change the Twitter Icon by X icon**

<img width="1440" alt="Screenshot 2024-12-03 at 15 01 22" src="https://github.com/user-attachments/assets/5f41a381-665f-4a52-876d-9710dc47895c">

Design link : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=3734-24280&t=LJZf2qYvEPPdGh7d-1

<img width="572" alt="image" src="https://github.com/user-attachments/assets/2e2cc0e2-3fcc-408d-bf4f-72eea94e5d35">

**[Insert clear description here]**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by OWK50GA** [comment]
Hey @Kevils I can work on this
I'm a Frontend Web Developer, and this is an interesting issue.
It is really easy. I'll just change the spacing (margin and padding) through the styles that define them, and change the icon used as the twitter icon is described in the issue description.

ETA - 12 hours

**Comment by michojekunle** [comment]
Hi, I’d like to work on the issue to adjust the margins and replace the Twitter icon as per the design suggestions. 

My approach:

- Update Margins/Paddings: Set 8px spacing between the social icons and 48px between the icons and the share button as per the design.
- Replace Icon: Replace the Twitter icon with the X icon using the provided design link.
- Test Locally: Ensure proper alignment, responsiveness, and visual consistency across devices.
- Submit PR: Follow the repo’s workflow and reference the issue in the PR.

I’ll complete this task within the 3-day timeframe, ensuring adherence to design standards.

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by aurlic** [comment]
I would be thrilled to work on this issue to perfect my skills !

**Comment by RomThpt** [comment]
Can I jump on this task?

**Comment by PrathamJha1** [comment]
Let me handle this issue!

**Comment by ryzen-xp** [comment]
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by davedumto** [comment]
Hi I am Dumto, I am a new contributor to the only dust Platform and this project. I would love to be assigned this issue. ETA 1 day

**Comment by Emmykeyz101** [comment]
Can I jump on this task?

**Comment by Shalomnze** [comment]
Could I be assigned to this?

**Comment by 3th-Enjay** [comment]
Mind if I try this one?

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/lfglabs-dev/starknet.quest/pull/995
