### ISSUE TITLE
Back button animation by hovering

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#976]
## Description 📹

**Make the animation for all 'Back' buttons the same as the 'Social Network' button. You can see it in the Loom video.**
https://www.loom.com/share/b86fb449062640d3a6aa553179ecd6ac
<img width="1440" alt="Screenshot 2024-12-03 at 14 41 48" src="https://github.com/user-attachments/assets/5e1dca7a-60c0-44ef-b149-103a8b37f886">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by michojekunle** [comment]
Hello,

I’d love to tackle this issue to standardize the animations for all 'Back' buttons, aligning them with the smoother animation of the 'Social Network' button. 

Here’s my plan:

- Analyze Current Animations: Compare the 'Back' button animations to the 'Social Network' button to identify differences.
- Implement Changes: Apply the 'Social Network' button animation to all 'Back' buttons for consistency.
- Test Locally: Verify the new animations and ensure no functionality is affected.
- Submit PR: Follow the repo’s workflow and reference the issue in the PR.

I will complete the task within the 3-day timeframe and ensure adherence to guidelines.

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by Nityam573** [comment]
I'd love to work on this!

**Comment by aurlic** [comment]
Hey I would love to get to work on this issue and think that I would be a good fit for this task ! I have already had the chance to work on some frontend for school projects and would be happy to perfect my skills with this issue !

**Comment by RomThpt** [comment]
I'd love to work on this!

**Comment by PrathamJha1** [comment]
I’m interested in this one.

**Comment by ryzen-xp** [comment]
Hi,
 I am proficient Blockchain developer  expert in web development.
I have  contributed many stark net project and more  . 
 please /assign  this issue .
Thank You

**Comment by 3th-Enjay** [comment]
Let me try this one!

**Comment by MaiCVCR** [comment]
Hi, I'm Mai, a developer with several years of experience. I really like your project and would love the opportunity to contribute to it. 
I will review all the "Back" buttons in the application to ensure they have the same hover animation as the "Social Network" button.

**Comment by hoangkianh** [comment]
Can I attempt this issue? Est time is 1 day
