### ISSUE TITLE
Standardize the hover animations for all cards

### ISSUE THREAD

**Issue by Kevils** [starknet-id/starknet.quest#977]
## Description 📹

**It would be necessary to standardize the hover animations for all the cards on Starknet Quest. I suggest using the hover effect from the glossary cards for all the other cards (DeFi cards, quests, collections, etc.), as it is smoother than the one that simply displays a border on the cards.**

Glossary cards link : https://starknet.quest/discover/defi

https://www.loom.com/share/48bcdae44da94757b4ecfe873eca6197

Cards to modify : 
<img width="1440" alt="Screenshot 2024-12-03 at 14 34 17" src="https://github.com/user-attachments/assets/0e534c03-99c1-49e6-8045-f01f81fb5d07">
<img width="1440" alt="Screenshot 2024-12-03 at 14 35 07" src="https://github.com/user-attachments/assets/00c0d416-be1e-43d7-8c13-8f6e9bb12166">
<img width="1440" alt="Screenshot 2024-12-03 at 14 35 57" src="https://github.com/user-attachments/assets/8957b0dc-380f-4c26-9b2e-9158f9c4dfe3">

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by OWK50GA** [comment]
I can work on this

**Comment by michojekunle** [comment]
Hello 👋,

I’d like to work on the issue to standardize hover animations across all cards on Starknet Quest. 

My plan:

- Analyze Current Animations: Compare hover effects on glossary cards and other cards (DeFi, quests, collections).
- Implement Changes: Apply the glossary card hover effect to all cards for a consistent and smooth user experience.
- Test Locally: Ensure functionality is intact and animations work uniformly.
- Submit PR: Follow the repo’s workflow, including referencing the issue in the PR.

I’ll complete the task within the 3-day timeframe and ensure all guidelines are followed.

Looking forward to your approval to proceed!

**Comment by Pvsaint** [comment]
Can I take this issues? I'm a frontend and smart contract developer and a first time contributor in this repo.
If assigned this issue, ETA 48 hours.

**Comment by Nityam573** [comment]
I’m interested in this one.

**Comment by aurlic** [comment]
Hey ! I'm a student at school 42 and I am also currently learning how to code in Rust and Cairo. I would be thrilled to tackle this issue to perfect my skills. I have had the occasion to work on some issues regarding frontend development and think that this would really be a good issue for me.
Thanks in advance and I hope that I will get to work on this project !

**Comment by RomThpt** [comment]
May I be assigned to this?

**Comment by emmanueldindu** [comment]
May I be assigned to this?

**Comment by PrathamJha1** [comment]
Can I attempt this issue?

**Comment by LuisChiej** [comment]
Can I start working on this?

**Comment by davedumto** [comment]
Hello my name is Dumto, I am a frontend developer, I am a new contributor to this project and I would love to work on this issue. Please can I be assigned?. ETA 1 Day

**Comment by Uyouyou** [comment]
Hi,  can i be assigned to this task?

**Comment by Marchand-Nicolas** [comment]
Hello @emmanueldindu are you working on the issue ? Please keep me informed not to be unassigned

**Comment by KeneePatel** [comment]
Hello Nico, 

I would love to work on this. Have decent experience with Next and Typescript. Also have solved an issue here. 

ETA: 1d
TG handle: @patelkenee

**Comment by emarc99** [comment]
Would love to do this. I have contributed to app/api.starknet.id projects in the past, so I have a pretty good understanding of your code base. I will ensure the aim of the task is precisely achieved. I have the necessary FE tech experience.
ETA - 3 days.

**Comment by Villarley** [comment]
hi @Marchand-Nicolas @Kevils 🚀🚀🚀,
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would tackle this issue by using the standard hover animation and adding it to the other by a sustainable solution, always using DRY and clean code.
Would love to contribute again to the project!
Pls feel free to reach out via telegram

**Comment by Birdmannn** [comment]
Hey Dev, can I work on this please?

**Comment by lauchaves** [comment]
Hey 🙋🏻 may I work on this ? 🚀

**Comment by Emmanex01** [comment]
May I solve the issue?
I'm a frontend developer, with 2+ years experience.

**Comment by omsant02** [comment]
Previously, i implemented the whole Essential defi concepts cards section in a previous pr,

i will implement that same smooth hover effect to all cards also

I would like to implement this hover effect, please assign this issue to me @Kevils @Marchand-Nicolas 
ETA : 1 day

Thank you

**Comment by snehaa-eth** [comment]
can i take up this issue @Marchand-Nicolas

**Comment by A6dulmalik** [comment]
I'm a front-end developer and I’d love to work on this task.

**Comment by Marchand-Nicolas** [comment]
Hello @emarc99 is everything okay ? Please keep me informed not to get unassigned

**Comment by emarc99** [comment]
Yes, it's going quite ok. @Marchand-Nicolas 
I will make a PR soon, today.
