### ISSUE TITLE
New Download quest users button

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#978]
## Description 📹

**Add a new button labeled "Download quest users" in the "Preview" tab when editing a quest. The button should call the API endpoint `/admin/quests/get_quest_users?quest_id=<QuestId>` with an `Authorization` header to fetch a JSON response containing quest users and download this data as a JSON file. To avoid making the `questDetails.tsx` file too heavy, implement this button as a separate reusable component, and define the request in `services/authService.ts` for reusability.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
- [ ] Add a new service method in `services/authService.ts` to fetch quest users.
- [ ] Create a new component `DownloadQuestUsersButton.tsx` to handle the "Download quest users" functionality.
- [ ] Import the service method in `DownloadQuestUsersButton.tsx`.
- [ ] Update `questDetails.tsx` to include this new component in the "Preview" tab.

### Update in `services/authService.ts`:

```tsx
const getQuestUsersByQuestId = async (params: { id: number }) => {
  try {
    const response = await fetch(
      `${baseurl}/admin/quests/get_quest_users?quest_id=${params.id}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      }
    );
    if (!response.ok) {
      throw new Error("Failed to fetch quest users");
    }
    return await response.json();
  } catch (err) {
    console.log("Error while getting quest users by quest id", err);
    throw err;
  }
};

export { getQuestUsersByQuestId };
```

### Create `DownloadQuestUsersButton.tsx`:

```tsx
import React from "react";
import Button from "@components/UI/button";
import { useNotification } from "@context/NotificationProvider";
import { getQuestUsersByQuestId } from "@services/authService";

type DownloadQuestUsersButtonProps = {
  questId: string;
};

const DownloadQuestUsersButton: React.FC<DownloadQuestUsersButtonProps> = ({ questId }) => {
  const { showNotification } = useNotification();

  const handleDownload = async () => {
    try {
      const data = await getQuestUsersByQuestId({ id: Number(questId) });

      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `quest_${questId}_users.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading quest users:", error);
      showNotification("Failed to download quest users.", "error");
    }
  };

  return (
    <Button onClick={handleDownload}>
      <p>Download quest users</p>
    </Button>
  );
};

export default DownloadQuestUsersButton;
```

### Update in `questDetails.tsx`:

```tsx
import DownloadQuestUsersButton from "./DownloadQuestUsersButton";

// Inside the render function of AdminQuestDetails component:
<DownloadQuestUsersButton questId={questId} />
```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Add reusable component for downloading quest users using authService"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by Agastya18** [comment]
assign it to me @Marchand-Nicolas

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies.
I would love to contribute to this project. My approach towards this issue after forking the repo would be to first define the API request in authService.ts and verify if the api request is been sent. I would create the new reusable component for the button DownloadQuestUsersButton.tsx. After working on the component (call the API which was defined in authService.ts and i would also create an error handling incase of network when trying to reach the API). I would integrate this component to the "Preview" tab and style it as much as its meant to be. After testing the integration i would create a PR

**Comment by davedumto** [comment]
Hi I am Dumto, I am a Frontend developer and I am a new contributor on the Only Dust platform. I would love to take on this Issue. ETA 1 day

**Comment by MaiCVCR** [comment]
Hi, I'm Mai, a developer with several years of experience. I really like your project and would love the opportunity to contribute to it. 
I can create the new button and component following the mentioned rules and instructions, ensuring their functionality works as expected.
