### ISSUE TITLE
New Download boost winners button

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/starknet.quest#980]
## Description 📹

**Add a new button labeled "Download boost winners" in the "Preview" tab when editing a boost. The button should call the API endpoint `/admin/boosts/get_boost_winners?boost_id=<BoostId>` with an `Authorization` header to fetch a JSON response containing boost winners and download this data as a JSON file. To avoid making the `questDetails.tsx` file too heavy, implement this button as a separate reusable component, and define the request in `services/authService.ts` for reusability.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
- [ ] Add a new service method in `services/authService.ts` to fetch boost winners.
- [ ] Create a new component `DownloadBoostWinnersButton.tsx` to handle the "Download boost winners" functionality.
- [ ] Import the service method in `DownloadBoostWinnersButton.tsx`.
- [ ] Update the relevant file (e.g., `questDetails.tsx` or similar) to include this new component.

### Update in `services/authService.ts`:

```tsx
const getBoostWinnersByBoostId = async (params: { id: number }) => {
  try {
    const response = await fetch(
      `${baseurl}/admin/boosts/get_boost_winners?boost_id=${params.id}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("token")}`,
        },
      }
    );
    if (!response.ok) {
      throw new Error("Failed to fetch boost winners");
    }
    return await response.json();
  } catch (err) {
    console.log("Error while getting boost winners by boost id", err);
    throw err;
  }
};

export { getBoostWinnersByBoostId };
```

### Create `DownloadBoostWinnersButton.tsx`:

```tsx
import React from "react";
import Button from "@components/UI/button";
import { useNotification } from "@context/NotificationProvider";
import { getBoostWinnersByBoostId } from "@services/authService";

type DownloadBoostWinnersButtonProps = {
  boostId: string;
};

const DownloadBoostWinnersButton: React.FC<DownloadBoostWinnersButtonProps> = ({ boostId }) => {
  const { showNotification } = useNotification();

  const handleDownload = async () => {
    try {
      const data = await getBoostWinnersByBoostId({ id: Number(boostId) });

      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `boost_${boostId}_winners.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading boost winners:", error);
      showNotification("Failed to download boost winners.", "error");
    }
  };

  return (
    <Button onClick={handleDownload}>
      <p>Download boost winners</p>
    </Button>
  );
};

export default DownloadBoostWinnersButton;
```

### Update in `questDetails.tsx` or relevant file:

```tsx
import DownloadBoostWinnersButton from "./DownloadBoostWinnersButton";

// Inside the render function of the relevant component:
<DownloadBoostWinnersButton boostId={boostId} />
```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Add reusable component for downloading boost winners using authService"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by davedumto** [comment]
Hello my name is Dumto, I am a frontend developer, I am a  new contributor to this project and I would love to work on this issue. Please can I be assigned?

**Comment by gadyrcdz** [comment]
Can I start working on this? Also, I'm a member of the community Dojo Coding

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies.
I would love to contribute to this project. My approach towards this issue after forking the repo would be to first define the API request in authService.ts and verify if the api request is been sent. I would create the new reusable component for the button DownloadBoostWinnersButton.tsx. I would then work on the component (call the API which was defined in authService.ts and i would also create an error handling incase of network when trying to reach the API as well as other necessary functions) . I would integrate this component to the "Preview" tab and style it as much as its meant to be. After testing the integration i would create a PR

**Comment by Emmykeyz101** [comment]
Can I be assigned to this?

**Comment by Emmykeyz101** [comment]
Mind if I try this one?

**Comment by abhirajprasad** [comment]
I am interested in taking up this issue :)

**Comment by Nanle100** [comment]
Can I work on this, please?

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by gadyrcdz** [comment]
Hey @Marchand-Nicolas, all good? I am just doing the issue and I have a question about this part 
![image](https://github.com/user-attachments/assets/c710c3dc-75c5-428f-8a0d-261678758011)
With the parameter "boostId" , where would I get it? Is there a getter for it or something like that?
